'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {Worker}=require('node:worker_threads'),{CsvFile}=require('../electron/engine.cjs'),stats=require('../electron/statistics.cjs'),{aggregate,joinSamples,sampleTable}=require('../electron/analysis-aggregation.cjs'),{parseAddress,markdownDocument,writeAnalysis,plotData,safeName}=require('../electron/analysis-export.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'csv-analysis-')),png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jKj0AAAAASUVORK5CYII=';
function read(file,modules={}){const scope={exports:{},setTimeout,require:name=>modules[name]??require(name)};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,scope);return scope.exports;}
const plain=v=>JSON.parse(JSON.stringify(v)),plots=read('src/analysis-plot.ts'),types=read('src/analysis-types.ts'),document=read('src/analysis-document.ts',{'./analysis-plot':{...plots,plotPNG:()=>png}}),tableState=read('src/table-state.ts');
test('変量の標本はソート後も元行に基づく非表示と非表示列を除外する',()=>{
  const p=path.join(root,'visibility.csv');fs.writeFileSync(p,'ID,X,Y\na,1,2\nb,2,4\nc,3,6\nd,4,8\n');const file=new CsvFile(p);file.configure({sorts:[{column:1,direction:'desc',mode:'numeric'}]});
  const sample=file.analysisSample([{row0:0,row1:3,col0:0,col1:2}],false,{}, {hiddenRows:[2],hiddenColumns:[2]});assert.deepEqual(sample.headers,['ID','X']);assert.deepEqual(sample.sourceRows,[5,4,2]);assert.deepEqual(sample.rows.map(r=>r[1]),['4','3','1']);assert.equal(sample.populationRows,3);assert.ok(Math.abs(stats.analyze(sample).columnSummaries[0].stats.mean-8/3)<1e-12);file.close();
});
test('隠れた行を全部除外しても空の分析と、選択交差の空欄を正しく返す',()=>{
  const p=path.join(root,'empty-analysis.csv');fs.writeFileSync(p,'A,B\n1,2\n3,4\n');const f=new CsvFile(p),ranges=[{row0:0,row1:0,col0:0,col1:0},{row0:1,row1:1,col0:1,col1:1}];assert.deepEqual(f.analysisSample(ranges).rows,[['1',''],['','4']]);const empty=f.analysisSample(ranges,false,{}, {hiddenRows:[1,2]});assert.equal(empty.populationRows,0);assert.equal(empty.rows.length,0);assert.equal(stats.analyze(empty).pairs.length,0);f.close();
});
test('テーブルのセル色は元行・選択マスクに追従し、ソート・Ctrl飛び飛び・削除後も一致する',()=>{
  const p=path.join(root,'table.csv');fs.writeFileSync(p,'A,B,C\n001,2,3\n002,4,6\n003,6,9\n');const f=new CsvFile(p);f.configure({sorts:[{column:1,direction:'desc',mode:'numeric'}]});const snapshot=f.tableSnapshot([{row0:0,row1:0,col0:0,col1:0},{row0:2,row1:2,col0:2,col1:2}]);assert.deepEqual(snapshot.sourceRows,[3,1]);assert.deepEqual(snapshot.rows,[['003',''],['','3']]);assert.deepEqual(snapshot.mask,[[0],[2]]);const table={...snapshot,id:'a',fileId:'f',sheet:'S'};assert.equal(tableState.cellTables([table],'f','S',3,0).length,1);assert.equal(tableState.cellTables([table],'f','S',3,2).length,0);assert.equal(tableState.cellTables([table],'f','Other',3,0).length,0);assert.equal(tableState.cellTables([],'f','S',3,0).length,0);f.close();
});
test('範囲の正規化・Excelセル番地・テーブルの上限・Windows出力名を検証する',()=>{assert.deepEqual(parseAddress('$AA$20:B2'),{row0:19,row1:1,col0:26,col1:1});assert.throws(()=>parseAddress('A0:B2'));assert.throws(()=>parseAddress('../source.csv'));assert.throws(()=>parseAddress('A2:XFD999999999999999999'));assert.equal(safeName('file|sheet:PC1/PC2?'),'file_sheet_PC1_PC2_');const colors=Array.from({length:100},(_,i)=>tableState.tableColor(i));assert.equal(new Set(colors).size,100);});
function sample(name,headers,rows,rowLabels){return {name,headers,rows,rowLabels,sampleOrdinals:rows.map((_,i)=>i),populationRows:rows.length,populationColumns:headers.length,truncated:false};}
test('列名・行名の一致は合流し、行の順序違いと重複名を出現順で合わせる',()=>{
  const a=sample('A',['ID','X'],[['a','1'],['a','2'],['b','3']],['a','a','b']),b=sample('B',['ID','X','Y'],[['b','3','9'],['a','1','3'],['a','2','6']],['b','a','a']);const joined=joinSamples([a,b],[0,1,2]);assert.equal(joined.alignment.mode,'行名で対応（重複は出現順）');assert.equal(joined.alignment.mergedColumns,2);assert.deepEqual(joined.rows,[['a','1','3'],['a','2','6'],['b','3','9']]);assert.ok(joined.headers[1].includes('合流'));
});
test('名前が一致しない場合は行位置で対応し、同名の値が食い違う列は上書きしない',()=>{
  const a=sample('A',['X'],[['1'],['2'],['3']],[null,null,null]),b=sample('B',['X'],[['10'],['20']],[null,null]);const joined=joinSamples([a,b],[0,1,2]);assert.equal(joined.alignment.mode,'先頭からの行位置で対応');assert.equal(joined.alignment.conflictingColumns,1);assert.deepEqual(joined.rows,[['1','10'],['2','20'],['3','']]);
});
test('複数範囲の標本は共通の行序数を使い、不足する末尾を捏造しない',async()=>{
  const sources=[{name:'Short',table:{headers:['X'],rows:Array.from({length:6000},(_,i)=>[String(i)])}},{name:'Long',table:{headers:['Y'],rows:Array.from({length:9000},(_,i)=>[String(i*3)])}}];const result=await aggregate(sources,sampleTable);const pair=result.pairs.find(p=>p.x.includes('X')&&p.y.includes('Y'));assert.ok(Math.abs(pair.r-1)<1e-12);assert.ok(Math.abs(pair.slope-3)<1e-9);assert.equal(result.populationRows,9000);assert.ok(result.sampledRows<=5000);assert.equal(result.truncated,true);assert.equal(result.sources[0].populationRows,6000);
});
test('既定の多変量分析は相関のない組合せと定数を表示せず、指定範囲は広く比較する',async()=>{const table={headers:['X','Y','Constant','Noise'],rows:Array.from({length:20},(_,i)=>[String(i),String(i*3+2),'7',String(i%2)])};const all=stats.analyze(table,true,{correlatedOnly:true});assert.equal(all.columnSummaries.length,2);assert.ok(all.pairs.every(p=>Math.abs(p.r)>=.7||Math.abs(p.spearman)>=.7));assert.ok(all.pca);assert.equal(stats.analyze(table,false).columnSummaries.length,4);assert.equal(all.pca.scores[0].standard.length,2);assert.ok(all.insights.every(v=>!v.includes('Constant')));const specified=await aggregate([{name:'Range',table}],sampleTable);assert.equal(specified.columnSummaries.length,4);assert.equal(specified.correlatedOnly,false);assert.ok(specified.pca.dimensions.some(v=>v.endsWith('Noise')));const whole=await aggregate([{name:'File',table,all:true}],sampleTable);assert.equal(whole.columnSummaries.length,2);assert.equal(whole.correlatedOnly,true);});
test('PCと元列を各軸2項目まで割り当て、回転・カテゴリ・OBJ座標と系列を保持する',()=>{
  const result=stats.analyze({headers:['売上','費用','利益'],rows:Array.from({length:12},(_,i)=>[String(i+1),String(i*2+1),String(i*3+2)])},true),pca=result.pca,axes=[['pc:0','column:0'],['pc:1','column:1'],['pc:2','column:2']],model=plots.pcaPlot(pca,axes,3,true);assert.equal(model.points.length,pca.scores.length*2);assert.ok(plots.categoryName(pca,'pc:0').includes('売上'));const g=plots.geometry(model,{yaw:0,pitch:20,roll:10},35);assert.equal(g.axes.length,3);assert.notEqual(g.points[0].x,plots.geometry(model,{yaw:0,pitch:20,roll:10},0).points[0].x);const obj=plots.objText(model);assert.equal(obj.split('\n').filter(l=>l.startsWith('v ')).length,model.points.length);assert.equal(obj.split('\n').filter(l=>l.startsWith('o ')).length,2);assert.equal(plots.seriesCorrelations(model).length,3);assert.match(plots.plotFilename(model),/PC1.*PC2.*PC3/);assert.ok(plotData(obj,'obj').length>0);
});
test('分析MDは折りたたみと独立した全統計・相関・グラフを含み、変量出力にはPCAを含めない',async()=>{
  const result=stats.analyze({headers:['X','Y'],rows:Array.from({length:6},(_,i)=>[String(i+1),String(i*2+1)])},true),doc=await document.analysisDocument(result,false,'範囲');const text=markdownDocument(plain(doc));assert.match(text,/四分位範囲/);assert.match(text,/歪度/);assert.match(text,/Pearson相関/);assert.match(text,/data:image\/png;base64/);assert.equal(doc.plots.length,3);assert.doesNotMatch(text,/主成分|寄与率/);
});
test('グラフ付きXLSXは画像・生の数値・描画データを読み直せて、式らしい列名も文字列で保存する',async()=>{
  const JSZip=require('jszip'),XLSX=require('@e965/xlsx'),target=path.join(root,'analysis.xlsx'),doc={name:'分析',sections:[{title:'全統計',paragraphs:['全文'],tables:[{headers:['項目','値'],rows:[['=HYPERLINK("evil")',123.5]]}]}],plots:[{title:'Graph',image:png,headers:['X','Y'],rows:[[1,2],[2,4]]}]};await writeAnalysis(doc,target,'xlsx');const zip=await JSZip.loadAsync(fs.readFileSync(target));assert.equal(Object.keys(zip.files).filter(p=>/^xl\/media\/.*\.png$/.test(p)).length,1);const book=XLSX.readFile(target);assert.deepEqual(book.SheetNames,['分析結果','グラフ','描画データ']);const cell=Object.values(book.Sheets['分析結果']).find(c=>c?.v==='=HYPERLINK("evil")');assert.equal(cell.t,'s');assert.equal(cell.f,undefined);assert.equal(book.Sheets['描画データ'].B3.v,2);assert.equal(book.Sheets['分析結果'].B4.v,123.5);
});
test('非アクティブシートの集計とテーブル作成は、現在シート・見出し・フィルターを変えない',async()=>{
  const XLSX=require('@e965/xlsx'),target=path.join(root,'sheets.xlsx'),wb=XLSX.utils.book_new();for(const name of ['Data','Other'])XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['X','Y'],[1,2],[2,4],[3,6]]),name);XLSX.writeFile(wb,target);
  const worker=new Worker(path.resolve('electron/worker.cjs'));let id=0;const call=(method,args)=>new Promise((resolve,reject)=>{const requestId=++id;const handler=m=>{if(m.requestId!==requestId)return;worker.off('message',handler);m.error?reject(Error(m.error)):resolve(m.result);};worker.on('message',handler);worker.postMessage({requestId,method,args});});
  try{await call('open',{path:target,options:{}});await call('configure',{filters:[{column:0,mode:'gt',value:'1'}]});const before=await call('page',{start:0,limit:5});const table=await call('createTable',{sheet:'Other',address:'A2:B4'});assert.equal(table.rows.length,3);await call('analyze',{all:true});await call('analysisSampleSheet',{sheet:'Other',all:true,limits:{rows:3}});assert.deepEqual(await call('page',{start:0,limit:5}),before);await assert.rejects(call('createTable',{sheet:'Other',address:'A2:C4'}),/範囲外/);assert.deepEqual(await call('page',{start:0,limit:5}),before);}finally{await worker.terminate();}
});
