import {launchWithoutTutorial} from './electron-profile';
import {test,expect,type ElectronApplication,type Page} from '@playwright/test';
import {readableText} from './ui-contrast';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const XLSX=require('@e965/xlsx'),root=process.cwd(),out=fs.mkdtempSync(path.join(os.tmpdir(),'csv-analysis-ui-')),file=path.join(out,'Book.xlsx'),csv=path.join(out,'Third.csv');
const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['ID','X','Y','売上額','Noise'],...Array.from({length:12},(_,i)=>['Row'+(i+1),i+1,(i+1)*3+2,(i+1)*4+7,i%2])]),'Data');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['ID','Z'],...Array.from({length:12},(_,i)=>['Row'+(12-i),(12-i)*10])]),'Other');XLSX.writeFile(book,file);fs.writeFileSync(csv,'ID,W\n'+Array.from({length:12},(_,i)=>'Row'+(12-i)+','+(12-i)**2).join('\n'));
const original=fs.readFileSync(file),originalCsv=fs.readFileSync(csv);let app:ElectronApplication,page:Page;const errors:string[]=[];
const cell=(r:number,c:number)=>page.locator(`[data-row="${r}"][data-col="${c}"]`),mode=(name:string)=>page.getByRole('tab',{name,exact:true});
test.describe.configure({mode:'serial'});
test.beforeAll(async()=>{app=await launchWithoutTutorial({args:['--no-sandbox','--user-data-dir='+path.join(out,'profile'),'.',file],cwd:root,env:{...process.env,CSV_LENS_TEST:'1'}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await expect(cell(0,1)).toHaveText('1',{timeout:30000});await page.getByLabel('左ペインを開閉').click();});
test.afterAll(async()=>{await app.close();expect(errors).toEqual([]);expect(fs.readFileSync(file)).toEqual(original);expect(fs.readFileSync(csv)).toEqual(originalCsv);});
async function saveTo(target:string){await app.evaluate(({dialog},target)=>{dialog.showSaveDialog=async(...args:any[])=>{(dialog as any).lastAnalysisPath=args.at(-1)?.defaultPath;return {canceled:false,filePath:target};};},target);}
async function range(r:number,c:number){await cell(0,1).click();await cell(r,c).click({modifiers:['Shift']});}

test('非表示行列を除外し、個別グラフと閉じた全項目をMD・XLSX出力する',async()=>{
  await range(11,2);await page.locator('.column-head[data-head-index="2"] .header-eye-zone').hover();await page.getByLabel('列Cを非表示',{exact:true}).click();await page.locator('.row-head[data-head-index="2"] .header-eye-zone').hover();await page.getByLabel('行4を非表示',{exact:true}).click();
  await mode('変量分析（選択範囲）').click();await expect(page.locator('.analysis-variable')).toHaveCount(1);await expect(page.locator('.analysis-sample')).toContainText('11 / 11行');await expect(page.locator('.analysis-sample')).toContainText('1 / 1列');
  const detail=page.locator('.analysis-variable').first();await detail.locator('summary').click();await expect(detail.locator('.analysis-plot')).toBeVisible();const image=path.join(out,'variable.png');await saveTo(image);await detail.getByRole('button',{name:'PNG保存',exact:true}).click();await expect.poll(()=>fs.existsSync(image)).toBe(true);expect(fs.readFileSync(image).subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');await detail.locator('summary').click();
  const md=path.join(out,'variable.md');await saveTo(md);await page.getByRole('button',{name:'分析を.md出力',exact:true}).click();await expect.poll(()=>fs.existsSync(md)).toBe(true);const text=fs.readFileSync(md,'utf8');expect(text).toContain('自己相関（1期）');expect(text).toContain('四分位範囲');expect(text).toContain('data:image/png;base64');expect(text).not.toContain('主成分');expect(text).not.toContain('## Y');expect(await detail.getAttribute('open')).toBeNull();
  const xlsx=path.join(out,'variable.xlsx');await saveTo(xlsx);await page.getByRole('button',{name:'分析を.xlsx出力',exact:true}).click();await expect.poll(()=>fs.existsSync(xlsx)).toBe(true);const zip=await require('jszip').loadAsync(fs.readFileSync(xlsx));expect(Object.keys(zip.files).filter(p=>/^xl\/media\/.*\.png$/.test(p))).toHaveLength(1);const result=XLSX.readFile(xlsx);expect(result.SheetNames).toEqual(['分析結果','グラフ','描画データ']);expect(Object.values(result.Sheets['分析結果']).some((v:any)=>v.v==='自己相関（1期）')).toBe(true);
  await page.getByLabel('表示状態を復元').click();await mode('ワークスペース').click();
});

test('Ctrl+T・番地追加・別シート選択保持・名前で集計・全域実行・テーブル削除',async()=>{
  await range(11,2);await page.locator('.grid-scroll').press('Control+t');await expect(mode('テーブルプレビュー')).toHaveAttribute('aria-selected','true');await expect(page.locator('.saved-table')).toHaveCount(1);await expect(page.locator('.saved-table header input')).toHaveValue('Book.xlsx|Data|B2:C13');await expect(cell(0,1)).toHaveClass(/table-cell/);
  await page.getByLabel('テーブル追加元シート').selectOption('Other');await page.getByLabel('テーブルのセル番地').fill('A1:B13');await page.getByRole('button',{name:'番地から追加',exact:true}).click();await expect(page.locator('.saved-table')).toHaveCount(2);await expect(cell(0,1)).toHaveText('1');await page.locator('.saved-table header input').nth(1).fill('その他Z');
  const colors=await page.locator('.saved-table').evaluateAll(nodes=>nodes.map(el=>getComputedStyle(el).getPropertyValue('--table-color')));expect(new Set(colors).size).toBe(2);
  await mode('Other').click();await expect(page.locator('[data-header-row="0"] [data-header-col="1"]')).toHaveClass(/table-cell/);await page.locator('[data-header-row="0"] [data-header-col="1"]').click({button:'right'});await expect(page.getByRole('menu',{name:'テーブルの操作'})).toBeVisible();await page.locator('.head-menu-shield').click({position:{x:1000,y:500}});await cell(0,1).click();await cell(11,1).click({modifiers:['Shift']});await mode('Data').click();await expect(cell(11,2)).toHaveAttribute('aria-selected','true');await mode('Other').click();await expect(cell(11,1)).toHaveAttribute('aria-selected','true');
  await app.evaluate(({BrowserWindow},target)=>BrowserWindow.getAllWindows()[0].webContents.send('csv:paths',[target]),csv);await expect(cell(0,1)).toHaveText('144');await cell(0,1).click();await cell(11,1).click({modifiers:['Shift']});await page.locator('.grid-scroll').press('Control+t');await expect(page.locator('.saved-table')).toHaveCount(3);
  await mode('多変量分析（ファイル全域）').click();await page.getByRole('radio',{name:'選択範囲を集計',exact:true}).check();await expect(page.locator('.analysis-source-list p')).toHaveCount(3);await expect(page.locator('.analysis-alignment')).toContainText('行名で対応');await expect(page.locator('.analysis-pairs')).toContainText('Other');await expect(page.locator('.analysis-pca')).toBeVisible();
  await page.getByRole('radio',{name:'すべてを集計',exact:true}).check();await expect(page.locator('.analysis-sample')).toHaveCount(0);await expect(page.getByLabel('すべてを集計を実行')).toBeEnabled();await page.getByLabel('すべてを集計を実行').click();await expect(page.locator('.analysis-sample')).toContainText('12 / 12行');await expect(page.locator('.analysis-alignment')).toContainText('合流した列 2');
  await page.locator('.tabbar').getByRole('button',{name:'Third.csvを閉じる',exact:true}).click();await page.getByRole('radio',{name:'指定テーブルから集計',exact:true}).check();await expect(page.locator('.analysis-table-list input')).toHaveCount(3);await expect(page.locator('.analysis-alignment')).toContainText('行名で対応');await expect(page.locator('.analysis-pca')).toBeVisible();
  await mode('Data').click();await cell(0,1).click({button:'right'});await page.getByRole('menu',{name:'テーブルの操作'}).getByRole('menuitem').click();await expect(page.locator('.saved-table')).toHaveCount(2);await expect(cell(0,1)).not.toHaveClass(/table-cell/);await page.locator('.saved-table').filter({has:page.locator('input[value="その他Z"]')}).getByRole('button').click();await expect(page.locator('.saved-table')).toHaveCount(1);
  await page.getByRole('radio',{name:'分析シート',exact:true}).check();await expect(page.locator('.analysis-pca')).toBeVisible();
});

test('PC・元列の2系列、3Dホイールと自動回転、PNG・2周GIF・OBJ・完全分析出力',async()=>{
  test.setTimeout(90000);await expect(page.locator('.analysis-pca')).toBeVisible();const pca=page.locator('.analysis-pca'),guide=pca.getByRole('region',{name:'主成分分析の解説'}),method=guide.locator('.pca-method');
  await expect(guide).toBeVisible();await expect(method).not.toHaveAttribute('open');await expect(guide.locator('.pca-color-meaning')).toContainText('似た傾向');
  const legendColors=()=>guide.locator('.pca-color-swatch').evaluateAll(nodes=>nodes.map(el=>getComputedStyle(el).backgroundColor)),pointColors=()=>pca.locator('.analysis-plot circle').evaluateAll(nodes=>[...new Set(nodes.map(el=>getComputedStyle(el).fill))]);
  expect((await legendColors()).sort()).toEqual((await pointColors()).sort());await method.locator('summary').click();await expect(method).toContainText('Jacobi法');await expect(method).toContainText('12行');await expect(method).toContainText('寄与率');await method.locator('summary').click();
  await page.getByLabel('分析の次元').selectOption('3');await expect(page.getByLabel('3D方向ホイール')).toBeVisible();await page.getByLabel('3D方向ホイール').scrollIntoViewIfNeeded();const first=await pca.locator('.analysis-plot circle').first().getAttribute('cx'),wheel=(await page.getByLabel('3D方向ホイール').boundingBox())!;await page.mouse.move(wheel.x+40,wheel.y+40);await page.mouse.down();await page.mouse.move(wheel.x+65,wheel.y+52,{steps:5});await page.mouse.up();await expect.poll(()=>pca.locator('.analysis-plot circle').first().getAttribute('cx')).not.toBe(first);
  await page.locator('.axis-choices summary').click();for(const [axis,index] of [['X',0],['Y',1],['Z',2]] as const)await page.getByLabel(axis+'軸 項目2').selectOption('column:'+index);await expect(page.locator('.series-correlations p')).toHaveCount(3);await expect(pca.locator('.analysis-plot circle')).toHaveCount(24);await expect(pca.locator('.pca-categories')).toContainText('PC1：');await expect(guide.locator('.pca-color-meaning')).toContainText('比較する系列');await expect(guide.getByRole('listitem')).toHaveCount(2);expect((await legendColors()).sort()).toEqual((await pointColors()).sort());
  const angle=await page.getByLabel('3D分析の回転').inputValue();await page.getByLabel('自動回転を開始').click();await expect.poll(()=>page.getByLabel('3D分析の回転').inputValue()).not.toBe(angle);await page.getByLabel('自動回転を停止').click();await expect(page.getByLabel('自動回転を開始')).toHaveAttribute('aria-pressed','false');
  await page.getByLabel('分析の次元').selectOption('2');const png=path.join(out,'pca.png');await saveTo(png);await pca.getByRole('button',{name:'PNG保存',exact:true}).click();await expect.poll(()=>fs.existsSync(png)).toBe(true);await page.getByLabel('分析の次元').selectOption('3');
  const gif=path.join(out,'pca.gif');await saveTo(gif);await pca.getByRole('button',{name:'.gif',exact:true}).click();await expect.poll(()=>fs.existsSync(gif),{timeout:45000}).toBe(true);const decoder=new (require('omggif').GifReader)(fs.readFileSync(gif));expect(decoder.numFrames()).toBe(73);expect(decoder.loopCount()).toBeNull();expect(decoder.frameInfo(0).delay).toBe(8);const a=new Uint8Array(decoder.width*decoder.height*4),b=new Uint8Array(a.length);decoder.decodeAndBlitFrameRGBA(0,a);decoder.decodeAndBlitFrameRGBA(18,b);expect(a.some((v,i)=>v!==b[i])).toBe(true);
  const obj=path.join(out,'pca.obj');await saveTo(obj);await pca.getByRole('button',{name:'.obj',exact:true}).click();await expect.poll(()=>fs.existsSync(obj)).toBe(true);const geometry=fs.readFileSync(obj,'utf8');const vertices=geometry.split('\n').filter(l=>l.startsWith('v '));expect(vertices.length).toBeGreaterThan(24*86);expect(geometry.split('\n').filter(l=>l.startsWith('f ')).length).toBeGreaterThan(24*168);expect(geometry).not.toMatch(/^p /m);expect(geometry).toContain('o series_2');for(const axis of 'XYZ'){expect(geometry).toContain('o axis_'+axis+'\n');const label=geometry.split('o axis_label_'+axis+'\n')[1].split('\no ')[0];expect(label).toMatch(/^f /m);}expect(geometry).toContain('# Z: PC3 / 売上額（標準化）');const filename=await app.evaluate(({dialog})=>(dialog as any).lastAnalysisPath);expect(filename).toMatch(/PC1.*PC2.*PC3/);
  const md=path.join(out,'multivariate.md');await saveTo(md);await page.getByRole('button',{name:'分析を.md出力',exact:true}).click();await expect.poll(()=>fs.existsSync(md)).toBe(true);const text=fs.readFileSync(md,'utf8');expect(text).toContain('主成分の分布');expect(text).toContain('Jacobi法');expect(text).toContain('k-means法');expect(text).toContain('比較する系列');expect(await method.getAttribute('open')).toBeNull();expect(text).toContain('Pearson相関');expect(text).toContain('歪度');expect(text).toContain('PC3');expect((text.match(/data:image\/png;base64/g)||[]).length).toBeGreaterThan(3);
  const xlsx=path.join(out,'multivariate.xlsx');await saveTo(xlsx);await page.getByRole('button',{name:'分析を.xlsx出力',exact:true}).click();await expect.poll(()=>fs.existsSync(xlsx)).toBe(true);const zip=await require('jszip').loadAsync(fs.readFileSync(xlsx));expect(Object.keys(zip.files).filter(p=>/^xl\/media\/.*\.png$/.test(p)).length).toBeGreaterThan(3);const exported=XLSX.readFile(xlsx),cells=Object.values(exported.Sheets['分析結果']).map((c:any)=>String(c.v||''));expect(cells.some(c=>c.includes('Jacobi法'))).toBe(true);expect(cells.some(c=>c.includes('比較する系列'))).toBe(true);await page.locator('.axis-choices summary').click();await method.locator('summary').click();for(const theme of ['light','dark']){for(const accent of ['#0f6cbd','#107c41','#5b5fc7']){await page.getByLabel('設定',{exact:true}).click();await page.getByLabel('カラープロファイル').selectOption(theme);await page.getByLabel('アクセントカラー').selectOption(accent);await page.getByRole('button',{name:'完了',exact:true}).click();await readableText(page);}await pca.scrollIntoViewIfNeeded();await page.screenshot({path:'docs/images/analysis-controls-'+theme+'.png'});}
});
