'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),stats=require('../electron/statistics.cjs');
function read(file,modules={}){const scope={exports:{},setTimeout,require:name=>modules[name]??require(name)};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,scope);return scope.exports;}
const layout=read('src/plot-layout.ts'),plots=read('src/analysis-plot.ts',{'./plot-layout':layout}),explanation=read('src/pca-explanation.ts'),document=read('src/analysis-document.ts',{'./analysis-plot':{...plots,plotPNG:()=> 'data:image/png;base64,fixture'},'./pca-explanation':explanation});
const measure=(text,font)=>[...text].reduce((n,c)=>n+(c.charCodeAt(0)>255?font:font*.6),0),close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
function fixture(){const rows=Array.from({length:1002},(_,i)=>[i%100+Math.sin(i),i%100*2+Math.cos(i),i%100*-3+Math.sin(i*.3)]);rows[502]=[20000,50000,-30000];return {rows,result:stats.analyze({headers:['X','Y','Z'],rows:[...rows,[null,1,2]]},true,{autoExclude:false})};}
test('重心は欠損を除いた全分析行から求め、描画標本に含まれない1件の群も保持する',()=>{
  const {rows,result}=fixture(),pca=result.pca,means=rows[0].map((_,c)=>stats.moments(rows.map(r=>r[c]))),standard=rows.map(row=>row.map((v,c)=>(v-means[c].mean)/means[c].sd)),scores=standard.map(row=>pca.loadings.map(vector=>row.reduce((sum,v,c)=>sum+v*vector[c],0))),groups=stats.kmeans(scores,3);
  assert.equal(pca.completeRows,1002);assert.equal(pca.scores.length,334);assert.equal(pca.centroids.reduce((sum,c)=>sum+c.count,0),1002);
  for(const center of pca.centroids){const indices=groups.assignments.flatMap((c,i)=>c===center.cluster?[i]:[]);assert.equal(center.count,indices.length);for(let d=0;d<3;d++){close(center.values[d],indices.reduce((s,i)=>s+scores[i][d],0)/indices.length);close(center.standard[d],indices.reduce((s,i)=>s+standard[i][d],0)/indices.length);}}
  const rare=pca.centroids.find(c=>c.count===1);assert.ok(rare);assert.ok(pca.scores.every(p=>p.cluster!==rare.cluster));
  for(let d=0;d<3;d++)close(pca.centroids.reduce((sum,c)=>sum+c.count*c.standard[d],0)/1002,0);
  const small=stats.analyze({headers:['X','Y'],rows:[[1,2],[2,4],[3,6]]},true).pca;assert.equal(small.centroids.length,0);assert.equal(plots.pcaPlot(small,plots.initialAxes(small),2,false).centers.length,0);
});
test('2D・3DのPC／元列・2系列・ゼロ軸で重心を投影し、間引き外の群にも同じ回転と縮尺を適用する',()=>{
  const {result}=fixture(),pca=result.pca,axes=[['pc:0','column:0'],['pc:1','column:1'],['pc:2','zero']];
  for(const dimension of [2,3]){const model=plots.pcaPlot(pca,axes,dimension,false);assert.equal(model.centers.length,6);for(const c of model.centers){const raw=pca.centroids.find(p=>p.cluster===c.cluster);close(c.x,c.series?raw.standard[0]:raw.values[0]);close(c.y,c.series?raw.standard[1]:raw.values[1]);close(c.z,dimension===2||c.series?0:raw.values[2]);assert.equal(c.count,raw.count);}
    for(const yaw of [0,70,180]){const orientation={yaw,pitch:-20,roll:15},g=plots.geometry(model,orientation,30),extent=Math.max(1,...[...model.points,...model.centers].flatMap(p=>[Math.abs(p.x),Math.abs(p.y),Math.abs(p.z)]));for(const c of g.centers){const p=c.original,n={x:p.x/extent,y:p.y/extent,z:p.z/extent},v=dimension===3?plots.rotate(n,orientation,30):n;close(c.x,240+v.x*132);close(c.y,160-v.y*106);}const exportLayout=layout.plotLayout(model,g,measure);assert.ok(exportLayout.centers.every(c=>c.x>=exportLayout.plot.x&&c.x<=exportLayout.plot.x+exportLayout.plot.width&&c.y>=exportLayout.plot.y&&c.y<=exportLayout.plot.y+exportLayout.plot.height));}}
});
test('重なる6群の中心ラベルは枠内で重ならず、Canvasも2D・3Dの白／ダーク両配色に菱形と群名を描画する',()=>{
  const centers=Array.from({length:6},(_,i)=>({x:240,y:160,label:`系列${Math.floor(i/3)+1} / 群${i%3+1} 中心`})),rect={x:10,y:14,width:460,height:288},boxes=layout.centerLabelLayout(centers,rect,measure);
  for(const b of boxes){assert.ok(b.x>=rect.x&&b.y>=rect.y&&b.x+b.width<=rect.x+rect.width&&b.y+b.height<=rect.y+rect.height);for(const a of boxes.filter(a=>a!==b))assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y);}
  const {result}=fixture();for(const dimension of [2,3])for(const theme of ['light','dark']){const model=plots.pcaPlot(result.pca,plots.initialAxes(result.pca),dimension,false),labels=[];let diamonds=0;const context={save(){},restore(){},fillRect(){},translate(){},scale(){},beginPath(){},rect(){},clip(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},closePath(){diamonds++;},fillText(text){labels.push(text);},measureText(text){return {width:measure(text,parseFloat(this.font))};}};plots.drawPlot({width:960,height:720,getContext:()=>context},model,{yaw:40,pitch:-20,roll:0},30,plots.plotColors(theme));assert.equal(diamonds,3);assert.ok(labels.filter(l=>/群\d 中心/.test(l)).length===3);}
});
test('MD・XLSXの分析資料に群の全件数と現在の軸の重心を追加し、変量分析には含めない',async()=>{
  const {result}=fixture(),model=plots.pcaPlot(result.pca,[['pc:0','column:0'],['pc:1','column:1'],['pc:2','column:2']],3,false),doc=await document.analysisDocument(result,true,'fixture',{model,orientation:{yaw:0,pitch:0,roll:0},angle:0,paragraphs:[]}),section=doc.sections.find(s=>s.title==='クラスター中心（重心）');assert.ok(section);assert.equal(section.tables[0].rows.length,6);assert.equal(section.tables[0].headers.length,6);assert.ok(section.paragraphs[0].includes('間引き前'));section.tables[0].rows.forEach((r,i)=>{const c=model.centers[i];assert.equal(r[2],c.count);close(r[3],c.x);close(r[4],c.y);close(r[5],c.z);});const variable=await document.analysisDocument(result,false,'fixture');assert.ok(variable.sections.every(s=>!s.title.includes('クラスター中心')));
});
