const {test}=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript'),vm=require('node:vm'),fs=require('node:fs');
const context={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/data.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);const {numeric,chartData,mergeTables,selectionSize,documentMarkdown}=context.exports;
const plain=value=>JSON.parse(JSON.stringify(value));
test('グラフは数値列を抽出し、ラベルと未選択の空欄を保持',()=>{const model=plain(chartData({headers:['月','売上','利益'],rows:[['Jan','12',''],['Feb','13','3']]}));assert.deepEqual(model.labels,['Jan','Feb']);assert.deepEqual(model.series[1].values,[null,3]);assert.equal(numeric('00012'),12);assert.equal(numeric('2026/10/02'),null);assert.equal(numeric('Infinity'),null);});
test('縦結合は見出しを合わせ、同名見出しが重複してもセルを落とさない',()=>{const blocks=[{id:'1',name:'a',table:{headers:['A','A','B'],rows:[['a1','a2','b']]}},{id:'2',name:'b',table:{headers:['B','A','A'],rows:[['bb','aa1','aa2']]}}];assert.deepEqual(plain(mergeTables(blocks,'rows',true)),{headers:['A','A','B'],rows:[['a1','a2','b'],['aa1','aa2','bb']]});});
test('横結合は行位置で合わせ、足りない行を空欄で補う',()=>{const blocks=[{table:{headers:['A'],rows:[['1'],['2']]}},{table:{headers:['B'],rows:[['00012']]}}];assert.deepEqual(plain(mergeTables(blocks,'columns',false)),{headers:['A','B'],rows:[['1','00012'],['2','']]});});

test('複数選択のセル数は重複を数えず、巨大範囲も走査しない',()=>{assert.equal(selectionSize([{row0:0,row1:2,col0:0,col1:2},{row0:1,row1:3,col0:1,col1:3}]),14);assert.equal(selectionSize([{row0:0,row1:10000000,col0:1,col1:1}]),10000001);});

test('Markdown文書はテキスト・表・グラフ・テキストのブロック順を保持',()=>{const blocks=[{id:'1',name:'導入',kind:'text',content:'# 導入',table:{headers:[],rows:[]}},{id:'2',name:'表',kind:'table',table:{headers:['ID','値'],rows:[['00012','3']]}},{id:'3',name:'図',kind:'chart',table:{headers:[],rows:[]},image:'data:image/png;base64,AA=='},{id:'4',name:'結論',kind:'text',content:'結論のテキスト',table:{headers:[],rows:[]}}];const source=documentMarkdown(blocks);assert.ok(source.indexOf('# 導入')<source.indexOf('| ID'));assert.ok(source.indexOf('| ID')<source.indexOf('![図]'));assert.ok(source.indexOf('![図]')<source.indexOf('結論のテキスト'));assert.equal(require('../electron/tables.cjs').documentText(blocks),source);});
