import {launchWithoutTutorial} from './electron-profile';
import {test,expect,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {readableText} from './ui-contrast';
const root=process.cwd(),profile=fs.mkdtempSync(path.join(os.tmpdir(),'csv-docking-')),file=path.join(root,'samples/sales.csv');
let app:ElectronApplication,page:Page;const errors:string[]=[];
test.describe.configure({mode:'serial'});
async function launch(){app=await launchWithoutTutorial({args:['--no-sandbox','--user-data-dir='+profile,'.',file],cwd:root,env:{...process.env,CSV_LENS_TEST:'1'}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await expect(page.locator('[data-row="0"][data-col="1"]')).toHaveText('1200000',{timeout:30000});}
test.beforeAll(launch);test.afterAll(async()=>{await app.close();expect(errors).toEqual([]);});
async function dropTab(id:string,position:string){const source=page.locator('#dock-tab-'+id);await source.scrollIntoViewIfNeeded();const start=(await source.boundingBox())!;await page.mouse.move(start.x+start.width/2,start.y+start.height/2);await page.mouse.down();await page.mouse.move(start.x+start.width/2+10,start.y+start.height/2+10);const target=page.locator('.dock-drop-zone.drop-'+position);await expect(target).toBeVisible();const end=(await target.boundingBox())!;await page.mouse.move(end.x+end.width/2,end.y+end.height/2,{steps:8});await page.mouse.up();await expect(page.locator('.dock-slot.'+position+' #dock-tab-'+id)).toHaveAttribute('aria-selected','true');}
async function closeGroup(id:string){await page.locator('.dock-rail').filter({has:page.locator('#dock-tab-'+id)}).locator('.boundary-toggle').click();}
test('境界のタブ名の実ドラッグで上に移動し、グラフとテーブルを別タブとして結合する',async()=>{
  const editor=(await page.locator('.main-panel').boundingBox())!;
  await page.locator('#dock-tab-chart').dragTo(page.locator('.main-panel'),{targetPosition:{x:editor.width/2,y:20}});
  await expect(page.locator('.dock-slot.top #dock-tab-chart')).toBeVisible();await expect(page.locator('.dock-drop-zones')).toHaveCount(0);
  await page.locator('#dock-tab-table').dragTo(page.locator('.dock-slot.top #dock-tab-chart'));
  await expect(page.locator('.dock-slot.top #dock-tab-table')).toHaveAttribute('aria-selected','true');await expect(page.locator('.dock-slot.top #dock-tab-chart')).toHaveAttribute('aria-selected','false');
  await page.locator('[data-row="0"][data-col="1"]').click();await page.locator('[data-row="5"][data-col="3"]').click({modifiers:['Shift']});await page.locator('.grid-scroll').press('Control+t');await expect(page.locator('.saved-table')).toHaveCount(1);await page.locator('.saved-table header input').fill('保つテーブル');
  await page.getByRole('tab',{name:'グラフプレビュー',exact:true}).click();await expect(page.locator('.chart-area canvas')).toBeVisible();await page.getByLabel('グラフのカラーセット').selectOption('pastel');
  await page.getByRole('tab',{name:'テーブルプレビュー',exact:true}).click();await expect(page.locator('.saved-table header input')).toHaveValue('保つテーブル');await dropTab('table','right');await expect(page.locator('.dock-slot.right .saved-table')).toHaveCount(1);await expect(page.locator('.dock-slot.top .chart-area canvas')).toBeVisible();
  await page.locator('#dock-tab-chart').dragTo(page.locator('.dock-slot.right #dock-tab-table'));await expect(page.locator('.dock-slot.right #dock-tab-chart')).toHaveAttribute('aria-selected','true');await dropTab('chart','top');
  const tab=page.locator('#dock-tab-chart'),start=(await tab.boundingBox())!;await page.mouse.move(start.x+10,start.y+10);await page.mouse.down();await page.mouse.move(start.x+35,start.y+20);await expect(page.locator('.dock-drop-zones')).toBeVisible();await page.keyboard.press('Escape');await page.mouse.up();await expect(page.locator('.dock-drop-zones')).toHaveCount(0);await expect(page.locator('.dock-slot.top #dock-tab-chart')).toHaveAttribute('aria-selected','true');await page.screenshot({path:'release/docking-check.png'});
});
test('分析も結合でき、3D設定と内容を一括開閉・移動・別ウィンドウで保持する',async()=>{
  await page.getByLabel('左ペインを開閉').click();await page.getByRole('tab',{name:'多変量分析（ファイル全域）',exact:true}).click();await expect(page.locator('.analysis-pca')).toBeVisible();await page.getByLabel('分析の次元').selectOption('3');await page.getByLabel('3D分析の回転').evaluate((el:HTMLInputElement)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,'90');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});
  const before=await page.locator('.analysis-pca .analysis-plot circle').first().getAttribute('cx');await dropTab('multivariate','right');await expect(page.locator('.dock-slot.right .analysis-pca')).toBeVisible();await expect(page.getByLabel('分析の次元')).toHaveValue('3');await expect(page.getByLabel('3D分析の回転')).toHaveValue('90');
  await closeGroup('multivariate');await expect(page.locator('.dock-slot.right')).toHaveCount(0);await page.locator('#dock-tab-multivariate').click();await expect(page.getByLabel('分析の次元')).toHaveValue('3');expect(await page.locator('.analysis-pca .analysis-plot circle').first().getAttribute('cx')).toBe(before);
  const popupPromise=app.waitForEvent('window');await page.getByLabel('多変量分析（ファイル全域）を別ウィンドウにする').click();const popup=await popupPromise;await expect(popup.getByLabel('分析の次元')).toHaveValue('3');await popup.getByRole('tab',{name:'テーブルプレビュー',exact:true}).click();await expect(popup.locator('.saved-table header input')).toHaveValue('保つテーブル');await popup.getByLabel('メインウィンドウに戻す').click();
  await expect(page.locator('.dock-slot.right .saved-table header input')).toHaveValue('保つテーブル');await page.getByRole('tab',{name:'多変量分析（ファイル全域）',exact:true}).click();await dropTab('multivariate','bottom');await expect(page.locator('.dock-slot.bottom .analysis-pca')).toBeVisible();await expect(page.getByLabel('分析の次元')).toHaveValue('3');await readableText(page);
});
test('全6タブを結合して並べ替え、テーマと再起動後の配置・開閉状態を保つ',async()=>{
  for(const id of ['workspace','selection','multivariate','chart','table','merge']){const position=await page.evaluate(id=>window.csv.preferences().then(p=>Object.entries(p.dockLayout!.groups).find(([,tabs])=>tabs.includes(id as any))?.[0]),id);if(position!=='right'){const button=page.locator('#dock-tab-'+id);if(!await button.count())await page.locator('#dock-tab-'+id).click();await dropTab(id,'right');}}
  await expect(page.locator('.dock-slot.right [role=tab]')).toHaveCount(6);await page.getByRole('tab',{name:'グラフプレビュー',exact:true}).click();await expect(page.getByLabel('グラフのカラーセット')).toHaveValue('pastel');
  await page.getByRole('tab',{name:'グラフプレビュー',exact:true}).dragTo(page.getByRole('tab',{name:'ワークスペース',exact:true}));
  await page.getByRole('tab',{name:'ワークスペース',exact:true}).click();await page.getByLabel('左ペインを開閉').click();await expect(page.locator('#dock-tab-workspace')).toBeVisible();await page.getByLabel('左ペインを開閉').click();await expect(page.locator('.dock-slot.right #dock-tab-workspace')).toHaveAttribute('aria-selected','true');
  await page.getByRole('tab',{name:'ファイル結合',exact:true}).click();await page.getByLabel('テキストブロックを追加').click();await page.getByLabel('テキスト 1を直接編集').click();await page.getByLabel('ブロックの編集内容').fill('保存前の文章を保持');await dropTab('merge','left');await closeGroup('merge');await page.locator('#dock-tab-merge').click();await expect(page.getByLabel('ブロックの編集内容')).toHaveValue('保存前の文章を保持');await dropTab('merge','right');await page.getByRole('tab',{name:'グラフプレビュー',exact:true}).click();await page.getByRole('tab',{name:'ファイル結合',exact:true}).click();await expect(page.getByLabel('ブロックの編集内容')).toHaveValue('保存前の文章を保持');
  await page.getByLabel('テーマを切り替え').click();await readableText(page);await page.getByLabel('テーマを切り替え').click();await readableText(page);
  await page.getByRole('tab',{name:'テーブルプレビュー',exact:true}).click();await closeGroup('table');await expect.poll(()=>page.evaluate(()=>window.csv.preferences().then(p=>p.dockLayout!.open.includes('table')))).toBe(false);
  const saved=await page.evaluate(()=>window.csv.preferences().then(p=>p.dockLayout));await app.close();await launch();await expect(page.locator('.dock-slot.right')).toHaveCount(0);await expect(page.locator('.dock-rail.rail-right [role=tab]')).toHaveCount(6);expect(await page.evaluate(()=>window.csv.preferences().then(p=>p.dockLayout))).toEqual(saved);await page.locator('#dock-tab-table').click();await expect(page.locator('.dock-slot.right #dock-tab-table')).toHaveAttribute('aria-selected','true');await expect(page.locator('.dock-tabs')).toHaveCount(0);await expect(page.locator('.docking-editor .rail-right')).toHaveCount(0);
});

test('文字ボタンと共通アイコンを分離し、全方向で一括開閉と境界位置を保つ',async()=>{
  async function strip(position:string){const rail=page.locator('.dock-rail.rail-'+position);await expect(rail).toHaveCount(1);await expect(rail.locator('.boundary-toggle')).toHaveCount(1);await expect(rail.locator('[role=tab]')).toHaveCount(6);return rail;}
  for(const position of ['top','bottom','left','right']){
    // Move the whole test group by dragging each tab to the chosen edge.
    for(const id of ['workspace','selection','multivariate','chart','table','merge']){const current=await page.evaluate(id=>window.csv.preferences().then(p=>Object.entries(p.dockLayout!.groups).find(([,tabs])=>tabs.includes(id as any))?.[0]),id);if(current!==position)await dropTab(id,position);}
    const rail=await strip(position);await expect(page.locator('.dock-slot.'+position)).toBeVisible();await expect(page.locator('.dock-tabs')).toHaveCount(0);
    for(const id of ['chart','table','workspace']){await rail.locator('#dock-tab-'+id).click();await expect(rail.locator('#dock-tab-'+id)).toHaveAttribute('aria-selected','true');await expect(page.locator('.dock-slot.'+position)).toBeVisible();}
    const active=await rail.locator('[aria-selected=true]').getAttribute('id'),state=await page.evaluate(()=>window.csv.preferences().then(p=>p.dockSizes));
    await rail.locator('.boundary-toggle').click();await expect(page.locator('.dock-slot')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>window.csv.preferences().then(p=>p.dockLayout!.open.length))).toBe(0);
    await (await strip(position)).locator('.boundary-toggle').click();await expect(page.locator('.dock-slot.'+position)).toBeVisible();await expect(rail.locator('#'+active)).toHaveAttribute('aria-selected','true');await expect.poll(()=>page.evaluate(()=>window.csv.preferences().then(p=>p.dockLayout!.open.length))).toBe(6);
    await rail.locator('.boundary-toggle').click();await expect(page.locator('.dock-slot')).toHaveCount(0);await rail.locator('#dock-tab-table').click();await expect(page.locator('.dock-slot.'+position)).toBeVisible();await expect(rail.locator('#dock-tab-table')).toHaveAttribute('aria-selected','true');expect(await page.evaluate(()=>window.csv.preferences().then(p=>p.dockSizes))).toEqual(state);
    const panel=(await page.locator('.dock-slot.'+position).boundingBox())!,bounds=(await rail.boundingBox())!;const gap=position==='top'?panel.y+panel.height-bounds.y-bounds.height:position==='bottom'?bounds.y-panel.y:position==='left'?panel.x+panel.width-bounds.x-bounds.width:bounds.x-panel.x;expect(Math.abs(gap)).toBeLessThanOrEqual(1);
    for(const tab of await rail.locator('[role=tab],.boundary-toggle').all()){await tab.scrollIntoViewIfNeeded();const box=(await tab.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(bounds.x-1);expect(box.y).toBeGreaterThanOrEqual(bounds.y-1);expect(box.x+box.width).toBeLessThanOrEqual(bounds.x+bounds.width+1);expect(box.y+box.height).toBeLessThanOrEqual(bounds.y+bounds.height+1);}
    await readableText(page);
  }
  await page.screenshot({path:'release/boundary-tabs-v1.5.3-light.png'});await page.getByLabel('テーマを切り替え').click();await readableText(page);await page.screenshot({path:'release/boundary-tabs-v1.5.3-dark.png'});
});
