'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const iconv=require('iconv-lite');
const {CsvFile,parseRecord,compareDecimal}=require('../electron/engine.cjs');const {tableText}=require('../electron/tables.cjs');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'csvlens-tests-'));
function fixture(name,content,options={}){const target=path.join(temp,name);fs.writeFileSync(target,Buffer.isBuffer(content)?content:Buffer.from(content));return new CsvFile(target,options);}
function hash(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');}
test('引用符、改行、空セル、先頭ゼロ、長い整数は文字列のまま保持',()=>{const f=fixture('quoted.csv','ID,メモ,値\r\n00012,"1行目\r\n2行目",12345678901234567890\r\n00013,"a,""b""",\r\n');assert.equal(f.count,2);assert.deepEqual(f.page(0).rows[0].cells,['00012','1行目\r\n2行目','12345678901234567890']);assert.deepEqual(f.row(2),['00013','a,"b"','']);f.close();});
test('CSV以外の引用符を含むTXTは行単位でそのまま表示',()=>{const f=fixture('literal.txt','"閉じない引用符\n次の行,そのまま\n');assert.equal(f.count,2);assert.deepEqual(f.row(0),['"閉じない引用符']);assert.deepEqual(f.row(1),['次の行,そのまま']);assert.equal(f.kind,'text');f.close();});
for(const encoding of ['utf8','cp932','euc-jp','utf16le','utf16be','utf32le','utf32be'])test('文字コード: '+encoding,()=>{const text='名前|値\r\n日本語|00001\r\n表|2\r\n';const bom=encoding.startsWith('utf')&&encoding!=='utf8'?'\ufeff':'';const f=fixture('encoding-'+encoding+'.csv',iconv.encode(bom+text,encoding),{encoding,delimiter:'|'});assert.deepEqual(f.row(1),['日本語','00001']);assert.deepEqual(f.row(2),['表','2']);f.close();});
test('CP932のパイプと同じ後続バイトを区切りと誤認しない',()=>{const chars=[];for(let cp=0x4e00;cp<=0x9fff;cp++){const c=String.fromCharCode(cp),b=iconv.encode(c,'cp932');if(b.length===2&&b[1]===0x7c){chars.push(c);break;}}assert.ok(chars.length);const f=fixture('cp-pipe.csv',iconv.encode('h|v\n'+chars[0]+'|3\n','cp932'),{encoding:'cp932',delimiter:'|'});assert.equal(f.columns,2);assert.deepEqual(f.row(1),[chars[0],'3']);f.close();});
test('引用符とCRLFのブロック境界',()=>{const prefix='x'.repeat(1024*1024-3);const f=fixture('boundary.csv','h\n"'+prefix+'"\r\nlast\r\n');assert.equal(f.count,2);assert.equal(f.row(1)[0],prefix);assert.equal(f.row(2)[0],'last');f.close();});
test('空ファイル・空行・末尾の空セル・不揃いな列',()=>{const empty=fixture('empty.csv','');assert.equal(empty.count,0);empty.close();const f=fixture('ragged.csv','a,b\n\n1,2,\n');assert.equal(f.count,2);assert.equal(f.columns,3);assert.ok(f.warnings.length);assert.deepEqual(f.row(1),['']);assert.deepEqual(f.row(2),['1','2','']);f.close();});
test('数値順の桁精度、複数条件、条件解除、ソート失敗のロールバック',()=>{const f=fixture('sort.csv','name,value\nB,12345678901234567891\nA,12345678901234567890\nC,-2.1\nD,word\n');f.configure({filters:[{column:1,mode:'gt',value:'0'}],sorts:[{column:1,mode:'numeric',direction:'asc'}]});assert.equal(f.count,2);assert.equal(f.page(0).rows[0].cells[0],'A');assert.throws(()=>f.configure({filters:[{column:0,mode:'regex',value:'['}]}));assert.equal(f.count,2);f.configure({filters:[],sorts:[]});assert.equal(f.count,4);f.close();assert.equal(compareDecimal('9007199254740993','9007199254740992'),1);assert.equal(compareDecimal('-0.10','-.1'),0);});
test('検索は現在の表示範囲で循環し、CSV形式のコピーで改行を保持',()=>{const f=fixture('find.csv','h1,h2\nfirst,"x\ny"\nlast,z\n');assert.deepEqual(f.find({value:'first'},{row:1,column:1}),{row:0,column:0});assert.equal(f.copy({row0:0,row1:0,col0:0,col1:1},','),'first,"x\ny"');f.close();});
test('元ファイルのSHA-256と更新日時は閲覧、検索、ソート、エクスポート後も同じ',()=>{const f=fixture('immutable.csv','h,v\r\nA,00012\r\nB,9999999999999999999\r\n');const original=hash(f.path),mtime=fs.statSync(f.path).mtimeMs;f.configure({sorts:[{column:1,mode:'numeric',direction:'desc'}]});f.find({value:'A'});f.exportFile({path:path.join(temp,'export.md'),format:'md',scope:'view'});assert.equal(hash(f.path),original);assert.equal(fs.statSync(f.path).mtimeMs,mtime);assert.throws(()=>f.exportFile({path:f.path,format:'csv'}));const hardlink=path.join(temp,'hardlink.csv');fs.linkSync(f.path,hardlink);assert.throws(()=>f.exportFile({path:hardlink,format:'csv'}));f.close();});
test('選択範囲のCSV/Markdown出力と飛び飛び選択の空欄',()=>{const f=fixture('ranges.csv','label,A,B,C\nJan,10,20,30\nFeb,11,21,31\nMar,12,22,32\n');const ranges=[{row0:0,row1:1,col0:1,col1:1},{row0:1,row1:2,col0:3,col1:3}];const table=f.selectionTable(ranges);assert.deepEqual(table.headers,['A','C']);assert.deepEqual(table.rows,[['10',''],['11','31'],['','32']]);const inferred=f.selectionTable(ranges,10000,false,true);assert.deepEqual(inferred.rows,[['Jan','10',''],['Feb','11','31'],['Mar','','32']]);assert.ok(inferred.inferred.length);const out=path.join(temp,'selection.md');f.exportFile({path:out,format:'md',scope:'selection',selections:ranges});assert.match(fs.readFileSync(out,'utf8'),/\| A \| C \|/);f.close();});
test('見出しがない表示でも先頭行方向に走査して列名を推定',()=>{const f=fixture('inference.csv','Category,売上,利益\nJan,10,2\nFeb,12,3\n',{headerRows:0});const table=f.selectionTable({row0:1,row1:2,col0:1,col1:2},1000,false,true);assert.deepEqual(table.headers,['行ラベル（推定）','売上','利益']);assert.deepEqual(table.rows[0],['Jan','10','2']);f.close();});
test('Markdownの最初の表をCSVに変換、TXT/MDのソース出力',()=>{const source='# 題名\n\n| 名前 | 値 |\n| --- | --- |\n| **A** | 00012 |\n';const f=fixture('native.md',source);const csv=path.join(temp,'markdown.csv');f.exportFile({path:csv,format:'csv',markdownTable:true});assert.equal(fs.readFileSync(csv,'utf8'),'名前,値\r\nA,00012\r\n');const txt=path.join(temp,'markdown.txt');f.exportFile({path:txt,format:'txt'});assert.equal(fs.readFileSync(txt,'utf8'),source);f.close();});
test('外部更新を検知し、古い索引の使用を拒否',()=>{const f=fixture('modified.csv','h\na\n');fs.writeFileSync(f.path,'h\na\nb\n');f.lastCheck=0;assert.throws(()=>f.page(0),/変更/);f.close();});
test('大容量の読み込みは仮想ページだけを返す',()=>{const target=path.join(temp,'large.csv');const fd=fs.openSync(target,'w');fs.writeSync(fd,'id,value\n');for(let n=0;n<100;n++)fs.writeSync(fd,Array.from({length:1000},(_,i)=>`${n*1000+i},00012\n`).join(''));fs.closeSync(fd);const f=new CsvFile(target);assert.equal(f.count,100000);assert.equal(f.page(99990,10).rows.at(-1).cells[0],'99999');assert.ok(f.starts instanceof Float64Array);f.close();});
test('共有用テーブルのMarkdownとCSVは元の文字列を保持',()=>{const table={headers:['名前','内容'],rows:[['0001','a,b'],['=1+1','改行\nあり']]};assert.equal(tableText(table,'csv'),'名前,内容\r\n0001,"a,b"\r\n=1+1,"改行\nあり"\r\n');assert.match(tableText(table,'md'),/改行<br>あり/);});
