import {test,expect,type ElectronApplication,type Page} from '@playwright/test';
import {launchWithoutTutorial} from './electron-profile';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const root=process.cwd(),profile=fs.mkdtempSync(path.join(os.tmpdir(),'csv-responsive-dock-')),file=path.join(root,'samples/sales.csv');let app:ElectronApplication,page:Page;const errors:string[]=[];
const prefs={tutorialStatus:'skipped',dockLayout:{groups:{left:['workspace','multivariate'],right:['merge'],top:['selection'],bottom:['chart','table']},active:{left:'workspace',right:'merge',top:'selection',bottom:'chart'},open:['workspace','multivariate','merge','selection','chart','table']},dockSizes:{left:{width:240,height:250},right:{width:310,height:260},top:{height:180,width:700},bottom:{height:240,width:710}}};
fs.writeFileSync(path.join(profile,'preferences.json'),JSON.stringify(prefs));
test.beforeAll(async()=>{app=await launchWithoutTutorial({args:['--no-sandbox','--user-data-dir='+profile,'.',file],cwd:root,env:{...process.env}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await expect(page.locator('[data-row="0"][data-col="1"]')).toHaveText('1200000',{timeout:30000});});test.afterAll(async()=>{await app.close();expect(errors).toEqual([]);});
async function dimensions(){return page.evaluate(()=>{const rect=(s:string)=>{const r=document.querySelector(s)!.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};return {root:rect('.docking-layout'),center:rect('.docking-editor'),left:rect('.dock-slot.left'),right:rect('.dock-slot.right'),top:rect('.dock-slot.top'),bottom:rect('.dock-slot.bottom')};});}
async function size(width:number,height:number){
  // Windows hidden-titlebar frame insets may add pixels when the native minimum
  // clamps setContentSize. Compare the tiled layout with the actual client area.
  await app.evaluate(async({BrowserWindow},{width,height})=>{const win=BrowserWindow.getAllWindows()[0];win.setContentSize(width,height);return win.webContents.executeJavaScript('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve({width:innerWidth,height:innerHeight}))))');},{width,height});
  await expect.poll(()=>page.evaluate(()=>Math.max(0,1000-innerWidth,714-innerHeight))).toBe(0);const viewport=await page.evaluate(()=>({width:innerWidth,height:innerHeight}));
  expect(Math.abs(viewport.width-width)).toBeLessThanOrEqual(16);expect(Math.abs(viewport.height-Math.max(height,714))).toBeLessThanOrEqual(16);expect(viewport.width).toBeGreaterThanOrEqual(1000);expect(viewport.height).toBeGreaterThanOrEqual(714);
  await expect.poll(async()=>{const d=await dimensions();return Math.max(Math.abs(d.root.w-viewport.width),Math.abs(d.root.h-(viewport.height-34)));}).toBeLessThan(1);
}
async function tiled(){await expect.poll(async()=>{const d=await dimensions();return Math.max(Math.abs(d.left.x+d.left.w-d.center.x),Math.abs(d.center.x+d.center.w-d.right.x),Math.abs(d.top.y+d.top.h-d.center.y),Math.abs(d.center.y+d.center.h-d.bottom.y),Math.abs(d.left.h-d.root.h),Math.abs(d.right.h-d.root.h),Math.abs(d.top.w-d.center.w),Math.abs(d.bottom.w-d.center.w),Math.abs(d.bottom.y+d.bottom.h-d.root.y-d.root.h),Math.abs(d.right.x+d.right.w-d.root.x-d.root.w));}).toBeLessThan(1);}
test('旧版の独立寸法を移行し、拡大・縮小・最小サイズでも隙間と重なりなく埋める',async()=>{
  await tiled();const ratios=await page.evaluate(()=>window.csv.preferences().then(p=>p.dockRatios));for(const [w,h] of [[1800,1100],[1200,760],[1000,560],[1600,1000]]){await size(w,h);await tiled();const d=await dimensions();expect(d.left.w).toBeGreaterThanOrEqual(189.9);expect(d.right.w).toBeGreaterThanOrEqual(279.9);expect(d.top.h).toBeGreaterThanOrEqual(179.9);expect(d.bottom.h).toBeGreaterThanOrEqual(179.9);expect(d.center.w).toBeGreaterThanOrEqual(359.9);expect(d.center.h).toBeGreaterThanOrEqual(319.9);expect(await page.evaluate(()=>window.csv.preferences().then(p=>p.dockRatios))).toEqual(ratios);const cell=await page.locator('[data-row="0"][data-col="1"]').boundingBox(),grid=await page.locator('.grid-scroll').boundingBox();expect(cell!.y+cell!.height).toBeLessThanOrEqual(grid!.y+grid!.height);await page.screenshot({path:'release/resize-v1.5.5-'+w+'x'+h+'.png'});}
  const d=await dimensions();expect(d.right.w/d.center.w).toBeCloseTo(ratios!.right!,2);expect(d.bottom.h/d.center.h).toBeCloseTo(ratios!.bottom!,2);await page.getByRole('button',{name:'sales.csvを閉じる',exact:true}).click();await expect(page.locator('.welcome h1')).toContainText('CSV nyaan Viewer');await size(1000,560);await tiled();expect(await page.locator('.welcome').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);await page.locator('.welcome').getByRole('button',{name:/ファイルを開く/}).scrollIntoViewIfNeeded();await page.screenshot({path:'release/resize-v1.5.5-welcome.png'});await size(1600,1000);await tiled();
});
test('境界のドラッグとキー操作が共有トラックを調整し、比率保存・閉じて再展開・復元でも隙間を作らない',async()=>{
  const before=await dimensions(),bottom=page.locator('.dock-slot.bottom'),grip=page.locator('.dock-slot.right').getByLabel('右ペインとデータの境界',{exact:true}),box=(await grip.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2-70,box.y+box.height/2,{steps:10});await page.mouse.up();await tiled();const changed=await dimensions();expect(changed.center.w).toBeCloseTo(before.center.w-70,0);expect(changed.right.w).toBeCloseTo(before.right.w+70,0);expect(changed.top.w).toBeCloseTo(changed.bottom.w,0);
  const saved=await page.evaluate(()=>window.csv.preferences().then(p=>p.dockRatios));await size(1800,1100);await tiled();const bigger=await dimensions();expect(bigger.right.w/bigger.center.w).toBeCloseTo(saved!.right!,2);await page.locator('.rail-right .boundary-toggle').click();await expect(page.locator('.dock-slot.right')).toHaveCount(0);await page.locator('#dock-tab-merge').click();await tiled();await bottom.getByLabel('下ペインとデータの境界',{exact:true}).focus();await bottom.getByLabel('下ペインとデータの境界',{exact:true}).press('ArrowUp');await tiled();
});
