'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),ts=require('typescript'),vm=require('node:vm');
const {CsvFile,compareDecimal}=require('../electron/engine.cjs'),{WorkbookFile}=require('../electron/workbook.cjs'),stats=require('../electron/statistics.cjs'),online=require('../electron/online.cjs'),XLSX=require('@e965/xlsx');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'csv-nyaan-revision-')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function read(file,modules={}){const scope={exports:{},structuredClone,require:name=>modules[name]??require(name)};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,scope);return scope.exports;}
const plain=v=>JSON.parse(JSON.stringify(v)),data=read('src/data.ts'),catalog=read('src/chart-catalog.ts'),recommend=read('src/chart-recommendation.ts',{'./data':data}),selection=read('src/grid-selection.ts');
for(const type of ['xlsx','xls','xlsb','ods'])test('Excel '+type+' は複数シート・書式付き値・式のキャッシュ・長い文字列をネイティブに保持',()=>{const workbook=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet([['ID','数値','式'],['000001',1234,'=1+1'],['12345678901234567890',2,'文字列']]);sheet.B2.z='#,##0';sheet.C3={t:'n',v:6,f:'2*3'};XLSX.utils.book_append_sheet(workbook,sheet,'Data');XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([['X','Y'],[1,2],[3,4]]),'Second');const p=path.join(root,'native.'+type);XLSX.writeFile(workbook,p,{bookType:type});const before=hash(p),file=new WorkbookFile(p);assert.deepEqual(file.row(1),['000001',type==='ods'?'1234':'1,234','=1+1']);assert.equal(file.row(2)[0],'12345678901234567890');assert.equal(file.row(2)[2],'6');assert.deepEqual(file.metadata().sheets,['Data','Second']);file.configure({sorts:[{column:1,direction:'desc',mode:'numeric'}]});file.configure({sheet:'Second'});assert.equal(file.count,2);assert.equal(file.page(0,1).rows[0].cells[1],'2');file.exportFile({path:path.join(root,type+'.md'),format:'md',scope:'all',encoding:'source'});assert.equal(hash(p),before);file.close();});
test('行の表示削除、復元、横方向ソートと表示列のエクスポート',()=>{const p=path.join(root,'projection.csv');fs.writeFileSync(p,'A,B,C\n10,0002,3\n5,4,6\n7,8,9\n');const file=new CsvFile(p);file.excludeSelection([{row0:1,row1:1,col0:0,col1:0}]);assert.equal(file.count,2);assert.deepEqual(file.sortColumns(0,'asc',[0,1,2]),[1,2,0]);const table=file.selectionTable({row0:0,row1:1,col0:0,col1:2},100,false,false,[2,0]);assert.deepEqual(table.headers,['C','A']);assert.deepEqual(table.rows,[['3','10'],['9','7']]);file.exportFile({path:path.join(root,'projection-export.csv'),format:'csv',scope:'view',columns:[2,0]});assert.equal(fs.readFileSync(path.join(root,'projection-export.csv'),'utf8'),'C,A\r\n3,10\r\n9,7\r\n');file.configure({excludedRows:[]});assert.equal(file.count,3);file.close();});
test('Ctrl矢印は連続範囲の端と次の非空セルを辿り、Shiftは最後の追加範囲だけを伸ばす',()=>{assert.equal(selection.jumpIndex(['1','2','','','5','6'],0,1),1);assert.equal(selection.jumpIndex(['1','2','','','5','6'],1,1),4);const one=selection.moveSelection(null,[],0,0,false,false),two=selection.moveSelection(one.selection,one.ranges,3,3,false,true),three=plain(selection.moveSelection(two.selection,two.ranges,5,4,true,false));assert.equal(three.ranges.length,2);assert.deepEqual(three.ranges[0],{row0:0,row1:0,col0:0,col1:0});assert.deepEqual(three.ranges[1],{row0:3,row1:5,col0:3,col1:4});});
test('分析は平均・欠損・等差則・回帰・順位相関・PCAを既知の値で検証',()=>{const result=stats.analyze({headers:['X','Y','Missing'],rows:Array.from({length:20},(_,i)=>[String(i+1),String((i+1)*3+2),i%2?'':String(i)])},true);assert.equal(result.columnSummaries[0].stats.mean,10.5);assert.equal(result.columnSummaries[0].stats.rule,'等差系列');assert.equal(result.columnSummaries[2].stats.missing,10);const pair=result.pairs.find(p=>p.x==='X'&&p.y==='Y');assert.ok(Math.abs(pair.r-1)<1e-12);assert.equal(pair.slope,3);assert.equal(pair.intercept,2);assert.ok(result.pca.explained[0]>.99);assert.equal(result.pca.completeRows,10);const tie=stats.ranks([1,1,2]);assert.deepEqual(tie,[1.5,1.5,3]);});
test('全域分析はフィルターを無視し、先頭と末尾を含む等間隔標本に制限',()=>{const p=path.join(root,'sample.csv');fs.writeFileSync(p,'X,Y\n'+Array.from({length:6000},(_,i)=>i+','+(i*2)).join('\n'));const file=new CsvFile(p);file.configure({filters:[{column:0,mode:'gt',value:'5998'}]});assert.equal(file.count,1);const sample=file.analysisSample([],true);assert.equal(sample.populationRows,6000);assert.equal(sample.rows.length,5000);assert.deepEqual(sample.rows[0],['0','0']);assert.deepEqual(sample.rows.at(-1),['5999','11998']);assert.equal(sample.truncated,true);file.close();});
test('グラフの推薦は時系列・座標・分布・割合・株価を区別',()=>{for(const [table,type]of [[{headers:['月','額'],rows:[['1月','3'],['2月','4'],['3月','5']]},'line'],[{headers:['X','Y'],rows:[['1','2'],['2','4'],['3','6']]},'scatter'],[{headers:['値'],rows:Array.from({length:20},(_,i)=>[String(i)])},'histogram'],[{headers:['分類','割合'],rows:[['A','20'],['B','80']]},'doughnut'],[{headers:['日付','高値','安値','終値'],rows:[['Jan','3','1','2']]},'stock-hlc']])assert.equal(recommend.recommendChart(table).type,type);assert.ok(catalog.CHART_KINDS.length>=75);assert.equal(new Set(catalog.CHART_KINDS.map(k=>k.id)).size,catalog.CHART_KINDS.length);assert.equal(data.numeric('1,234.50'),1234.5);assert.equal(data.numeric('1,2'),null);});
function response(body,status=200){return new Response(Buffer.isBuffer(body)?body:JSON.stringify(body),{status});}
test('公開Google URLはExcelとして取得し、元URLとデータを保持',async()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['A'],['0001']]),'Data');const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),requests=[];const result=await online.openOnline('https://docs.google.com/spreadsheets/d/test_id/edit#gid=4',{fetch:async url=>{requests.push(url);return response(bytes);},accessToken:()=>{throw Error('unexpected');},cacheDir:root});assert.match(requests[0],/export\?format=xlsx/);assert.equal(result.sourceUrl,'https://docs.google.com/spreadsheets/d/test_id/edit#gid=4');assert.equal(hash(result.path),crypto.createHash('sha256').update(bytes).digest('hex'));});
test('非公開GoogleはSheets APIの書式付き値を読み取り、書き込みを行わない',async()=>{const requests=[];const result=await online.openOnline('https://docs.google.com/spreadsheets/d/private/edit#gid=2',{fetch:async(url,options)=>{requests.push({url,options});if(url.includes('/export'))return response({},403);if(url.includes('batchGet'))return response({valueRanges:[{values:[['ID','Value'],['00001','1,234']]}]});return response({properties:{title:'Private'},sheets:[{properties:{title:'Sheet A',sheetId:2,gridProperties:{rowCount:10,columnCount:2}}}]});},accessToken:async()=> 'test',cacheDir:root});assert.equal(requests.length,3);assert.equal(requests[1].options.headers.Authorization,'Bearer test');assert.ok(requests.every(r=>!r.options.method));const file=new WorkbookFile(result.path,result.options);assert.equal(file.sheet,'Sheet A');assert.deepEqual(file.row(1),['00001','1,234']);file.close();});
test('Microsoft共有URLはGraph経由で取得し、署名付き配布先へBearerを送らない',async()=>{const requests=[],zip=Buffer.from('504b03040102','hex');const result=await online.openOnline('https://1drv.ms/x/s/example',{fetch:async(url,options)=>{requests.push({url,options});if(url.includes('graph.microsoft.com'))return response({name:'Book.xlsx','@microsoft.graph.downloadUrl':'https://download.example/book'});if(url.includes('download.example'))return response(zip);return response({},403);},accessToken:async()=> 'test',cacheDir:root});assert.match(requests[2].url,/\/shares\/u!/);assert.equal(requests[2].options.headers.Authorization,'Bearer test');assert.equal(requests[3].options.headers,undefined);assert.equal(path.extname(result.path),'.xlsx');});
test('オンラインURLの危険なスキーム、認証埋め込み、HTML応答は拒否',async()=>{assert.throws(()=>online.parseOnline('http://example.com/file.xlsx'),/HTTPS/);assert.throws(()=>online.parseOnline('https://user:pass@example.com/file.xlsx'),/HTTPS/);assert.throws(()=>online.extension(Buffer.from('<html>login</html>')),/Excel/);await assert.rejects(online.openOnline('https://docs.google.com/spreadsheets/d/private/edit',{fetch:async()=>response({},403),accessToken:async()=>{throw Error('no');},cacheDir:root}),/Googleにログイン/);});

const echarts=require('echarts'),settings=read('src/chart-settings.ts',{'./data':data}),options=read('src/chart-options.ts',{'./data':data,'./chart-catalog':catalog});
test('全グラフタイプはCPU/SVGでも描画でき、散布図・株価・ヒストグラム・3Dの値を正しく割り当てる',()=>{const table={headers:['日付','X','Y','Size','Volume','Open','High','Low','Close'],rows:Array.from({length:8},(_,i)=>['2026-10-'+String(i+1).padStart(2,'0'),String(i),String(i*i),String(i+1),String(100+i),String(10+i),String(13+i),String(8+i),String(11+i)])};for(const kind of catalog.CHART_KINDS){const option=options.buildChartOption(table,kind.id,settings.defaultChartSettings(),'light');const chart=echarts.init(null,null,{renderer:'svg',ssr:true,width:800,height:400});try{chart.setOption(option);assert.match(chart.renderToSVGString(),/<svg/);}finally{chart.dispose();}}const scatter=options.buildChartOption(table,'scatter',settings.defaultChartSettings(),'light');assert.equal(scatter.series[0].data[3][0],3);assert.equal(scatter.series[0].data[3][1],9);const stock=options.buildChartOption(table,'stock-volume-ohlc',settings.defaultChartSettings(),'light');assert.deepEqual(plain(stock.series[0].data[0]),[10,11,8,13]);assert.equal(stock.series[1].data[0],100);const depth=options.buildChartOption(table,'column-3d',settings.defaultChartSettings(),'light');assert.deepEqual(plain(depth.series[0].encode),{x:0,y:[1,2]});const bins=options.buildChartOption({headers:['V'],rows:[['1'],['1'],['2'],['2'],['3']]},'histogram',settings.defaultChartSettings(),'light');assert.equal(bins.series[0].data.reduce((s,n)=>s+n,0),5);});

test('カンマ・通貨・指数表記は精度を落とさず並べ替え、表示値を保持して数値フィルターを適用',()=>{assert.equal(compareDecimal('1,234','98'),1);assert.equal(compareDecimal('¥1,234.50','1234.5'),0);assert.equal(compareDecimal('1e1000000','9e999999'),1);assert.equal(compareDecimal('0','1e-10000'),-1);assert.equal(compareDecimal('-0','0.00'),0);assert.equal(compareDecimal('1.2e3','1200'),0);assert.equal(compareDecimal('1,2','12'),null);assert.equal(compareDecimal('1e20','100000000000000000001'),-1);const p=path.join(root,'formatted.csv');fs.writeFileSync(p,'Value\n"1,234"\n98\n1e4\n');const file=new CsvFile(p);file.configure({sorts:[{column:0,direction:'asc',mode:'numeric'}],filters:[{column:0,mode:'gt',value:'100'}]});assert.deepEqual(file.page(0,2).rows.map(r=>r.cells[0]),['1,234','1e4']);file.close();});
