import {test,expect,_electron as electron,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {readableText} from './ui-contrast';
const root=process.cwd(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'s-browser-ui-')),profile=path.join(dir,'profile'),file=path.join(root,'samples/sales.csv'),original=fs.readFileSync(file);
let app:ElectronApplication,page:Page;const errors:string[]=[];
test.describe.configure({mode:'serial'});
async function launch(){app=await electron.launch({args:['--no-sandbox','--user-data-dir='+profile,'.',file],cwd:root,env:{...process.env,CSV_LENS_TEST:'1'}});page=await app.firstWindow();page.on('pageerror',error=>errors.push(error.message));await expect(page.locator('[data-row="0"][data-col="1"]')).toHaveText('1200000',{timeout:30000});await app.evaluate(({session,shell,dialog,nativeImage})=>{
  (globalThis as any).sNativeUrls=[];(globalThis as any).sDialogLog=[];(globalThis as any).sDialogResponse=0;shell.openExternal=async url=>{(globalThis as any).sNativeUrls.push(url);};dialog.showMessageBox=async(_window,options)=>{(globalThis as any).sDialogLog.push(options.title);return {response:(globalThis as any).sDialogResponse,checkboxChecked:false};};
  const bitmap=Buffer.alloc(24*24*4);for(let i=0;i<bitmap.length;i+=4){bitmap[i]=210;bitmap[i+1]=150;bitmap[i+2]=40;bitmap[i+3]=255;}const ownImage=nativeImage.createFromBitmap(bitmap,{width:24,height:24}).toPNG(),ownURL='data:image/png;base64,'+ownImage.toString('base64');for(let i=0;i<bitmap.length;i+=4){bitmap[i]=20;bitmap[i+1]=20;bitmap[i+2]=220;}const otherURL=nativeImage.createFromBitmap(bitmap,{width:24,height:24}).toDataURL();
  session.defaultSession.protocol.handle('https',request=>request.url.startsWith('https://www.googleapis.com/drive/v3/about')?new Response(JSON.stringify({user:{displayName:'API本人',photoLink:'https://lh3.googleusercontent.com/a/fixture'}}),{headers:{'Content-Type':'application/json'}}):request.url.startsWith('https://lh3.googleusercontent.com/')?new Response(ownImage,{headers:{'Content-Type':'image/png'}}):new Response('unavailable',{status:403}));
  const controls:Record<string,string>={google:'aria-label="Google Account: 本人"',microsoft:'data-tid="me-control"',github:'data-testid="user-menu-button"',slack:'data-qa="user-button"',discord:'data-testid="account-avatar"'};
  for(const id of ['google','microsoft','github','slack','discord'])session.fromPartition('persist:csv-nyaan-s-'+id).protocol.handle('https',()=>new Response(`<!doctype html><html lang="ja"><body><h1>架空サービス ${id}</h1><img id="other-user-avatar" alt="他人の画像" width="24" height="24" src="${otherURL}"><button id="own-account" ${controls[id]} style="display:none"><img id="own-avatar" alt="本人の画像" width="24" height="24" src="${ownURL}"></button><button id="fixture-login">テストログイン</button><input id="fixture-upload" type="file"><button id="fixture-popup">ログインウィンドウ</button><pre id="fixture-result"></pre><script>document.querySelector('#fixture-login').onclick=()=>{localStorage.setItem('fixture-login','${id}-signed-in');document.cookie='fixture_session=${id};Path=/;Secure;SameSite=Lax;Max-Age=3600';document.querySelector('h1').textContent='ログイン済み ${id}';document.querySelector('#own-account').style.display='inline-block';};if(localStorage.getItem('fixture-login'))document.querySelector('#own-account').style.display='inline-block';document.querySelector('#fixture-popup').onclick=()=>window.open(location.origin+'/popup');document.querySelector('#fixture-upload').onchange=async e=>{const f=e.target.files[0];if(f){window.fixtureUpload={name:f.name,text:await f.text(),bytes:Array.from(new Uint8Array(await f.arrayBuffer()))};document.querySelector('#fixture-result').textContent=f.name;}};</script></body></html>`,{headers:{'Content-Type':'text/html; charset=utf-8'}}));
});}
test.beforeAll(launch);test.afterAll(async()=>{await app.close();expect(errors).toEqual([]);expect(fs.readFileSync(file)).toEqual(original);});
async function chromeAfter(action:()=>Promise<unknown>){const before=new Set(app.context().pages());await action();await expect.poll(()=>app.context().pages().some(p=>!before.has(p)&&p.url().includes('s-browser.html'))).toBe(true);const chrome=app.context().pages().find(p=>!before.has(p)&&p.url().includes('s-browser.html'))!;await expect(chrome.locator('#confirm')).toBeVisible();return chrome;}
async function remote(chrome:Page){await expect(chrome.locator('#address')).toHaveValue(/^https:/);const url=await chrome.locator('#address').inputValue();await expect.poll(()=>app.context().pages().some(p=>p.url()===url)).toBe(true);return app.context().pages().find(p=>p.url()===url)!;}
async function closeBrowsers(){await app.evaluate(({BrowserWindow})=>{for(const win of BrowserWindow.getAllWindows())if(win.webContents.getURL().includes('s-browser.html'))win.close();});}
async function connect(id:string,label:string){await page.getByRole('button',{name:'Sアカウント接続',exact:true}).click();await page.getByLabel('Sアカウント接続先').selectOption(id);const chrome=await chromeAfter(()=>page.getByRole('button',{name:'内部ブラウザでログイン',exact:true}).click());await expect(chrome.locator('#confirm')).toBeEnabled();const site=await remote(chrome),storedLogin=await site.evaluate(()=>localStorage.getItem('fixture-login'));await site.locator('#fixture-login').click();await chrome.getByLabel('Sアカウントの表示名').fill(label);await chrome.getByRole('button',{name:'このログインを使用',exact:true}).click();await expect(chrome.locator('#account-state')).toContainText(label);await page.getByLabel('Sアカウント接続を閉じる').click();return {chrome,site,storedLogin};}
async function ownAvatar(provider:string){
  const names:Record<string,string>={google:'Google',microsoft:'Microsoft',github:'GitHub',slack:'Slack',discord:'Discord'},image=page.getByLabel(names[provider]+'のアカウントを確認').locator('img');await expect(image).toBeVisible();await expect.poll(()=>image.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth===64)).toBe(true);
  const source=await image.getAttribute('src');expect(source).toMatch(/^data:image\/png;base64,/);const pixel=await app.evaluate(({nativeImage},src)=>{const image=nativeImage.createFromDataURL(src!),b=image.toBitmap(),at=(32*64+32)*4;return [b[at+2],b[at+1],b[at]];},source);expect(pixel).toEqual([40,150,210]);
}
async function ribbonFits(count:number){
  await expect(page.locator('.account-icon')).toHaveCount(count);
  for(const width of [1000,1440]){await app.evaluate(({BrowserWindow},width)=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('dist/index.html'))!.setContentSize(width,940),width);
    const state=await page.locator('.account-icons').evaluate(el=>{const style=getComputedStyle(el),box=el.getBoundingClientRect();return {client:[el.clientWidth,el.clientHeight],scroll:[el.scrollWidth,el.scrollHeight],overflow:[style.overflowX,style.overflowY],fit:Array.from(el.children).every(child=>{const b=child.getBoundingClientRect();return b.left>=box.left&&b.right<=box.right&&b.top>=box.top&&b.bottom<=box.bottom;})};});expect(state.scroll).toEqual(state.client);expect(state.overflow.some(value=>['auto','scroll'].includes(value))).toBe(false);expect(state.fit).toBe(true);
    if(count){const last=(await page.locator('.account-icon').last().boundingBox())!,theme=(await page.getByLabel('テーマを切り替え').boundingBox())!;expect(last.x+last.width).toBeLessThanOrEqual(theme.x);}expect((await page.locator('.online-bar').boundingBox())!.width).toBeGreaterThanOrEqual(100);await expect(page.locator('.compact-titlebar')).toHaveCSS('height','34px');
  }
}
test('既存入口を保持し、TeamsのWeb・アプリ、隔離された内部ブラウザとログイン登録を確認する',async()=>{
  await ribbonFits(0);for(const label of ['共有','接続','S共有','Sアカウント接続'])await expect(page.locator('.menubar').getByRole('button',{name:label,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Sアカウント接続',exact:true}).click();await page.getByLabel('Sアカウント接続先').selectOption('teams');await page.getByRole('button',{name:'Teamsアプリを開く',exact:true}).click();expect(await app.evaluate(()=>(globalThis as any).sNativeUrls)).toEqual(['msteams://teams.microsoft.com/']);
  const chrome=await chromeAfter(()=>page.getByRole('button',{name:'内部ブラウザでログイン',exact:true}).click());await expect(chrome.locator('#confirm')).toBeEnabled();const site=await remote(chrome);expect(await site.evaluate(()=>({csv:typeof (window as any).csv,browser:typeof (window as any).sBrowser,node:typeof (window as any).require}))).toEqual({csv:'undefined',browser:'undefined',node:'undefined'});
  expect(await app.evaluate(({webContents})=>{const view=webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://teams.microsoft.com/'))!,p=view.getLastWebPreferences()!;return {sandbox:p.sandbox,node:p.nodeIntegration,isolation:p.contextIsolation,security:p.webSecurity};})).toEqual({sandbox:true,node:false,isolation:true,security:true});
  expect(await app.evaluate(({webContents,ipcMain})=>{const view=webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://teams.microsoft.com/'))!;try{(ipcMain as any)._invokeHandlers.get('csv:sAccounts')({sender:view,senderFrame:view.mainFrame});return 'allowed';}catch(e){return String(e);}})).toContain('操作元が不正');
  await chrome.getByLabel('内部ブラウザのURL').fill('file:///secret.txt');await chrome.locator('#address-form').getByRole('button',{name:'移動',exact:true}).click();await expect(chrome.locator('#notice')).toContainText('HTTPS');expect(site.url()).toBe('https://teams.microsoft.com/');
  const popup=await chromeAfter(()=>site.locator('#fixture-popup').click());await expect(popup.locator('#address')).toHaveValue('https://teams.microsoft.com/popup');await closeBrowsers();await page.getByLabel('Sアカウント接続を閉じる').click();
  const connected=await connect('teams','Teams確認用');await expect(page.getByLabel('Microsoftのアカウントを確認')).toBeVisible();await ribbonFits(1);await ownAvatar('microsoft');await readableText(page);await readableText(connected.chrome);await closeBrowsers();
});
test('S共有でCSVを用意し、ファイル選択・本文コピー・保存を行い、元ファイルと既存OAuthを保つ',async()=>{
  await page.locator('[data-row="0"][data-col="0"]').click();await page.locator('[data-row="2"][data-col="4"]').click({modifiers:['Shift']});await page.locator('.menubar').getByRole('button',{name:'S共有',exact:true}).click();await page.getByLabel('S共有先').selectOption('gmail');await page.getByLabel('S共有の件名').fill('共有サンプル');await page.getByLabel('S共有の宛先').fill('example@example.com');await page.getByLabel('S共有のメッセージ').fill('添付を確認');
  const chrome=await chromeAfter(()=>page.getByRole('button',{name:'内部ブラウザで共有',exact:true}).click());await expect(chrome.locator('#file-name')).toHaveText('共有サンプル.csv');const site=await remote(chrome);expect(new URL(site.url()).searchParams.get('to')).toBe('example@example.com');expect(await site.evaluate(()=>(window as any).fixtureUpload)).toBeUndefined();await app.evaluate(()=>(globalThis as any).sDialogResponse=2);await site.locator('#fixture-upload').click();await expect.poll(()=>app.evaluate(()=>(globalThis as any).sDialogLog.includes('共有ファイルを添付'))).toBe(true);expect(await site.locator('#fixture-upload').evaluate((el:HTMLInputElement)=>el.files?.length)).toBe(0);await app.evaluate(()=>(globalThis as any).sDialogResponse=0);await site.locator('#fixture-upload').click();await expect(site.locator('#fixture-result')).toHaveText('共有サンプル.csv');const uploaded=await site.evaluate(()=>(window as any).fixtureUpload);expect(uploaded.text).toContain('000001');expect(uploaded.text).toContain('1200000');await chrome.getByRole('button',{name:'本文をコピー',exact:true}).click();expect(await app.evaluate(({clipboard})=>clipboard.readText())).toBe(uploaded.text);
  await app.evaluate(({dialog},target)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:target});},file);await chrome.getByRole('button',{name:'共有ファイルを保存',exact:true}).click();await expect(chrome.locator('#notice')).toContainText('元ファイル');expect(fs.readFileSync(file)).toEqual(original);
  const saved=path.join(dir,'shared.csv');await app.evaluate(({dialog},target)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:target});},saved);await chrome.getByRole('button',{name:'共有ファイルを保存',exact:true}).click();await expect.poll(()=>fs.existsSync(saved)).toBe(true);expect(fs.readFileSync(saved,'utf8')).toBe(uploaded.text);await closeBrowsers();await page.getByLabel('S共有を閉じる').click();
  await page.evaluate(()=>window.csv.configureConnection('google',{clientId:'fixture-client',access_token:'fixture-only-token'}));await expect(page.getByLabel('Googleのアカウントを確認')).toBeVisible();await ribbonFits(2);await ownAvatar('google');
});
test('全アカウントのアイコン位置・テーマ・再起動復元と、確認付きログアウトの範囲を検証する',async()=>{
  for(const [service,label,provider,count] of [['gmail','Google確認用','google',2],['github','GitHub確認用','github',3],['slack','Slack確認用','slack',4],['discord','Discord確認用','discord',5]] as const){await connect(service,label);await ownAvatar(provider);await ribbonFits(count);}
  await expect(page.locator('.account-icon')).toHaveCount(5);for(const width of [1000,1440]){await app.evaluate(({BrowserWindow},width)=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('dist/index.html'))!.setContentSize(width,940),width);const last=(await page.locator('.account-icon').last().boundingBox())!,theme=(await page.getByLabel('テーマを切り替え').boundingBox())!;expect(last.x+last.width).toBeLessThanOrEqual(theme.x);await expect(page.locator('.compact-titlebar')).toHaveCSS('height','34px');expect((await page.locator('.online-bar').boundingBox())!.width).toBeGreaterThanOrEqual(100);}
  await page.getByLabel('テーマを切り替え').click();await readableText(page);for(const chrome of app.windows().filter(p=>p.url().includes('s-browser.html')))await readableText(chrome);await closeBrowsers();await app.close();await launch();await expect(page.locator('.account-icon')).toHaveCount(5);await ownAvatar('google');await ownAvatar('microsoft');await ribbonFits(5);
  await page.evaluate(()=>window.csv.configureConnection('google',{clientId:'fixture-client',access_token:'fixture-only-token'}));const google=await connect('gmail','Google確認用');expect(google.storedLogin).toBe('google-signed-in');await closeBrowsers();await page.getByLabel('Googleのアカウントを確認').click();await page.getByRole('button',{name:'キャンセル',exact:true}).click();await expect(page.getByLabel('Googleのアカウントを確認')).toBeVisible();await page.getByLabel('Googleのアカウントを確認').click();const apiChoice=page.getByLabel('既存の「接続」の認証を解除');if(await apiChoice.count())await apiChoice.uncheck();await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.csv.sAccounts().then(a=>a.find(p=>p.provider==='google')?.connected))).toBe(false);expect(await page.evaluate(()=>window.csv.sAccounts().then(a=>a.find(p=>p.provider==='microsoft')?.connected))).toBe(true);
  expect(await page.evaluate(()=>window.csv.connections().then(s=>s.providers.google.connected))).toBe(true);expect(await page.evaluate(()=>window.csv.sAccounts().then(a=>a.find(p=>p.provider==='google')?.avatar))).toBeUndefined();await ownAvatar('google');expect(await app.evaluate(({session})=>session.fromPartition('persist:csv-nyaan-s-google').cookies.get({}))).toEqual([]);const cleared=await connect('gmail','再接続確認');expect(cleared.storedLogin).toBeNull();await closeBrowsers();
  await page.locator('.menubar').getByRole('button',{name:'接続',exact:true}).click();await expect(page.getByLabel('OAuthクライアントID')).toHaveValue('fixture-client');await page.getByLabel('共有画面を閉じる').click();
});

test('画像取得失敗時はサービスアイコンに戻り、他人の画像を採用せず、更新で復元する',async()=>{
  const {chrome,site}=await connect('github','GitHub画像更新');await ownAvatar('github');await site.locator('#own-account').evaluate(el=>(el as HTMLElement).style.display='none');await chrome.getByRole('button',{name:'画像を更新',exact:true}).click();await expect(chrome.locator('#notice')).toContainText('サービスのアイコン');const icon=page.getByLabel('GitHubのアカウントを確認');await expect(icon.locator('img')).toHaveCount(0);await expect(icon.locator('svg')).toBeVisible();expect(await page.evaluate(()=>window.csv.sAccounts().then(a=>a.find(p=>p.provider==='github')?.connected))).toBe(true);
  await site.locator('#fixture-login').click();await chrome.getByRole('button',{name:'再読み込み',exact:true}).click();await ownAvatar('github');await chrome.getByRole('button',{name:'画像を更新',exact:true}).click();await expect(chrome.locator('#notice')).toContainText('ユーザーの画像');await ownAvatar('github');
  // Cached-but-undecodable images must still fall back at the renderer boundary.
  await page.evaluate(()=>document.querySelector<HTMLImageElement>('.account-icon img')!.src='data:image/png;base64,YmFk');await expect(page.locator('.account-icon img')).toHaveCount(4);await ribbonFits(5);await closeBrowsers();
});
