import {launchWithoutTutorial} from './electron-profile';
import {test,expect,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {readableText} from './ui-contrast';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'s-navigation-ui-'));let app:ElectronApplication,page:Page;
const errors:string[]=[];test.describe.configure({mode:'serial'});
test.beforeAll(async()=>{app=await launchWithoutTutorial({args:['--no-sandbox','--user-data-dir='+path.join(dir,'profile'),'.',path.join(process.cwd(),'samples/sales.csv')],cwd:process.cwd(),env:{...process.env}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await expect(page.locator('[data-row="0"][data-col="1"]')).toHaveText('1200000',{timeout:30000});await app.evaluate(({session,shell})=>{(globalThis as any).sExternal=[];shell.openExternal=async url=>{(globalThis as any).sExternal.push(url);};for(const id of ['google','microsoft','github','slack','discord']){const ses=session.fromPartition('persist:csv-nyaan-s-'+id);ses.protocol.handle('https',request=>{const url=new URL(request.url);if(url.pathname==='/shell')return new Response('<html><body style="margin:0;min-height:100vh;background:rgb(30,170,85)"><div id="root"></div><script>setTimeout(()=>requestAnimationFrame(()=>document.querySelector("#root").textContent="Delayed web application"),1200)</script></body></html>',{headers:{'Content-Type':'text/html'}});if(url.pathname==='/slow')return new Promise<Response>(resolve=>setTimeout(()=>resolve(new Response('Old slow page',{headers:{'Content-Type':'text/html'}})),800));return new Response('<!doctype html><html><body style="margin:0;min-height:100vh;background:rgb(30,170,85)"><h1>Service '+id+'</h1><button id="popup">Popup</button><button id="redirect">Redirect to login</button><script>document.querySelector("#popup").onclick=()=>{const p=window.open("about:blank");setTimeout(()=>p.location.href=location.origin+"/popup",100)};document.querySelector("#redirect").onclick=()=>location.href="https://accounts.google.com/login";</script></body></html>',{headers:{'Content-Type':'text/html'}});});}});});
test.afterAll(async()=>{await app.close();expect(errors).toEqual([]);});
async function open(service:string){const before=new Set(app.context().pages());await page.evaluate(service=>window.csv.sOpen({service,table:{headers:['A'],rows:[['1']]}}),service);await expect.poll(()=>app.context().pages().some(p=>!before.has(p)&&p.url().includes('s-browser.html'))).toBe(true);const chrome=app.context().pages().find(p=>!before.has(p)&&p.url().includes('s-browser.html'))!;await expect(chrome.locator('#service')).not.toHaveText('S内部ブラウザ');return chrome;}
async function close(){await app.evaluate(({BrowserWindow})=>{for(const win of BrowserWindow.getAllWindows())if(win.webContents.getURL().includes('s-browser.html'))win.close();});}
async function rendered(chrome:Page){await expect(chrome.locator('#page-status')).toBeHidden();return app.evaluate(async({BrowserWindow},chromeURL)=>{const win=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL()===chromeURL)!,view=win.contentView.children.find((v:any)=>v.webContents?.getURL().startsWith('https://')) as any,bounds=view.getBounds(),image=await view.webContents.capturePage(),bitmap=image.toBitmap(),size=image.getSize(),at=(Math.floor(size.height/2)*size.width+Math.floor(size.width/2))*4;return {visible:view.getVisible(),bounds,content:win.getContentBounds(),size,color:[bitmap[at+2],bitmap[at+1],bitmap[at]],remote:view.webContents.getURL()};},chrome.url());}
test('11サービスのS共有で、URLだけでなく内部ページの可視領域と描画を確認する',async()=>{
  const services=await page.evaluate(()=>window.csv.sServices());expect(services).toHaveLength(11);for(const s of services){const chrome=await open(s.id),result=await rendered(chrome);expect(result.visible).toBe(true);expect(result.bounds.x).toBe(0);expect(result.bounds.y).toBe(164);expect(result.bounds.width).toBe(result.content.width);expect(result.bounds.height).toBe(result.content.height-164);expect(result.size.width).toBeGreaterThan(0);expect(result.size.height).toBeGreaterThan(0);expect(result.color).toEqual([30,170,85]);await close();}
});
test('初回の通信失敗でも接続先URLを保持し、両配色でエラーから外部ブラウザ・再試行へ復帰する',async()=>{
  await app.evaluate(({session})=>session.fromPartition('persist:csv-nyaan-s-google').webRequest.onBeforeRequest((details,callback)=>callback({cancel:details.resourceType==='mainFrame'})));const chrome=await open('gmail');await expect(chrome.locator('#page-status')).toHaveAttribute('data-phase','failed');await expect(chrome.locator('#page-title')).toHaveText('サービスのページを開けませんでした');await expect(chrome.locator('#page-detail')).toContainText('ERR_BLOCKED_BY_CLIENT');const address=await chrome.locator('#address').inputValue();expect(address).toMatch(/^https:\/\/mail\.google\.com\/mail\/\?/);await expect(chrome.locator('#confirm')).toBeDisabled();
  for(const theme of ['light','dark']){await page.evaluate(theme=>window.csv.preferences({theme:theme as 'light'|'dark'}),theme);await expect(chrome.locator('html')).toHaveAttribute('data-theme',theme);await readableText(chrome);}await chrome.locator('#external-retry').click();expect(await app.evaluate(()=>(globalThis as any).sExternal.at(-1))).toBe(address);
  await app.evaluate(({session})=>session.fromPartition('persist:csv-nyaan-s-google').webRequest.onBeforeRequest(null));await chrome.locator('#retry').click();expect((await rendered(chrome)).color).toEqual([30,170,85]);await expect(chrome.locator('#confirm')).toBeEnabled();await close();
});
test('再読み込み・トップ復帰・不正なURL・中断とabout:blankの認証ポップアップを扱う',async()=>{
  const chrome=await open('github');await rendered(chrome);await chrome.locator('#address').fill('https://gist.github.com/slow');await chrome.locator('#address-form button').click();await chrome.locator('#address').fill('https://gist.github.com/fast');await chrome.locator('#address-form button').click();await expect(chrome.locator('#address')).toHaveValue('https://gist.github.com/fast');await rendered(chrome);await expect(chrome.locator('#notice')).not.toContainText('ERR_ABORTED');
  await chrome.locator('#address').fill('file:///secret.txt');await chrome.locator('#address-form button').click();await expect(chrome.locator('#notice')).toContainText('HTTPS');await expect(chrome.locator('#page-status')).toBeHidden();const site=app.context().pages().find(p=>p.url()==='https://gist.github.com/fast')!;const before=new Set(app.context().pages());await site.locator('#popup').click();await expect.poll(()=>app.context().pages().some(p=>!before.has(p)&&p.url().includes('s-browser.html'))).toBe(true);const popup=app.context().pages().find(p=>!before.has(p)&&p.url().includes('s-browser.html'))!;await expect(popup.locator('#address')).toHaveValue('https://gist.github.com/popup');await rendered(popup);
  await app.evaluate(({session})=>session.fromPartition('persist:csv-nyaan-s-github').webRequest.onBeforeRequest((d,callback)=>callback({cancel:d.resourceType==='mainFrame'})));await chrome.locator('#reload').click();await expect(chrome.locator('#page-status')).toHaveAttribute('data-phase','failed');await app.evaluate(({session})=>session.fromPartition('persist:csv-nyaan-s-github').webRequest.onBeforeRequest(null));await chrome.locator('#home').click();await expect(chrome.locator('#address')).toHaveValue('https://gist.github.com/');await rendered(chrome);await close();
});

test('接続入口はサービスのトップを開き、描画処理が停止しても空白から再試行できる',async()=>{
  const before=new Set(app.context().pages());await page.evaluate(()=>window.csv.sOpen({service:'gmail'}));await expect.poll(()=>app.context().pages().some(p=>!before.has(p)&&p.url().includes('s-browser.html'))).toBe(true);const chrome=app.context().pages().find(p=>!before.has(p)&&p.url().includes('s-browser.html'))!;await expect(chrome.locator('#address')).toHaveValue('https://mail.google.com/');await rendered(chrome);await app.evaluate(({webContents})=>webContents.getAllWebContents().find(w=>w.getURL()==='https://mail.google.com/')!.forcefullyCrashRenderer());await expect(chrome.locator('#page-status')).toHaveAttribute('data-phase','failed');await expect(chrome.locator('#page-message')).toContainText('描画処理が停止');await expect(chrome.locator('#confirm')).toBeDisabled();await chrome.locator('#retry').click();expect((await rendered(chrome)).color).toEqual([30,170,85]);await close();
});


test('Web用の識別情報を使用し、非同期の画面生成を待って空白の読み込み完了を防ぐ',async()=>{
  const chrome=await open('discord');await rendered(chrome);const site=app.context().pages().find(p=>p.url()==='https://discord.com/app')!;const agent=await site.evaluate(()=>navigator.userAgent);expect(agent).toContain('Chrome/');expect(agent).not.toContain('Electron/');expect(agent).not.toContain('csv-nyaan-viewer/');await chrome.locator('#address').fill('https://discord.com/shell');await chrome.locator('#address-form button').click();await expect(chrome.locator('#page-status')).toHaveAttribute('data-phase','loading');await expect(chrome.locator('#confirm')).toBeDisabled();await expect(chrome.locator('#page-status')).toBeHidden();await expect(app.context().pages().find(p=>p.url()==='https://discord.com/shell')!.locator('body')).toContainText('Delayed web application');await rendered(chrome);await close();
});
