'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),http=require('node:http');
const table={headers:['ID','値'],rows:[['000001','=1+1'],['12345678901234567890','文字列']]};
function harness(responder){const requests=[],opened=[];const electron={shell:{openExternal:async url=>opened.push(url)},safeStorage:{isEncryptionAvailable:()=>false,getSelectedStorageBackend:()=> 'basic_text'},net:{fetch:async(url,options)=>{requests.push({url,options});const data=await responder(url,options);return {ok:true,status:200,text:async()=>typeof data==='string'?data:JSON.stringify(data)};}}};const module={exports:{}};vm.runInNewContext(fs.readFileSync('electron/sharing.cjs','utf8'),{require:name=>name==='electron'?electron:name==='./tables.cjs'?require('../electron/tables.cjs'):require(name),module,exports:module.exports,process,Buffer,URL,URLSearchParams,FormData,Blob,AbortSignal,setTimeout,clearTimeout});const api=module.exports;api.init(fs.mkdtempSync(path.join(os.tmpdir(),'csv-lens-share-')));return {api,requests,opened};}
test('トークンは安全な保存領域がない環境でディスクに平文保存しない',()=>{const {api}=harness(()=>({}));const status=api.configure('google',{clientId:'test',access_token:'fake-sensitive-token'});assert.equal(status.providers.google.connected,true);assert.equal(status.secureStorage,false);assert.equal(JSON.stringify(status).includes('fake-sensitive-token'),false);});
test('Google Sheetsへの書き込みはRAWで先頭ゼロ・式文字列を保持',async()=>{const {api,requests}=harness(url=>url.endsWith('/spreadsheets')?{spreadsheetId:'id',spreadsheetUrl:'https://sheets.google.com/id'}:{});api.configure('google',{access_token:'fake-token'});await api.share({service:'sheets',table});const write=requests.find(r=>r.url.includes('valueInputOption'));assert.ok(write.url.includes('valueInputOption=RAW'));assert.deepEqual(JSON.parse(write.options.body).values,[table.headers,...table.rows]);});
test('Google DriveはCSVファイルをmultipartとして作成',async()=>{const {api,requests}=harness(()=>({id:'file'}));api.configure('google',{access_token:'fake'});const result=await api.share({service:'drive',table});assert.match(result.url,/drive.google.com/);assert.match(requests[0].options.body.toString(),/000001/);});
test('GmailはCSV添付の下書き作成だけを行う',async()=>{const {api,requests}=harness(()=>({id:'draft'}));api.configure('google',{access_token:'fake'});await api.share({service:'gmail',table,recipient:'user@example.com',title:'テスト',message:'本文'});assert.match(requests[0].url,/\/drafts$/);const raw=Buffer.from(JSON.parse(requests[0].options.body).message.raw,'base64url').toString();assert.match(raw,/multipart\/mixed/);assert.match(raw,/attachment/);assert.ok(!requests.some(r=>r.url.includes('/send')));});
test('Google ChatはDriveリンクを指定スペースへ投稿',async()=>{const {api,requests}=harness(url=>url.includes('/upload/')?{id:'f'}:{name:'spaces/abc/messages/1'});api.configure('google',{access_token:'fake'});await api.share({service:'chat',table,recipient:'spaces/abc'});assert.ok(requests[1].url.endsWith('/spaces/abc/messages'));await assert.rejects(api.share({service:'chat',table,recipient:'invalid'}));});
test('OneDrive・Teamsは識別子付きのCSVを作成',async()=>{const {api,requests,opened}=harness(()=>({id:'f',webUrl:'https://onedrive.live.com/file'}));api.configure('microsoft',{access_token:'fake'});await api.share({service:'onedrive',table});assert.match(requests[0].url,/export-[a-f0-9]{6}\.csv/);await api.share({service:'teams',table,recipient:'user@example.com'});assert.match(opened[0],/teams.microsoft.com/);});
test('Outlookは添付付き下書きを作成し、送信APIは呼ばない',async()=>{const {api,requests}=harness(()=>({id:'d',webLink:'https://outlook.office.com/d'}));api.configure('microsoft',{access_token:'fake'});await api.share({service:'outlook',table,recipient:'a@example.com;b@example.com'});const body=JSON.parse(requests[0].options.body);assert.equal(body.toRecipients.length,2);assert.equal(body.attachments[0].contentType,'text/csv');assert.ok(!requests.some(r=>r.url.includes('/send')));});
test('Excel Online出力のセルは式ではなく文字列として格納',async()=>{const ExcelJS=require('exceljs'),{api,requests}=harness(()=>({id:'xlsx',webUrl:'https://onedrive.live.com/xlsx'}));api.configure('microsoft',{access_token:'fake'});await api.share({service:'excel',table});const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(requests[0].options.body);const ws=workbook.getWorksheet('Data');assert.equal(ws.getCell('A2').value,'000001');assert.equal(ws.getCell('B2').value,'=1+1');assert.equal(ws.getCell('A3').value,'12345678901234567890');});
test('GitHubは既定で公開一覧に掲載しないGistを作成',async()=>{const {api,requests}=harness(()=>({id:'g',html_url:'https://gist.github.com/g'}));api.configure('github',{access_token:'fake'});await api.share({service:'github',table});assert.equal(JSON.parse(requests[0].options.body).public,false);});
test('Slack Botは外部アップロード方式でCSVを添付',async()=>{const {api,requests}=harness(url=>url.includes('getUploadURLExternal')?{ok:true,file_id:'file',upload_url:'https://files.slack.com/upload'}:{ok:true});api.configure('slack',{access_token:'fake'});await api.share({service:'slack',table,recipient:'C0001'});assert.ok(requests[2].url.includes('completeUploadExternal'));assert.equal(JSON.parse(requests[2].options.body).channel_id,'C0001');});
test('Discord WebhookはCSVファイルを添付し、mentionを無効化',async()=>{const {api,requests}=harness(()=>({id:'1'}));api.configure('discord',{webhook:'https://discord.com/api/webhooks/fake'});await api.share({service:'discord',table});assert.ok(requests[0].options.body instanceof FormData);assert.equal(requests[0].options.body.get('files[0]').name,'csv-lens-export.csv');assert.deepEqual(JSON.parse(requests[0].options.body.get('payload_json')).allowed_mentions,{parse:[]});});
test('Webhookのホスト制限と未接続は明示的に拒否',async()=>{const {api}=harness(()=>({}));api.configure('discord',{webhook:'https://example.com/no'});await assert.rejects(api.share({service:'discord',table}),/公式Webhook/);await assert.rejects(api.share({service:'drive',table}),/ログイン/);});
test('Google OAuthはシステムブラウザ、PKCE、state検証を使う',async()=>{const {api,opened}=harness(()=>({access_token:'fake',refresh_token:'fake-refresh',expires_in:3600}));api.configure('google',{clientId:'test-client',clientSecret:'test-desktop-secret'});const pending=api.login('google',()=>{});for(let n=0;n<100&&!opened.length;n++)await new Promise(r=>setTimeout(r,10));assert.ok(opened.length);const url=new URL(opened[0]);assert.ok(url.searchParams.get('code_challenge'));assert.equal(url.searchParams.get('code_challenge_method'),'S256');const callback=new URL(url.searchParams.get('redirect_uri'));callback.searchParams.set('state',url.searchParams.get('state'));callback.searchParams.set('code','fake-code');await new Promise((resolve,reject)=>http.get(callback,res=>{res.resume();res.on('end',resolve);}).on('error',reject));assert.equal((await pending).providers.google.connected,true);});
test('ブラウザ共有とアプリ起動はアップロードを呼ばない',async()=>{const {api,requests,opened}=harness(()=>({}));await api.browser({service:'gmail',recipient:'a@example.com',table});await api.browser({service:'discord',native:true});assert.equal(requests.length,0);assert.match(opened[0],/mail.google.com/);assert.equal(opened[1],'discord://');});

test('Markdown文書のDrive共有は本文とグラフをZIPにまとめる',async()=>{const {api,requests}=harness(()=>({id:'file'}));api.configure('google',{access_token:'fake'});await api.share({service:'drive',table:{headers:[],rows:[]},document:[{id:'test-chart',name:'図',kind:'chart',image:'data:image/png;base64,iVBORw0KGgo=',table:{headers:[],rows:[]}},{id:'text',name:'文章',kind:'text',content:'# テキスト',table:{headers:[],rows:[]}}]});const body=requests[0].options.body;assert.match(body.toString(),/application\/zip/);const start=body.indexOf(Buffer.from('PK\x03\x04'));assert.ok(start>0);const zip=await require('jszip').loadAsync(body.subarray(start));assert.ok(zip.file('document.md'));assert.ok(zip.file('assets/chart-test-chart.png'));assert.match(await zip.file('document.md').async('string'),/# テキスト/);});
