import {test,expect,_electron as electron,type ElectronApplication,type Page} from '@playwright/test';
import {readableText} from './ui-contrast';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const root=process.cwd(),profile=fs.mkdtempSync(path.join(os.tmpdir(),'csv-first-tutorial-')),file=path.join(root,'samples/sales.csv'),original=fs.readFileSync(file),sample=fs.readFileSync(path.join(root,'assets/tutorial.csv'));
let app:ElectronApplication,page:Page;const errors:string[]=[];const guide=()=>page.getByRole('dialog',{name:/クリックして、|ファイルとセル|範囲を選択|グラフをプレビュー|選択範囲をテーブル|選択範囲の変量|多変量分析とPC|テキスト・表・グラフ|ペインの位置|検索・フィルター|Markdownとテキスト|別の形式へ|共有・アカウント|配色・出力|チュートリアルを完了/});
async function launch(){app=await electron.launch({args:['--no-sandbox','--user-data-dir='+profile,'.',file],cwd:root,env:{...process.env}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await expect(page.locator('.document-heading h1')).toContainText('sales.csv',{timeout:30000});}
async function next(){await guide().getByRole('button',{name:'次へ',exact:true}).click();}
test.describe.configure({mode:'serial'});test.beforeAll(launch);test.afterAll(async()=>{await app.close();expect(errors).toEqual([]);expect(fs.readFileSync(file)).toEqual(original);expect(fs.readFileSync(path.join(root,'assets/tutorial.csv'))).toEqual(sample);});
test('初回は自動表示し、あとでを選ぶと再起動後には表示しない',async()=>{
  await expect(guide()).toBeVisible();await expect(guide()).toHaveAttribute('aria-modal','true');await page.screenshot({path:'release/tutorial-v1.5.5-intro.png'});await guide().getByRole('button',{name:'あとで',exact:true}).click();await expect(page.locator('.tutorial-card')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>window.csv.preferences().then(p=>p.tutorialStatus))).toBe('skipped');await app.close();await launch();await expect(page.locator('.tutorial-card')).toHaveCount(0);expect(await page.evaluate(()=>window.csv.preferences().then(p=>p.recent))).not.toContain(path.join(root,'assets/tutorial.csv'));
});
test('ヘルプから再実行し、実際の選択・テーブル・結合と全13段階を完了して元の作業を保持する',async()=>{
  test.setTimeout(90000);await page.locator('[data-row="0"][data-col="1"]').click();await page.locator('[data-row="5"][data-col="3"]').click({modifiers:['Shift']});await page.locator('.grid-scroll').press('Control+t');await expect(page.locator('.saved-table')).toHaveCount(1);await page.locator('.saved-table header input').fill('元のテーブル');await page.locator('#dock-tab-merge').click();await page.getByLabel('テキストブロックを追加').click();await expect(page.locator('.merge-block')).toHaveCount(1);
  await expect.poll(()=>page.evaluate(()=>window.csv.preferences().then(p=>p.dockLayout?.open.includes('merge')&&p.dockLayout.active.bottom==='table'))).toBe(true);await page.locator('.rail-bottom .boundary-toggle').click();await expect.poll(()=>page.evaluate(()=>window.csv.preferences().then(p=>p.dockLayout?.open.includes('chart')))).toBe(false);const before=await page.evaluate(()=>window.csv.preferences());await page.getByRole('button',{name:'ヘルプ',exact:true}).click();await page.getByRole('button',{name:'クリックして学ぶチュートリアル',exact:true}).click();await guide().getByRole('button',{name:'チュートリアルを開始',exact:true}).click();await expect(guide().getByRole('heading')).toHaveText('ファイルとセルを読む');await expect(page.locator('.document-heading h1')).toContainText('tutorial.csv');
  await next();await expect(guide().getByRole('button',{name:'次へ',exact:true})).toBeDisabled();await page.locator('[data-row="0"][data-col="1"]').click();await page.locator('[data-row="5"][data-col="3"]').click({modifiers:['Shift']});await expect(guide()).toContainText('操作を確認しました');await next();await expect(page.locator('.chart-area canvas')).toBeVisible();await page.getByLabel('グラフのカラーセット').selectOption('pastel');await page.screenshot({path:'release/tutorial-v1.5.5-chart.png'});
  await next();await guide().getByRole('button',{name:'練習用テーブルを作成',exact:true}).click();await expect(guide()).toContainText('操作を確認しました');await expect(page.locator('.saved-table')).toHaveCount(2);await page.locator('.saved-table header input').last().fill('練習テーブル');await next();await expect(page.locator('.analysis-variable')).not.toHaveCount(0);await next();await expect(page.locator('.analysis-pca')).toBeVisible();await expect(page.locator('.analysis-pca')).toContainText('PCと色の見方');
  await next();await guide().getByRole('button',{name:'練習範囲を結合へ追加',exact:true}).click();await expect(guide()).toContainText('操作を確認しました');await expect(page.locator('.merge-block')).toHaveCount(2);await next();await guide().getByRole('button',{name:'グラフを右ペインへ移動',exact:true}).click();await expect(page.locator('.dock-slot.right #dock-tab-chart')).toHaveAttribute('aria-selected','true');
  await next();await guide().getByRole('button',{name:'検索バーを開く',exact:true}).click();await page.getByLabel('検索語').fill('360000');await page.getByLabel('検索語').press('Enter');await next();await guide().getByRole('button',{name:'Markdownの練習文書を開く',exact:true}).click();await expect(page.locator('.markdown-body h1')).toContainText('チュートリアル用');await guide().getByRole('button',{name:'TXTの練習文書を開く',exact:true}).click();await expect(page.locator('.document-heading h1')).toContainText('tutorial.txt');
  await next();await guide().getByRole('button',{name:'エクスポート設定を開く',exact:true}).click();await expect(page.locator('.modal')).toContainText('エクスポート');await page.getByLabel('ダイアログを閉じる',{exact:true}).click();await next();await expect(guide()).toContainText('S共有・Sアカウント接続');await next();await guide().getByRole('button',{name:'表示設定を開く',exact:true}).click();await page.getByLabel('カラープロファイル').selectOption('dark');await readableText(page);await page.screenshot({path:'release/tutorial-v1.5.5-settings-dark.png'});await guide().getByRole('button',{name:'完了へ',exact:true}).click();await expect(guide().getByRole('heading')).toHaveText('チュートリアルを完了しました');await guide().getByRole('button',{name:'使い始める',exact:true}).click();
  await expect(page.locator('.tutorial-card')).toHaveCount(0);await expect(page.locator('.document-heading h1')).toContainText('sales.csv');await expect.poll(()=>page.evaluate(()=>window.csv.preferences().then(p=>p.tutorialStatus))).toBe('completed');const after=await page.evaluate(()=>window.csv.preferences());expect(after.dockLayout).toEqual(before.dockLayout);expect(after.dockRatios).toEqual(before.dockRatios);expect(after.tutorialRestore).toBeNull();expect(after.recent).toEqual(before.recent);await expect(page.locator('.dock-slot.bottom')).toHaveCount(0);await page.waitForTimeout(250);await expect(page.locator('.dock-slot.bottom')).toHaveCount(0);
  await page.locator('#dock-tab-table').click();await expect(page.locator('.saved-table')).toHaveCount(1);await expect(page.locator('.saved-table header input')).toHaveValue('元のテーブル');await page.locator('#dock-tab-merge').click();await expect(page.locator('.merge-block')).toHaveCount(1);expect(await page.locator('.tabbar button').filter({hasText:'tutorial.'}).count()).toBe(0);
});
test('練習中にウィンドウを閉じても配置を復元し、既存ファイルと最近の履歴を保つ',async()=>{
  const before=await page.evaluate(()=>window.csv.preferences());await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.send('csv:command','tutorial'));await guide().getByRole('button',{name:'チュートリアルを開始',exact:true}).click();await next();await guide().getByRole('button',{name:'練習用の範囲を選択',exact:true}).click();await next();await expect(page.locator('.chart-area canvas')).toBeVisible();await app.close();await launch();await expect(page.locator('.tutorial-card')).toHaveCount(0);const after=await page.evaluate(()=>window.csv.preferences());expect(after.dockLayout).toEqual(before.dockLayout);expect(after.dockRatios).toEqual(before.dockRatios);expect(after.recent).toEqual(before.recent);expect(after.tutorialRestore).toBeUndefined();await expect(page.locator('.document-heading h1')).toContainText('sales.csv');
});
