'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const MAX=256*1024*1024;
function parseOnline(input){const u=new URL(String(input).trim());if(u.protocol!=='https:'||u.username||u.password)throw Error('HTTPSのExcelまたはGoogleスプレッドシートURLを入力してください。');
 const google=u.hostname==='docs.google.com'&&u.pathname.match(/^\/spreadsheets\/d\/([a-zA-Z0-9_-]+)(?:\/|$)/);if(google)return {provider:'google',id:google[1],url:u.href,gid:(u.hash.match(/gid=(\d+)/)||[])[1]||u.searchParams.get('gid')};
 const drive=u.hostname==='drive.google.com'&&u.pathname.match(/^\/file\/d\/([a-zA-Z0-9_-]+)/);if(drive)return {provider:'googleDrive',id:drive[1],url:u.href};
 const microsoft=['1drv.ms','onedrive.live.com','office.live.com','excel.officeapps.live.com'].includes(u.hostname)||u.hostname.endsWith('.sharepoint.com');return {provider:microsoft?'microsoft':'direct',url:u.href};}
function shareId(url){return 'u!'+Buffer.from(url).toString('base64url');}
async function readBytes(response){if(!response.ok)throw Error('HTTP '+response.status);if(Number(response.headers.get('content-length'))>MAX)throw Error('オンラインファイルは256 MiB以内です。');const parts=[];let total=0;for await(const part of response.body){total+=part.length;if(total>MAX){throw Error('オンラインファイルは256 MiB以内です。');}parts.push(Buffer.from(part));}return Buffer.concat(parts);}
function extension(bytes,name=''){if(bytes.subarray(0,4).toString('hex')==='504b0304')return /\.xlsb$/i.test(name)?'.xlsb':'.xlsx';if(bytes.subarray(0,8).toString('hex')==='d0cf11e0a1b11ae1')return '.xls';const text=bytes.subarray(0,500).toString('utf8');if(/<\?xml/.test(text)&&/Workbook|office:document/i.test(text))return '.xml';throw Error('Excelファイルを取得できませんでした。閲覧ページではなくファイルのURL、または対応サービスの共有URLを指定してください。');}
async function openOnline(input,{fetch,accessToken,cacheDir}){const parsed=parseOnline(input),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),90000);const get=(url,options={})=>fetch(url,{...options,signal:controller.signal});let bytes,ext,title='Online Excel',sheet;
try{
 if(parsed.provider==='google'){
   const url='https://docs.google.com/spreadsheets/d/'+parsed.id+'/export?format=xlsx';let publicError;try{bytes=await readBytes(await get(url));ext=extension(bytes);}catch(error){publicError=error;}
   if(!ext){let token;try{token=await accessToken('google');}catch{throw Error('このスプレッドシートは公開ダウンロードできません。接続メニューでGoogleにログインしてください。');}const headers={Authorization:'Bearer '+token};const metaResponse=await get('https://sheets.googleapis.com/v4/spreadsheets/'+parsed.id+'?fields=properties(title),sheets(properties)',{headers});if(!metaResponse.ok)throw Error('Googleスプレッドシートを開けません（HTTP '+metaResponse.status+'）。Sheets APIの有効化・権限を確認してください。');const meta=JSON.parse((await readBytes(metaResponse)).toString());title=meta.properties.title;const props=meta.sheets.map(s=>s.properties);if(props.reduce((n,s)=>n+s.gridProperties.rowCount*s.gridProperties.columnCount,0)>20000000)throw Error('オンラインシートの総セル数が大きすぎます。範囲を絞ったファイルで開いてください。');const query=new URLSearchParams({valueRenderOption:'FORMATTED_VALUE'});props.forEach(p=>query.append('ranges',"'"+p.title.replaceAll("'","''")+"'"));const response=await get('https://sheets.googleapis.com/v4/spreadsheets/'+parsed.id+'/values:batchGet?'+query,{headers});const data=JSON.parse((await readBytes(response)).toString());bytes=Buffer.from(JSON.stringify({sheets:props.map((p,i)=>({name:p.title,values:data.valueRanges[i]?.values||[]}))}));ext='.gsheet-cache';sheet=props.find(p=>String(p.sheetId)===parsed.gid)?.title;
   }
 }else if(parsed.provider==='googleDrive'){
   try{bytes=await readBytes(await get('https://drive.google.com/uc?export=download&id='+parsed.id));ext=extension(bytes);}catch{}
   if(!ext){let token;try{token=await accessToken('google');}catch{throw Error('Google DriveのExcelを開くには、接続メニューでGoogleにログインしてください。');}const headers={Authorization:'Bearer '+token};const metaResponse=await get('https://www.googleapis.com/drive/v3/files/'+parsed.id+'?fields=name,mimeType',{headers});const meta=JSON.parse((await readBytes(metaResponse)).toString());title=meta.name;if(meta.mimeType==='application/vnd.google-apps.spreadsheet')throw Error('Googleスプレッドシートはdocs.google.com/spreadsheetsのURLで開いてください。');bytes=await readBytes(await get('https://www.googleapis.com/drive/v3/files/'+parsed.id+'?alt=media',{headers}));ext=extension(bytes,title);}
 }else if(parsed.provider==='microsoft'){
   let publicUrl=new URL(parsed.url);publicUrl.searchParams.set('download','1');try{bytes=await readBytes(await get(publicUrl.href));ext=extension(bytes,parsed.url);}catch{}
   if(!ext){try{bytes=await readBytes(await get('https://api.onedrive.com/v1.0/shares/'+shareId(parsed.url)+'/root/content'));ext=extension(bytes,parsed.url);}catch{}}
   if(!ext){let token;try{token=await accessToken('microsoft');}catch{throw Error('このExcelは公開ダウンロードできません。接続メニューでMicrosoftにログインしてください。');}const headers={Authorization:'Bearer '+token};const response=await get('https://graph.microsoft.com/v1.0/shares/'+shareId(parsed.url)+'/driveItem',{headers});if(!response.ok)throw Error('Microsoftの共有Excelを開けません（HTTP '+response.status+'）。共有権限と接続設定を確認してください。');const item=JSON.parse((await readBytes(response)).toString());title=item.name||title;const download=item['@microsoft.graph.downloadUrl'];if(!download||new URL(download).protocol!=='https:')throw Error('ダウンロード可能なExcelファイルではありません。');bytes=await readBytes(await get(download));ext=extension(bytes,title);}
 }else{const response=await get(parsed.url);bytes=await readBytes(response);title=decodeURIComponent(new URL(parsed.url).pathname.split('/').pop()||title);ext=extension(bytes,title);}
 fs.mkdirSync(cacheDir,{recursive:true});const filePath=path.join(cacheDir,crypto.randomUUID()+ext);fs.writeFileSync(filePath,bytes,{flag:'wx'});return {path:filePath,sourceUrl:parsed.url,name:title.replace(/\.[^.]+$/,'')+ (ext==='.gsheet-cache'?'.gsheet':ext),options:{sheet}};
}finally{clearTimeout(timeout);}}
module.exports={parseOnline,shareId,extension,readBytes,openOnline};
