'use strict';
function number(value){const raw=String(value??'').trim().replace(/^[￥¥$€£]\s*/,'').replace(/%$/,'').trim(),s=/^[+-]?\d{1,3}(?:,\d{3})+(?:\.\d+)?$/.test(raw)?raw.replaceAll(',',''):raw;return s&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(s)&&Number.isFinite(Number(s))?Number(s):null;}
function quantile(sorted,p){if(!sorted.length)return null;const x=(sorted.length-1)*p,a=Math.floor(x);return sorted[a]+(sorted[Math.ceil(x)]-sorted[a])*(x-a);}
function moments(values){let mean=0,m2=0;values.forEach((x,i)=>{const d=x-mean;mean+=d/(i+1);m2+=d*(x-mean);});const variance=values.length>1?m2/(values.length-1):0;return {mean,variance,sd:Math.sqrt(variance)};}
function regression(pairs){if(pairs.length<2)return {n:pairs.length,r:null,r2:null,slope:null,intercept:null};const xs=pairs.map(p=>p[0]),ys=pairs.map(p=>p[1]),x=moments(xs),y=moments(ys);let cross=0;pairs.forEach(([a,b])=>cross+=(a-x.mean)*(b-y.mean));const denom=(pairs.length-1)*x.sd*y.sd,r=denom?Math.max(-1,Math.min(1,cross/denom)):null,slope=x.variance?cross/((pairs.length-1)*x.variance):null;return {n:pairs.length,r,r2:r===null?null:r*r,slope,intercept:slope===null?null:y.mean-slope*x.mean};}
function ranks(values){const sorted=values.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v),result=[];for(let i=0;i<sorted.length;){let j=i+1;while(j<sorted.length&&sorted[j].v===sorted[i].v)j++;for(let k=i;k<j;k++)result[sorted[k].i]=(i+j-1)/2+1;i=j;}return result;}
function summarize(values){const valid=values.filter(v=>v!==null),sorted=[...valid].sort((a,b)=>a-b),m=moments(valid),q1=quantile(sorted,.25),q3=quantile(sorted,.75),iqr=q1===null?null:q3-q1;const trend=regression(values.flatMap((v,i)=>v===null?[]:[[i,v]]));const pairs=values.slice(1).flatMap((v,i)=>v===null||values[i]===null?[]:[[values[i],v]]),lag1=regression(pairs).r;let monotonic=0;for(const [a,b]of pairs)monotonic+=Math.sign(b-a);const diffs=pairs.map(([a,b])=>b-a),step=moments(diffs),ratios=pairs.filter(([a])=>a!==0).map(([a,b])=>b/a),ratio=moments(ratios);let rule='明確な単純則なし';if(valid.length>=3){if(m.sd===0)rule='定数';else if(diffs.length>=2&&step.sd<=Math.max(1e-9,Math.abs(step.mean)*1e-5))rule='等差系列';else if(ratios.length>=2&&ratio.sd<=Math.max(1e-9,Math.abs(ratio.mean)*1e-5))rule='等比系列';else if((trend.r2??0)>.8)rule='線形トレンド';else if(Math.abs(monotonic)/Math.max(pairs.length,1)>.9)rule='単調な変化';else if((lag1??0)>.7)rule='連続した変化';}
return {n:valid.length,missing:values.length-valid.length,min:sorted[0]??null,max:sorted.at(-1)??null,median:quantile(sorted,.5),q1,q3,iqr,mean:valid.length?m.mean:null,sd:valid.length?m.sd:null,variance:valid.length?m.variance:null,cv:m.mean?m.sd/Math.abs(m.mean):null,outliers:iqr===null?0:valid.filter(v=>v<q1-1.5*iqr||v>q3+1.5*iqr).length,skew:m.sd&&valid.length?valid.reduce((s,v)=>s+((v-m.mean)/m.sd)**3,0)/valid.length:null,trend,lag1,rule};}
function eigen(matrix){const n=matrix.length,a=matrix.map(r=>[...r]),v=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0));for(let iter=0;iter<80*n*n;iter++){let p=0,q=0,max=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(Math.abs(a[i][j])>max){p=i;q=j;max=Math.abs(a[i][j]);}if(max<1e-10)break;const angle=.5*Math.atan2(2*a[p][q],a[q][q]-a[p][p]),c=Math.cos(angle),s=Math.sin(angle),app=a[p][p],aqq=a[q][q],apq=a[p][q];a[p][p]=c*c*app-2*s*c*apq+s*s*aqq;a[q][q]=s*s*app+2*s*c*apq+c*c*aqq;a[p][q]=a[q][p]=0;for(let k=0;k<n;k++)if(k!==p&&k!==q){const kp=a[k][p],kq=a[k][q];a[k][p]=a[p][k]=c*kp-s*kq;a[k][q]=a[q][k]=s*kp+c*kq;}for(let k=0;k<n;k++){const vp=v[k][p],vq=v[k][q];v[k][p]=c*vp-s*vq;v[k][q]=s*vp+c*vq;}}
return Array.from({length:n},(_,i)=>({value:Math.max(0,a[i][i]),vector:v.map(row=>row[i])})).sort((a,b)=>b.value-a.value);}
const distance=(a,b)=>a.reduce((s,x,i)=>s+(x-(b[i]||0))**2,0);
function kmeans(points,k){let centers=[points[0]],assignments=[];while(centers.length<k){let far=0,best=-1;points.forEach((p,i)=>{const d=Math.min(...centers.map(c=>distance(p,c)));if(d>best){best=d;far=i;}});centers.push([...points[far]]);}
for(let iter=0;iter<50;iter++){const next=points.map(p=>centers.reduce((best,c,i)=>distance(p,c)<distance(p,centers[best])?i:best,0));if(next.every((v,i)=>v===assignments[i]))break;assignments=next;centers=centers.map((old,cluster)=>{const members=points.filter((_,i)=>assignments[i]===cluster);return members.length?old.map((_,d)=>members.reduce((s,p)=>s+p[d],0)/members.length):old;});}return {assignments,centers,counts:centers.map((_,c)=>assignments.filter(v=>v===c).length),sse:points.reduce((s,p,i)=>s+distance(p,centers[assignments[i]]),0)};}
function analyze(table,multivariate=false){const columns=table.headers.map((name,c)=>{const values=table.rows.map(row=>number(row[c]));return {name,column:c,values,stats:summarize(values)};}).filter(c=>c.stats.n>0);const pairColumns=columns.filter(c=>c.stats.n>=3&&c.stats.sd>0).slice(0,32),pairs=[];
for(let a=0;a<pairColumns.length;a++)for(let b=a+1;b<pairColumns.length;b++){const x=pairColumns[a],y=pairColumns[b],values=x.values.flatMap((v,i)=>v===null||y.values[i]===null?[]:[[v,y.values[i]]]),linear=regression(values);const rx=ranks(values.map(v=>v[0])),ry=ranks(values.map(v=>v[1])),spearman=regression(rx.map((v,i)=>[v,ry[i]])).r;pairs.push({x:x.name,y:y.name,xColumn:x.column,yColumn:y.column,...linear,spearman,rule:linear.r!==null&&Math.abs(linear.r)>.8?'強い線形関係':spearman!==null&&Math.abs(spearman)>.8?'単調な非線形関係':'明確な単純関係なし'});}
pairs.sort((a,b)=>Math.abs(b.r||0)-Math.abs(a.r||0));let pca=null;
if(multivariate){const dims=pairColumns.slice(0,16),complete=table.rows.map((_,r)=>({r,values:dims.map(c=>c.values[r])})).filter(row=>row.values.every(v=>v!==null));if(dims.length>=2&&complete.length>=3){const means=dims.map((_,c)=>moments(complete.map(row=>row.values[c]))),standard=complete.map(row=>row.values.map((v,c)=>(v-means[c].mean)/(means[c].sd||1))),cov=dims.map((_,a)=>dims.map((_,b)=>standard.reduce((s,row)=>s+row[a]*row[b],0)/(standard.length-1))),components=eigen(cov),sum=components.reduce((s,c)=>s+c.value,0),scores=standard.map(row=>components.slice(0,3).map(c=>row.reduce((s,v,i)=>s+v*c.vector[i],0)));const groups=scores.length>=6?kmeans(scores,Math.min(3,Math.floor(Math.sqrt(scores.length/2)))):null;
pca={dimensions:dims.map(c=>c.name),completeRows:complete.length,explained:components.map(c=>sum?c.value/sum:0),loadings:components.slice(0,3).map(c=>c.vector),scores:scores.filter((_,i)=>i%Math.max(1,Math.ceil(scores.length/500))===0).map((point,j)=>{const i=j*Math.max(1,Math.ceil(scores.length/500));return {values:point,row:table.sourceRows?.[complete[i].r]??complete[i].r+1,cluster:groups?.assignments[i]??0};}),clusters:groups?.counts||[]};}}
const insights=[];for(const c of columns){if(c.stats.rule!=='明確な単純則なし')insights.push(c.name+'：'+c.stats.rule);if(c.stats.outliers)insights.push(c.name+'：IQR基準の外れ値候補 '+c.stats.outliers+'件');}for(const pair of pairs.slice(0,3))if(Math.abs(pair.r||0)>.8)insights.push(pair.x+' / '+pair.y+'：'+(pair.r>0?'正':'負')+'の相関');if(pca)insights.push('第1〜'+Math.min(3,pca.explained.length)+'主成分で '+(pca.explained.slice(0,3).reduce((s,v)=>s+v,0)*100).toFixed(1)+'% の分散を説明');
return {populationRows:table.populationRows??table.rows.length,sampledRows:table.rows.length,populationColumns:table.populationColumns??table.headers.length,sampledColumns:table.headers.length,columnSummaries:columns.map(({values,...c})=>c),pairs:pairs.slice(0,30),pairColumns:pairColumns.length,pca,insights:insights.slice(0,30),truncated:!!table.truncated,multivariate,precisionWarning:table.rows.some(row=>row.some(v=>/^[-+]?\d{16,}/.test(String(v))))};}
module.exports={number,quantile,moments,regression,ranks,summarize,eigen,kmeans,analyze};
