import {pairPlot,variablePlot,plotPNG,type PlotModel} from './analysis-plot';
import type {PcaViewState} from './pca-view';
import type {AnalysisDocument,AnalysisResult,ExportSection,PlotAsset,VariableSummary} from './analysis-types';
export const analysisLimit='数値の近似計算です。相関は因果関係を示しません。全域・集計分析は最大5,000行・250,000セル・256列の標本、相関は最大32変量、主成分は最大16変量、描画は最大500点/系列です。';
export const variableLimit=analysisLimit.replace('、主成分は最大16変量','');
export function statisticRows(c:VariableSummary):(string|number|null)[][] {const s=c.stats;return [['推定',s.rule],['有効数',s.n],['欠損',s.missing],['平均',s.mean],['標準偏差',s.sd],['分散',s.variance],['中央値',s.median],['最小',s.min],['最大',s.max],['第1四分位',s.q1],['第3四分位',s.q3],['四分位範囲',s.iqr],['変動係数',s.cv],['歪度',s.skew],['外れ値候補',s.outliers],['行順の傾き',s.trend.slope],['行順の切片',s.trend.intercept],['行順のR²',s.trend.r2],['自己相関（1期）',s.lag1]];}
const plotAsset=(model:PlotModel,image=plotPNG(model)):PlotAsset=>({title:model.title,image,headers:['元行','系列','群','X','Y',...(model.dimension===3?['Z']:[])],rows:model.points.map(p=>[p.row,p.series+1,p.cluster+1,p.x,p.y,...(model.dimension===3?[p.z]:[])])});
export async function analysisDocument(result:AnalysisResult,multivariate:boolean,label:string,pcaState?:PcaViewState,onProgress?:(text:string)=>void):Promise<AnalysisDocument>{
  const sections:ExportSection[]=[{title:'分析結果',paragraphs:[label,`${result.sampledRows.toLocaleString()} / ${result.populationRows.toLocaleString()}行 · ${result.sampledColumns} / ${result.populationColumns}列`,result.truncated?'対象の一部を等間隔にサンプリングしています。':'対象の全行・全列を分析しました。',multivariate?(result.correlatedOnly?'相関が認められた変量・組合せを表示しています。':'指定した範囲・テーブルの数値列と組合せを表示しています。'):'非表示の行・列は分析から除外しています。',...(result.alignment?[`${result.alignment.mode} · 合流した列 ${result.alignment.mergedColumns} · 値が異なるため別系列にした列 ${result.alignment.conflictingColumns}`]:[]),...(result.insights.length?result.insights.filter(text=>multivariate||!text.includes('主成分')):['単純な法則は検出されませんでした。'])],tables:result.sources?.length?[{headers:['集計元','対象行','対象列','標本行','標本列'],rows:result.sources.map(s=>[s.name,s.populationRows,s.populationColumns,s.sampledRows,s.sampledColumns])}]:[]}];
  const plots:PlotAsset[]=[];
  for(const c of result.columnSummaries){sections.push({title:c.name,paragraphs:[],tables:[{headers:['項目','値'],rows:statisticRows(c)}]});if(c.stats.rule!=='明確な単純則なし')plots.push(plotAsset(variablePlot(c)));if(plots.length%8===0){onProgress?.('グラフを作成中…');await new Promise<void>(r=>setTimeout(r,0));}}
  for(const p of result.pairs){sections.push({title:p.x+' × '+p.y,paragraphs:[p.rule,`y ≈ ${p.slope??'—'} x + ${p.intercept??'—'}`],tables:[{headers:['組数','Pearson相関','Spearman順位相関','R²','傾き','切片'],rows:[[p.n,p.r,p.spearman,p.r2,p.slope,p.intercept]]}]});if(p.rule!=='明確な単純関係なし')plots.push(plotAsset(pairPlot(p)));}
  if(multivariate&&result.pca){const pca=result.pca;sections.push({title:'主成分の分布',paragraphs:[...(pcaState?.paragraphs||[]),`完全な数値行 ${pca.completeRows} · ${pca.dimensions.length}変量`,'推定した群：'+(pca.clusters.map((n,i)=>'群'+(i+1)+' '+n+'件').join(' / ')||'群分けなし')],tables:[{headers:['主成分','寄与率'],rows:pca.explained.map((v,i)=>['PC'+(i+1),v])},{headers:['変量',...pca.loadings.map((_,i)=>'PC'+(i+1))],rows:pca.dimensions.map((name,i)=>[name,...pca.loadings.map(c=>c[i])])}]});if(pcaState)plots.unshift(plotAsset(pcaState.model,plotPNG(pcaState.model,pcaState.orientation,pcaState.angle)));}
  sections.push({title:'分析の条件・上限',paragraphs:[multivariate?analysisLimit:variableLimit,...(result.precisionWarning?['長い整数は丸めの影響があります。']:[]),'グラフは表示用の標本です。元のセル文字列は変更しません。']});
  return {name:(multivariate?'多変量分析':'変量分析')+'_'+label,sections,plots};
}
