import type {PairSummary,PrincipalComponents,VariableSummary} from './analysis-types';
export interface Point3 {x:number;y:number;z:number;row:number;cluster:number;series:number}
export interface PlotModel {title:string;labels:[string,string,string];axisCaptions?:[string,string,string];points:Point3[];dimension:2|3;uniform?:boolean;lines:boolean;seriesNames:string[];regression?:{slope:number;intercept:number}}
export interface Orientation {yaw:number;pitch:number;roll:number}
export type AxisChoices=[string[],string[],string[]];
export const initialAxes=(pca:PrincipalComponents):AxisChoices=>[['pc:0'],['pc:1'],[pca.loadings.length>2?'pc:2':'zero']];
export function choiceName(pca:PrincipalComponents,key:string){if(key==='zero')return 'Z=0';const [kind,index]=key.split(':');return kind==='pc'?'PC'+(Number(index)+1):pca.dimensions[Number(index)]+'（標準化）';}
export function categoryName(pca:PrincipalComponents,key:string){if(!key.startsWith('pc:'))return choiceName(pca,key);const values=pca.loadings[Number(key.split(':')[1])]||[];return choiceName(pca,key)+'：'+values.map((v,i)=>({name:pca.dimensions[i],weight:v})).sort((a,b)=>Math.abs(b.weight)-Math.abs(a.weight)).slice(0,3).map(v=>v.name+' '+(v.weight>=0?'+':'')+v.weight.toFixed(2)).join(' / ');}
export function pcaPlot(pca:PrincipalComponents,axes:AxisChoices,dimension:2|3,lines:boolean):PlotModel {
  const count=Math.max(...axes.slice(0,dimension).map(a=>a.length)),points:Point3[]=[];
  function value(point:PrincipalComponents['scores'][number],key:string){const [kind,index]=key.split(':');return key==='zero'?0:kind==='pc'?point.values[Number(index)]??0:point.standard[Number(index)]??0;}
  for(let series=0;series<count;series++)for(const p of pca.scores){const keys=axes.map(a=>a[series]||a[0]);points.push({x:value(p,keys[0]),y:value(p,keys[1]),z:dimension===3?value(p,keys[2]):0,row:p.row,cluster:p.cluster,series});}
  const labels=axes.map((a,i)=>a.map(k=>choiceName(pca,k)).join(' / ')||(i===2?'Z=0':'')) as [string,string,string];
  const axisCaptions=axes.map(a=>a.map(key=>key.startsWith('column:')?(pca.dimensions[Number(key.split(':')[1])].split('|').at(-1)?.trim()||choiceName(pca,key)):choiceName(pca,key)).join(' / ')) as [string,string,string];
  return {title:'主成分の分布',labels,axisCaptions,points,dimension,uniform:true,lines,seriesNames:Array.from({length:count},(_,i)=>'系列'+(i+1)+'：'+axes.slice(0,dimension).map(a=>choiceName(pca,a[i]||a[0])).join(' × '))};
}
export function variablePlot(c:VariableSummary):PlotModel {return {title:c.name+'：'+c.stats.rule,labels:['選択順',c.name,''],points:c.plot.filter(p=>p.value!==null).map(p=>({x:p.order??p.row,y:p.value!,z:0,row:p.row,cluster:0,series:0})),dimension:2,lines:true,seriesNames:[c.name]};}
export function pairPlot(p:PairSummary):PlotModel {return {title:p.x+' × '+p.y,labels:[p.x,p.y,''],points:p.plot.map(v=>({...v,z:0,cluster:0,series:0})),dimension:2,lines:false,seriesNames:[p.rule],...(p.slope!==null&&p.intercept!==null?{regression:{slope:p.slope,intercept:p.intercept}}:{})};}
export function rotate(point:{x:number;y:number;z:number},orientation:Orientation,angle:number){const yaw=(orientation.yaw+angle)*Math.PI/180,pitch=orientation.pitch*Math.PI/180,roll=orientation.roll*Math.PI/180;const x=point.x*Math.cos(yaw)-point.z*Math.sin(yaw),depth=point.x*Math.sin(yaw)+point.z*Math.cos(yaw),y=point.y*Math.cos(pitch)-depth*Math.sin(pitch),z=point.y*Math.sin(pitch)+depth*Math.cos(pitch);return {x:x*Math.cos(roll)-y*Math.sin(roll),y:x*Math.sin(roll)+y*Math.cos(roll),z};}
export function geometry(model:PlotModel,orientation:Orientation={yaw:0,pitch:0,roll:0},angle=0){
  const bounds=['x','y','z'].map(axis=>{const values=model.points.map(p=>p[axis as 'x'|'y'|'z']);const min=Math.min(0,...values),max=Math.max(0,...values);return {min,max,span:max-min||1};});
  const extent=Math.max(1,...model.points.flatMap(p=>[Math.abs(p.x),Math.abs(p.y),Math.abs(p.z)]));
  const normalized=model.uniform?model.points.map(p=>({...p,x:p.x/extent,y:p.y/extent,z:model.dimension===3?p.z/extent:0})):model.points.map(p=>({...p,x:(p.x-bounds[0].min)/bounds[0].span*2-1,y:(p.y-bounds[1].min)/bounds[1].span*2-1,z:model.dimension===3?(p.z-bounds[2].min)/bounds[2].span*2-1:0}));
  const project=(p:{x:number;y:number;z:number})=>{const v=model.dimension===3?rotate(p,orientation,angle):p;return {x:240+v.x*132,y:160-v.y*106,z:'z' in v?v.z:0};};
  const origin=model.dimension===3||model.uniform?{x:0,y:0,z:0}:{x:-1,y:-1,z:0},axes=[{x:1.35,y:origin.y,z:origin.z},{x:origin.x,y:1.3,z:origin.z},{x:origin.x,y:origin.y,z:1.35}].slice(0,model.dimension).map((end,i)=>({start:project(origin),end:project(end),name:'XYZ'[i]+': '+model.labels[i],caption:'XYZ'[i]+': '+(model.axisCaptions?.[i]||model.labels[i])}));
  const points=normalized.map((p,i)=>({...p,...project(p),original:model.points[i]}));
  const regression=model.regression?[bounds[0].min,bounds[0].max].map(x=>project({x:(x-bounds[0].min)/bounds[0].span*2-1,y:(model.regression!.slope*x+model.regression!.intercept-bounds[1].min)/bounds[1].span*2-1,z:0})):[];
  return {points,axes,bounds,regression};
}
export interface PlotColors {bg:string;text:string;muted:string;series:string[]}
export function plotColors():PlotColors {const style=getComputedStyle(document.documentElement);return {bg:style.getPropertyValue('--bg').trim(),text:style.getPropertyValue('--text').trim(),muted:style.getPropertyValue('--muted').trim(),series:[1,2,3,4].map(n=>style.getPropertyValue('--plot-'+n).trim())};}
const short=(s:string,max=28)=>s.length>max?s.slice(0,max-1)+'…':s;
export function drawPlot(canvas:HTMLCanvasElement,model:PlotModel,orientation:Orientation,angle:number,colors=plotColors()){
  const context=canvas.getContext('2d')!,g=geometry(model,orientation,angle);context.save();context.fillStyle=colors.bg;context.fillRect(0,0,canvas.width,canvas.height);context.scale(canvas.width/480,canvas.height/340);context.fillStyle=colors.text;context.font='15px "Segoe UI","Yu Gothic UI",sans-serif';context.fillText(short(model.title,42),12,22);context.strokeStyle=colors.muted;context.lineWidth=1.2;
  for(const axis of g.axes){context.beginPath();context.moveTo(axis.start.x,axis.start.y);context.lineTo(axis.end.x,axis.end.y);context.stroke();context.font='22px "Segoe UI","Yu Gothic UI",sans-serif';context.textAlign=axis.end.x>=300?'right':'left';context.fillText(short(axis.caption,18),Math.max(10,Math.min(465,axis.end.x+(axis.end.x>=300?-6:6))),Math.max(40,Math.min(294,axis.end.y)));context.textAlign='left';}
  if(model.lines)for(let series=0;series<model.seriesNames.length;series++){const points=g.points.filter(p=>p.series===series);context.strokeStyle=colors.series[series%4];context.beginPath();points.forEach((p,i)=>i?context.lineTo(p.x,p.y):context.moveTo(p.x,p.y));context.stroke();}
  if(g.regression.length){context.strokeStyle=colors.series[1];context.setLineDash([5,4]);context.beginPath();context.moveTo(g.regression[0].x,g.regression[0].y);context.lineTo(g.regression[1].x,g.regression[1].y);context.stroke();context.setLineDash([]);}
  for(const p of [...g.points].sort((a,b)=>a.z-b.z)){context.fillStyle=colors.series[(model.seriesNames.length>1?p.series:p.cluster)%4];context.beginPath();context.arc(p.x,p.y,2.7,0,2*Math.PI);context.fill();}
  context.fillStyle=colors.text;context.font='12px "Segoe UI","Yu Gothic UI",sans-serif';model.seriesNames.slice(0,2).forEach((name,i)=>context.fillText(short(name,58),10,316+i*16));context.restore();
}
export function plotPNG(model:PlotModel,orientation:Orientation={yaw:0,pitch:0,roll:0},angle=0){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;drawPlot(canvas,model,orientation,angle);return canvas.toDataURL('image/png');}
export function plotFilename(model:PlotModel){return 'analysis_'+model.labels.slice(0,model.dimension).map((label,i)=>'XYZ'[i]+'-'+label.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,48)).join('_');}
export function objText(model:PlotModel){const text=['# CSV nyaan Viewer',...model.labels.slice(0,3).map((label,i)=>'# '+'XYZ'[i]+': '+label.replace(/[\r\n]/g,' '))];for(const p of model.points)text.push(`v ${p.x} ${p.y} ${p.z}`);for(let series=0;series<model.seriesNames.length;series++){text.push('o series_'+(series+1));const ids=model.points.flatMap((p,i)=>p.series===series?[i+1]:[]);for(const id of ids)text.push('p '+id);if(ids.length>1)text.push('l '+ids.join(' '));}return text.join('\n')+'\n';}
export function seriesCorrelations(model:PlotModel){if(model.seriesNames.length<2)return [];const first=model.points.filter(p=>p.series===0),second=model.points.filter(p=>p.series===1);return ['x','y','z'].slice(0,model.dimension).map(key=>{const a=first.map(p=>p[key as 'x'|'y'|'z']),b=second.map(p=>p[key as 'x'|'y'|'z']);const ma=a.reduce((s,v)=>s+v,0)/a.length,mb=b.reduce((s,v)=>s+v,0)/b.length,cross=a.reduce((s,v,i)=>s+(v-ma)*(b[i]-mb),0),den=Math.sqrt(a.reduce((s,v)=>s+(v-ma)**2,0)*b.reduce((s,v)=>s+(v-mb)**2,0));return {axis:key.toUpperCase(),r:den?cross/den:null};});}
