import React,{useEffect,useMemo,useRef,useState} from 'react';
import {FlaskConical,Play,Download} from 'lucide-react';
import type {Tab} from './types';
import {allSources,selectionSources} from './table-state';
import {AnalysisChart} from './analysis-chart';
import {PcaView,type PcaViewState} from './pca-view';
import {pairPlot,plotFilename,plotPNG,variablePlot,type PlotModel} from './analysis-plot';
import {analysisDocument,analysisLimit,variableLimit,statisticRows} from './analysis-document';
import {formatNumber as fmt,type AnalysisResult,type AnalysisSource,type SavedTable} from './analysis-types';
type Scope='sheet'|'ranges'|'all'|'tables';
function DetailChart({model,onError}:{model:PlotModel;onError(text:string):void}) {return <div className="individual-analysis-chart"><AnalysisChart model={model}/><button onClick={()=>window.csv.savePlot(plotPNG(model),'png',plotFilename(model)).catch(e=>onError(String(e)))}><Download size={13}/>PNG保存</button></div>;}
export function AnalysisPanel({tab,tabs,tables,all}:{tab?:Tab;tabs:Tab[];tables:SavedTable[];all:boolean}){
  const [report,setResult]=useState<AnalysisResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[run,setRun]=useState(0),[sheet,setSheet]=useState(''),[scope,setScope]=useState<Scope>('sheet'),[tableIds,setTableIds]=useState<string[]>(tables.map(t=>t.id)),[executedSources,setExecutedSources]=useState<AnalysisSource[]>([]),[exporting,setExporting]=useState('');
  const knownTables=useRef(tables.map(t=>t.id)),pcaState=useRef<PcaViewState|undefined>(undefined);
  useEffect(()=>{setTableIds(ids=>[...ids.filter(id=>tables.some(t=>t.id===id)),...tables.filter(t=>!knownTables.current.includes(t.id)).map(t=>t.id)]);knownTables.current=tables.map(t=>t.id);},[tables]);
  const sources=selectionSources(tabs),selectedTables=tables.filter(t=>tableIds.includes(t.id));
  const cleanSource=(s:AnalysisSource)=>({...s,view:s.view?{filters:s.view.filters,sorts:s.view.sorts,hidden:s.view.hidden,hiddenRows:s.view.hiddenRows,excludedRows:s.view.excludedRows,deletedColumns:s.view.deletedColumns,columnFilter:s.view.columnFilter}:undefined});
  const tableQuery=useMemo(()=>JSON.stringify({sources:selectedTables.map(t=>({name:t.name,table:t}))}),[tables,tableIds]);
  const query=scope==='tables'&&all?tableQuery:JSON.stringify(!all?{id:tab?.meta.id,method:'analyze',args:{all:false,selections:tab?.ranges?.length?tab.ranges:tab?.selection?[tab.selection]:[],visibility:{hiddenRows:tab?.hiddenRows||[],hiddenColumns:[...(tab?.hidden||[]),...(tab?.deletedColumns||[])],columns:tab?.columnFilter}},view:{filters:tab?.filters,sorts:tab?.sorts,count:tab?.meta.count,sheet:tab?.meta.sheet}}:scope==='sheet'?{id:tab?.meta.id,method:'analyze',args:{all:true}}:scope==='ranges'?{sources:sources.map(cleanSource)}:scope==='all'?{sources:executedSources}: {sources:selectedTables.map(t=>({name:t.name,table:t}))});
  useEffect(()=>{setResult(null);setSheet('');pcaState.current=undefined;},[all,scope,all&&scope!=='sheet'?null:tab?.meta.id]);
  useEffect(()=>{
    let alive=true;setBusy(false);setError('');setResult(null);
    const input=JSON.parse(query);if(!all&&!tab?.selection)return;
    if(all&&scope==='all'&&!executedSources.length)return;
    if(!input.id&&!input.sources?.length)return;
    const timer=setTimeout(()=>{setBusy(true);const task=input.sources?window.csv.analyzeMany(input.sources):window.csv.request<AnalysisResult>(input.id,input.method,input.args);task.then(value=>{if(alive){pcaState.current=undefined;setResult(value);}}).catch(e=>{if(alive)setError(String(e));}).finally(()=>{if(alive)setBusy(false);});},250);
    return()=>{alive=false;clearTimeout(timer);};
  },[query,all,scope,run]);
  const result=useMemo(()=>report?.sheets?.find(s=>s.name===(sheet||tab?.meta.sheet))?.result||report?.sheets?.[0]?.result||report,[report,sheet,tab?.meta.sheet]);
  function execute(){setError('');if(all&&scope==='all')setExecutedSources(allSources(tabs));setRun(r=>r+1);}
  function changeScope(next:Scope){setScope(next);setExecutedSources([]);setSheet('');}
  const label=all&&scope!=='sheet'?scope==='ranges'?'選択範囲を集計':scope==='all'?'すべてを集計':'指定テーブルから集計':(tab?.meta.name||tab?.meta.path.split(/[\\/]/).pop()||'')+(all&&tab?.meta.sheet?'_'+(sheet||tab.meta.sheet):'');
  async function exportAnalysis(format:'md'|'xlsx'){if(!result)return;setExporting(format);setError('');try{const doc=await analysisDocument(result,all,label,pcaState.current,text=>setExporting(text));await window.csv.saveAnalysis(doc,format);}catch(e){setError(String(e));}finally{setExporting('');}}
  return <div className="analysis-panel"><header><FlaskConical size={16}/><strong>{all?'多変量分析':'変量分析'}</strong><button className="icon-btn" aria-label="分析を再実行" disabled={busy||(!tab&&!tables.length)} onClick={execute}><Play size={14}/></button></header><p>{all?'相関・主成分・群を推定します。集計元を選択してください。':'選択範囲の分布と1次元・2次元の関係を調べます。非表示の行・列は除外します。'}</p>
  {all&&<fieldset className="analysis-scopes"><legend>集計対象</legend><label className="sheet-scope"><input type="radio" name="analysis-scope" aria-label="分析シート" checked={scope==='sheet'} onChange={()=>changeScope('sheet')}/><span>分析シート（全シート計算済み）<select aria-label="分析するワークシート" disabled={scope!=='sheet'||!report||busy} value={sheet||tab?.meta.sheet||''} onChange={e=>setSheet(e.target.value)}>{report?.sheets?report.sheets.map(s=><option key={s.name}>{s.name}</option>):<option value={tab?.meta.sheet||''}>{tab?.meta.sheet||'現在のファイル'}</option>}</select></span></label><label><input type="radio" name="analysis-scope" aria-label="選択範囲を集計" checked={scope==='ranges'} onChange={()=>changeScope('ranges')}/>選択範囲を集計 <small>{sources.length}シート・ファイル</small></label>{scope==='ranges'&&<div className="analysis-source-list">{sources.map((s,i)=><p key={i}>{s.name} · {s.selections?.length}範囲</p>)}{!sources.length&&<p>複数シート・ファイルで範囲を選択してください。</p>}</div>}<div className="all-scope"><label><input type="radio" name="analysis-scope" aria-label="すべてを集計" checked={scope==='all'} onChange={()=>changeScope('all')}/>すべてを集計</label><button className="icon-btn" aria-label="すべてを集計を実行" disabled={scope!=='all'||busy||!tabs.length} onClick={execute}><Play size={14}/></button></div>{scope==='all'&&!executedSources.length&&<small>▷で開いている全ファイル・全シートの集計を開始します。</small>}<label><input type="radio" name="analysis-scope" aria-label="指定テーブルから集計" checked={scope==='tables'} onChange={()=>changeScope('tables')}/>指定テーブルから集計</label>{scope==='tables'&&<div className="analysis-table-list">{tables.map(t=><label key={t.id}><input type="checkbox" checked={tableIds.includes(t.id)} onChange={e=>setTableIds(ids=>e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/><span>{t.name}</span></label>)}{!tables.length&&<p>Ctrl＋Tで一時テーブルを作成してください。</p>}</div>}</fieldset>}
  {busy&&<p role="status">分析中…</p>}{error&&<p role="alert">{error}</p>}{!tab&&!tables.length&&<p>CSVまたはExcelを開いてください。</p>}
  {result&&<><div className="analysis-sample">{result.sampledRows.toLocaleString()} / {result.populationRows.toLocaleString()}行 · {result.sampledColumns} / {result.populationColumns}列{result.truncated&&<span>対象の一部を等間隔にサンプリング</span>}</div>{result.alignment&&<p className="analysis-alignment">{result.alignment.mode} · 合流した列 {result.alignment.mergedColumns} · 値が異なるため別系列にした列 {result.alignment.conflictingColumns}</p>}{result.sources&&result.sources.length>0&&<details><summary>集計元</summary>{result.sources.map((s,i)=><p key={i}>{s.name}：{s.sampledRows} / {s.populationRows}行 · {s.sampledColumns} / {s.populationColumns}列</p>)}</details>}<div className="analysis-insights">{result.insights.length?result.insights.map((text,i)=><p key={i}>{text}</p>):<p>{all?'相関のある組合せは検出されませんでした。':'単純な法則は検出されませんでした。'}</p>}</div>
  {all&&result.pca&&<PcaView key={result.pca.dimensions.join('\u0000')} pca={result.pca} onState={state=>{pcaState.current=state;}}/>}
  {result.columnSummaries.map(c=><details key={c.column} className="analysis-variable"><summary><span>{c.name}</span><small>{c.stats.rule}</small></summary><dl>{statisticRows(c).slice(1).map(([label,value])=><React.Fragment key={String(label)}><dt>{label}</dt><dd>{typeof value==='number'?fmt(value):value??'—'}</dd></React.Fragment>)}</dl>{c.stats.rule!=='明確な単純則なし'&&<DetailChart model={variablePlot(c)} onError={setError}/>}</details>)}
  {result.pairs.length>0&&<section className="analysis-pairs"><strong>2変量の関係</strong>{result.pairs.map((p,i)=><details key={i}><summary>{p.x} × {p.y}<small>r = {fmt(p.r)}</small></summary><p>{p.rule} · {p.n}組</p><p>順位相関 {fmt(p.spearman)} / R² {fmt(p.r2)}</p><p>y ≈ {fmt(p.slope)} x + {fmt(p.intercept)}</p>{p.rule!=='明確な単純関係なし'&&<DetailChart model={pairPlot(p)} onError={setError}/>}</details>)}</section>}
  <p className="analysis-limit">{all?analysisLimit:variableLimit}{result.precisionWarning?'長い整数は丸めの影響があります。':''}</p><div className="analysis-exports"><button disabled={!!exporting||busy} onClick={()=>exportAnalysis('md')}><Download size={13}/>分析を.md出力</button><button disabled={!!exporting||busy} onClick={()=>exportAnalysis('xlsx')}><Download size={13}/>分析を.xlsx出力</button></div>{exporting&&<p role="status">{exporting}を出力中…</p>}</>}
  </div>;
}
