import * as echarts from 'echarts';
import { feature } from 'topojson-client';
import world from 'world-atlas/countries-110m.json';
import countries from 'i18n-iso-countries';
import ja from 'i18n-iso-countries/langs/ja.json';
import en from 'i18n-iso-countries/langs/en.json';
import { chartData, numeric, type TableData } from './data';
import { chartKind, COLOR_SETS } from './chart-catalog';
import type { ChartSettings, Axis } from './chart-settings';
countries.registerLocale(ja);countries.registerLocale(en);
const geography=feature(world as any,(world as any).objects.countries) as any;
echarts.registerMap('world',geography);
const countryName=(value:string)=>{const code=countries.getAlpha2Code(value,'ja')||countries.getAlpha2Code(value,'en')||(value.length===2?value.toUpperCase():countries.alpha3ToAlpha2(value.toUpperCase()));const name=code?countries.getName(code,'en'):value;return name==='United States'?'United States of America':name||value;};
export function quantile(sorted:number[],q:number){if(!sorted.length)return 0;const p=(sorted.length-1)*q,lo=Math.floor(p);return sorted[lo]+(sorted[Math.ceil(p)]-sorted[lo])*(p-lo);}
export function histogram(values:number[]){if(!values.length)return {labels:[],counts:[],edges:[]};const sorted=[...values].sort((a,b)=>a-b),min=sorted[0],max=sorted.at(-1)!,iqr=quantile(sorted,.75)-quantile(sorted,.25);const width=2*iqr/Math.cbrt(values.length);const n=min===max?1:Math.max(1,Math.min(40,width>0?Math.ceil((max-min)/width):Math.ceil(Math.sqrt(values.length))));const step=min===max?1:(max-min)/n,edges=Array.from({length:n+1},(_,i)=>min+i*step),counts=Array(n).fill(0);for(const value of values)counts[Math.min(n-1,Math.max(0,Math.floor((value-min)/step)))]++;return {edges,counts,labels:counts.map((_,i)=>`${Number(edges[i].toPrecision(4))}〜${Number(edges[i+1].toPrecision(4))}`)};}
export function hierarchy(table:TableData){const model=chartData(table),roots:any[]=[];const numericCols=table.headers.map((_,c)=>c).filter(c=>table.rows.some(r=>numeric(r[c]||'')!==null)&&table.rows.every(r=>!r[c]?.trim()||numeric(r[c])!==null));const labelCols=table.headers.map((_,c)=>c).filter(c=>!numericCols.includes(c));table.rows.forEach((row,r)=>{const labels=labelCols.flatMap(c=>(row[c]||'').split(/[/>]/)).filter(Boolean);if(!labels.length)labels.push(model.labels[r]);let children=roots;for(let i=0;i<labels.length;i++){let node=children.find(n=>n.name===labels[i]);if(!node){node={name:labels[i],children:[]};children.push(node);}if(i===labels.length-1)node.value=(node.value||0)+Math.max(0,model.series[0]?.values[r]||0);children=node.children;}});const clean=(nodes:any[])=>nodes.forEach(n=>{if(n.children.length){clean(n.children);if(n.value)n.children.push({name:n.name+'（直属）',value:n.value});delete n.value;}else delete n.children;});clean(roots);return roots;}
export function buildChartOption(table:TableData,type:string,settings:ChartSettings,theme:string,compact=false):any {
  const model=chartData(table),kind=chartKind(type),dark=theme==='dark',colors=COLOR_SETS[settings.palette||'fluent'].colors,text=dark?'#dedede':'#424242';
  const labelSettings=settings[kind.horizontal?'y':'x'].labels,nameSettings=settings[kind.horizontal?'x':'y'].labels;
  const labels=labelSettings?.length===model.labels.length?labelSettings:model.labels,names=nameSettings?.length===model.series.length?nameSettings:model.series.map(s=>s.label),series=model.series.map((s,i)=>({...s,label:names[i]??s.label}));
  const base:any={backgroundColor:dark?'#292929':'#ffffff',color:colors,animation:false,textStyle:{color:text,fontFamily:'Segoe UI, Yu Gothic UI, sans-serif',fontSize:compact?8:10},tooltip:{trigger:'item',confine:true,className:'chart-tooltip',backgroundColor:dark?'#292929':'#ffffff',borderColor:dark?'#777':'#ccc',textStyle:{color:text}},legend:{bottom:2,textStyle:{color:text,fontSize:compact?8:10},pageTextStyle:{color:text},pageIconColor:text,pageIconInactiveColor:dark?'#777':'#aaa',itemWidth:10,itemHeight:8},grid:{left:settings.y.title?(compact?80:100):(compact?40:70),right:25,top:20,bottom:compact?42:58},series:[]};
  const axis=(a:Axis,category:boolean,data:string[]=labels)=>{const v=settings[a];return {type:category?'category':'value',data:category?data:undefined,name:v.title,nameLocation:'middle',nameGap:a==='x'?26:(compact?65:85),nameTextStyle:{color:text,fontSize:compact?9:11},axisLabel:{color:text,fontSize:compact?8:10,hideOverlap:true,formatter:category?undefined:v.digits==='auto'?undefined:(value:number)=>new Intl.NumberFormat('ja-JP',{minimumFractionDigits:Number(v.digits),maximumFractionDigits:Number(v.digits)}).format(value)},axisLine:{lineStyle:{color:dark?'#777':'#aaa'}},splitLine:{show:!category,lineStyle:{color:dark?'#ffffff15':'#0000000c'}},min:!category&&v.min.trim()?numeric(v.min):undefined,max:!category&&v.max.trim()?numeric(v.max):undefined};};
  const message=(content:string)=>({...base,legend:{show:false},graphic:[{type:'text',left:'center',top:'middle',style:{text:content,fill:text,fontSize:12,textAlign:'center',lineHeight:20}}]});
  if(!series.length)return message('数値データを選択してください。');
  const positive=series[0].values.map((v,i)=>({name:labels[i],value:Math.max(0,v||0)}));
  if(type.startsWith('pie')||type.startsWith('doughnut')||type==='bar-of-pie'){
    base.legend={...base.legend,type:'scroll'};
    if(type==='pie-of-pie'||type==='bar-of-pie'){
      const split=Math.max(1,Math.min(3,positive.length-1)),small=positive.slice(-split),large=[...positive.slice(0,-split),{name:'その他（補助図）',value:small.reduce((s,v)=>s+v.value,0)}];
      base.series=[{type:'pie',radius:'65%',center:['28%','43%'],data:large,label:{color:text,fontSize:10}},type==='pie-of-pie'?{type:'pie',radius:'40%',center:['77%','43%'],data:small,label:{color:text,fontSize:10}}:{type:'bar',data:small.map(v=>v.value)}];
      if(type==='bar-of-pie'){base.grid={left:'60%',right:'6%',top:'15%',bottom:'23%'};base.xAxis=axis('x',true,small.map(v=>v.name));base.yAxis=axis('y',false);}
      return base;
    }
    if(kind.depth){const total=positive.reduce((s,p)=>s+p.value,0)||1;let start=-Math.PI/2;const slices=positive.map(p=>{const item={...p,start,end:start+p.value/total*Math.PI*2};start=item.end;return item;});base.series=[{type:'custom',coordinateSystem:'none',data:slices.map(p=>p.value),renderItem:(params:any,api:any)=>{const p=slices[params.dataIndex],rx=params.coordSys?.width?params.coordSys.width*.3:api.getWidth()*.32,ry=Math.min(api.getHeight()*.28,rx*.48),cx=api.getWidth()/2,cy=api.getHeight()*.43,explode=type.includes('exploded')?10:0,dx=Math.cos((p.start+p.end)/2)*explode,dy=Math.sin((p.start+p.end)/2)*explode;const arc=Array.from({length:Math.max(3,Math.ceil((p.end-p.start)*18))+1},(_,i)=>{const a=p.start+(p.end-p.start)*i/Math.max(3,Math.ceil((p.end-p.start)*18));return [cx+dx+Math.cos(a)*rx,cy+dy+Math.sin(a)*ry];});const front=arc.filter(v=>v[1]>=cy+dy);return {type:'group',children:[...(front.length>1?[{type:'polygon',shape:{points:[...front,...[...front].reverse().map(v=>[v[0],v[1]+14])]},style:{fill:colors[params.dataIndex%colors.length],stroke:dark?'#333':'#fff',opacity:.65}}]:[]),{type:'polygon',shape:{points:[[cx+dx,cy+dy],...arc]},style:{fill:colors[params.dataIndex%colors.length],stroke:dark?'#292929':'#fff'}},{type:'text',style:{text:p.name,x:cx+dx+Math.cos((p.start+p.end)/2)*rx*.72,y:cy+dy+Math.sin((p.start+p.end)/2)*ry*.72,fill:text,stroke:base.backgroundColor,lineWidth:2,fontSize:9}}]};}}];return base;}
    base.series=[{type:'pie',radius:type.startsWith('doughnut')?['42%','68%']:'68%',center:['50%','43%'],data:positive,selectedMode:type.includes('exploded')?'multiple':'single',selectedOffset:15,label:{color:text,fontSize:compact?8:10},itemStyle:{borderWidth:1,borderColor:dark?'#292929':'#fff'},...(type.includes('exploded')?{data:positive.map(v=>({...v,selected:true}))}:{})}];return base;
  }
  if(type==='treemap'||type==='sunburst'){base.legend={show:false};base.series=[{type,data:hierarchy(table),radius:type==='sunburst'?[0,'85%']:undefined,top:15,bottom:15,left:5,right:5,label:{color:text,fontSize:10,textBorderColor:base.backgroundColor,textBorderWidth:2},roam:false,nodeClick:false,breadcrumb:{show:false},levels:type==='treemap'?[{itemStyle:{borderWidth:2,gapWidth:2}}]:undefined}];return base;}
  if(type==='map'){base.legend={show:false};base.visualMap={min:Math.min(0,...positive.map(v=>v.value)),max:Math.max(1,...positive.map(v=>v.value)),left:5,bottom:5,inRange:{color:[colors.at(-1),colors[0]]},textStyle:{color:text}};base.series=[{type:'map',map:'world',roam:true,data:positive.map(v=>({...v,name:countryName(v.name)})),label:{show:false},emphasis:{label:{show:true,color:text,backgroundColor:base.backgroundColor,padding:[2,3]}},itemStyle:{areaColor:dark?'#444':'#e4e8ed',borderColor:dark?'#777':'#fff'}}];return base;}
  if(type.startsWith('radar')){const max=Math.max(1,...series.flatMap(s=>s.values.map(v=>v||0)));base.radar={indicator:labels.map(name=>({name,max})),radius:'62%',center:['50%','43%'],axisName:{color:text,fontSize:10},splitArea:{areaStyle:{color:dark?['#333','#292929']:['#f4f6f8','#fff']}}};base.series=[{type:'radar',symbol:type==='radar'?'none':'circle',areaStyle:type==='radar-filled'?{opacity:.3}:undefined,data:series.map(s=>({name:s.label,value:s.values.map(v=>v||0)}))}];return base;}
  if(type==='funnel'){base.series=[{type:'funnel',top:10,bottom:38,left:'15%',width:'70%',sort:'descending',gap:2,data:positive,label:{color:text,fontSize:10}}];return base;}
  if(type.startsWith('surface')){
    if(series.length<2||labels.length<2)return message('サーフェスには2行×2列以上の数値行列が必要です。');
    const cells=labels.flatMap((_,r)=>series.map((s,c)=>[r,c,s.values[r]]).filter(v=>v[2]!==null)),all=cells.map(v=>v[2] as number),min=Math.min(...all),max=Math.max(...all),span=max-min||1;
    const color=(v:number)=>colors[Math.min(colors.length-1,Math.floor((v-min)/span*(colors.length-1)))];
    if(kind.depth){base.legend={show:false};const mesh:any[]=[];for(let r=0;r<labels.length-1;r++)for(let c=0;c<series.length-1;c++){const z=[series[c].values[r],series[c].values[r+1],series[c+1].values[r+1],series[c+1].values[r]];if(z.every(v=>v!==null))mesh.push([r,c,...z]);}mesh.sort((a,b)=>(a[0]+a[1])-(b[0]+b[1]));base.series=[{type:'custom',coordinateSystem:'none',data:mesh,renderItem:(params:any,api:any)=>{const d=mesh[params.dataIndex],w=api.getWidth(),h=api.getHeight(),step=Math.min(w/(labels.length+series.length+2),h*1.1/(labels.length+series.length+2));const project=(r:number,c:number,z:number)=>[w/2+(r-c)*step,h*.32+(r+c)*step*.35-(z-min)/span*h*.24];return {type:'polygon',shape:{points:[project(d[0],d[1],d[2]),project(d[0]+1,d[1],d[3]),project(d[0]+1,d[1]+1,d[4]),project(d[0],d[1]+1,d[5])]},style:{fill:type==='surface-wireframe'?'transparent':color((d[2]+d[3]+d[4]+d[5])/4),stroke:type==='surface-wireframe'?colors[0]:dark?'#999':'#fff',lineWidth:1}};}}];return base;}
    base.xAxis=axis('x',true);base.yAxis=axis('y',true,names);base.legend={show:false};base.visualMap={min,max,left:0,bottom:0,inRange:{color:colors},textStyle:{color:text}};
    const contours:any[]=[];for(let level=1;level<9;level++){const z=min+span*level/9;for(let r=0;r<labels.length-1;r++)for(let c=0;c<series.length-1;c++){const points=[[r,c,series[c].values[r]],[r+1,c,series[c].values[r+1]],[r+1,c+1,series[c+1].values[r+1]],[r,c+1,series[c+1].values[r]]];const intersections:number[][]=[];for(let k=0;k<4;k++){const a=points[k],b=points[(k+1)%4];if(a[2]===null||b[2]===null||a[2]===b[2])continue;if(((a[2] as number)<=z&&z<(b[2] as number))||((b[2] as number)<=z&&z<(a[2] as number))){const t=(z-(a[2] as number))/((b[2] as number)-(a[2] as number));intersections.push([(a[0] as number)+t*((b[0] as number)-(a[0] as number)),(a[1] as number)+t*((b[1] as number)-(a[1] as number))]);}}for(let k=0;k+1<intersections.length;k+=2)contours.push([...intersections[k],...intersections[k+1],z]);}}
    base.series=[...(type==='surface-contour'?[{type:'heatmap',data:cells,label:{show:false}}]:[]),{type:'custom',data:contours,renderItem:(_:any,api:any)=>{const a=api.coord([api.value(0),api.value(1)]),b=api.coord([api.value(2),api.value(3)]);return {type:'line',shape:{x1:a[0],y1:a[1],x2:b[0],y2:b[1]},style:{stroke:text,lineWidth:1}};}}];return base;
  }
  const xy=type.startsWith('scatter')||type.startsWith('bubble');
  base.xAxis=axis('x',!xy&&!kind.horizontal);base.yAxis=axis('y',!!kind.horizontal,labels);
  if(xy){if(series.length<2)return message('XとYの2つの数値列が必要です。');if(type.startsWith('bubble')&&series.length<3)return message('X・Y・大きさの3つの数値列が必要です。');const bubble=type.startsWith('bubble'),points=series.slice(1,bubble?2:undefined).map((s,i)=>({name:s.label,type:bubble||type==='scatter'?'scatter':'line',smooth:kind.smooth,symbolSize:bubble?(v:number[])=>Math.max(4,Math.min(70,Math.sqrt(Math.abs(v[2]))*4)):kind.markers?6:0,lineStyle:{width:2},itemStyle:kind.depth?{shadowBlur:8,shadowColor:'#0005'}:undefined,data:s.values.map((v,r)=>[series[0].values[r],v,bubble?series[2].values[r]:undefined]).filter(v=>v[0]!==null&&v[1]!==null)}));base.xAxis.name=settings.x.title||series[0].label;base.yAxis.name=settings.y.title||series[1].label;base.series=points;return base;}
  if(type==='histogram'){const bins=histogram(series[0].values.filter((v):v is number=>v!==null));base.xAxis=axis('x',true,bins.labels);base.yAxis.name=settings.y.title||'度数';base.series=[{name:series[0].label,type:'bar',barGap:'0%',barCategoryGap:'0%',data:bins.counts}];return base;}
  if(type==='boxplot'){const outliers:any[]=[];base.xAxis=axis('x',true,names);base.series=[{name:'箱ひげ',type:'boxplot',data:series.map((s,i)=>{const values=s.values.filter((v):v is number=>v!==null).sort((a,b)=>a-b);const q1=quantile(values,.25),median=quantile(values,.5),q3=quantile(values,.75),iqr=q3-q1,inside=values.filter(v=>v>=q1-1.5*iqr&&v<=q3+1.5*iqr);values.filter(v=>v<q1-1.5*iqr||v>q3+1.5*iqr).forEach(v=>outliers.push([i,v]));return [inside[0]??values[0],q1,median,q3,inside.at(-1)??values.at(-1)];})},{name:'外れ値',type:'scatter',data:outliers,symbolSize:5}];return base;}
  if(type==='pareto'){const sorted=positive.sort((a,b)=>b.value-a.value),total=sorted.reduce((s,v)=>s+v.value,0)||1;let sum=0;base.xAxis=axis('x',true,sorted.map(v=>v.name));base.yAxis=[axis('y',false),{...axis('y',false),min:0,max:100,name:'累積割合 (%)',position:'right'}];base.grid.right=55;base.series=[{name:series[0].label,type:'bar',data:sorted.map(v=>v.value)},{name:'累積割合',type:'line',yAxisIndex:1,data:sorted.map(v=>{sum+=v.value;return sum/total*100;})}];return base;}
  if(type==='waterfall'){let sum=0;const bars:any[]=[];series[0].values.forEach((v,r)=>{if(v===null)return;const total=/total|合計|総計|残高/i.test(labels[r]);const end=total?v:sum+v,start=total?0:sum;bars.push([r,start,end]);sum=end;});base.series=[{name:series[0].label,type:'custom',encode:{x:0,y:[1,2]},data:bars,renderItem:(_:any,api:any)=>{const index=api.value(0),start=api.coord([index,api.value(1)]),end=api.coord([index,api.value(2)]),width=api.size([1,0])[0]*.6;return {type:'rect',shape:{x:start[0]-width/2,y:Math.min(start[1],end[1]),width,height:Math.max(1,Math.abs(start[1]-end[1]))},style:{fill:colors[api.value(2)>=api.value(1)?0:1]}};}}];return base;}
  if(type.startsWith('stock')){const hasOpen=type.includes('ohlc'),volume=type.includes('volume'),required=(hasOpen?4:3)+(volume?1:0);if(series.length<required)return message(`${kind.name}には${required}つの数値列が必要です。`);const choose=(pattern:RegExp,fallback:number)=>{const index=series.findIndex(s=>pattern.test(s.label));return series[index<0?fallback:index];};const offset=volume?1:0,open=choose(/始値|open/i,offset),high=choose(/高値|high/i,offset+(hasOpen?1:0)),low=choose(/安値|low/i,offset+(hasOpen?2:1)),close=choose(/終値|close/i,offset+(hasOpen?3:2));const data=labels.map((_,r)=>[hasOpen?open.values[r]:close.values[r],close.values[r],low.values[r],high.values[r]]).map(v=>v.some(n=>n===null)?'-':v);base.series=[{name:'株価',type:'candlestick',data,itemStyle:{color:colors[0],color0:colors[1],borderColor:colors[0],borderColor0:colors[1]}}];if(volume){const vol=choose(/出来高|volume/i,0);base.grid=[{...base.grid,bottom:'37%'},{...base.grid,top:'72%',bottom:35}];base.xAxis=[{...base.xAxis,axisLabel:{show:false}},{...base.xAxis,gridIndex:1}];base.yAxis=[base.yAxis,{...axis('y',false),gridIndex:1,name:'出来高'}];base.series.push({name:vol.label,type:'bar',xAxisIndex:1,yAxisIndex:1,data:vol.values});}return base;}
  const percentValues=series.map(s=>s.values.map((v,r)=>{if(v===null)return null;const sum=series.reduce((n,other)=>n+Math.abs(other.values[r]||0),0);return sum?v/sum*100:0;}));
  const basicType=kind.family==='折れ線'||kind.family==='面'?'line':'bar';
  if(kind.horizontal){base.xAxis=axis('x',false);base.yAxis=axis('y',true,labels);}
  base.series=series.map((s,i)=>({name:s.label,type:basicType,stack:kind.stacked?'total':undefined,data:kind.percent?percentValues[i]:s.values,symbol:kind.markers?'circle':'none',symbolSize:4,smooth:false,lineStyle:kind.depth?{width:5,shadowBlur:4,shadowColor:colors[i%colors.length],shadowOffsetX:5,shadowOffsetY:5}:{width:2},areaStyle:kind.family==='面'?{opacity:kind.depth?.5:.3}:undefined,itemStyle:kind.depth?{shadowColor:'#0004',shadowBlur:3,shadowOffsetX:4,shadowOffsetY:-4}:undefined}));
  if(kind.depth&&basicType==='line'){
    const depth=Math.min(9,50/Math.max(series.length,1));base.grid.top=25+depth*series.length;base.grid.right=30+depth*series.length;
    base.series=series.map((s,i)=>({name:s.label,type:'custom',encode:{x:0,y:[1,2]},data:s.values.flatMap((v,r)=>{if(v===null)return [];const value=kind.percent?percentValues[i][r]||0:v,prior=kind.stacked?series.slice(0,i).reduce((n,_,j)=>n+(kind.percent?percentValues[j][r]||0:series[j].values[r]||0),0):0;return [[r,prior,prior+value]];}),renderItem:(_:any,api:any)=>{
      const r=Number(api.value(0));if(r===0||s.values[r-1]===null)return;const previous=kind.percent?percentValues[i][r-1]||0:s.values[r-1]||0,prior=kind.stacked?series.slice(0,i).reduce((n,_,j)=>n+(kind.percent?percentValues[j][r-1]||0:series[j].values[r-1]||0),0):0;
      const project=(x:number,y:number)=>{const p=api.coord([x,y]);return [p[0]+i*depth,p[1]-i*depth];},a=project(r-1,prior+previous),b=project(r,Number(api.value(2))),d=depth*.7,color=colors[i%colors.length],children:any[]=[];
      if(kind.family==='面'){children.push({type:'polygon',shape:{points:[project(r-1,prior),a,b,project(r,Number(api.value(1)))]},style:{fill:color,opacity:.55}});}
      children.push({type:'polygon',shape:{points:[a,b,[b[0]+d,b[1]-d],[a[0]+d,a[1]-d]]},style:{fill:color,opacity:.8}},{type:'line',shape:{x1:a[0],y1:a[1],x2:b[0],y2:b[1]},style:{stroke:color,lineWidth:2}});return {type:'group',children};
    }}));
  }
  if(kind.depth&&basicType==='bar'){
    const horizontal=!!kind.horizontal,count=series.length;
    base.series=series.map((s,i)=>({name:s.label,type:'custom',encode:horizontal?{x:[1,2],y:0}:{x:0,y:[1,2]},stack:kind.stacked?'total':undefined,data:s.values.map((v,r)=>{const val=(kind.percent?percentValues[i][r]:v)||0,prior=kind.stacked?series.slice(0,i).reduce((sum,_,j)=>sum+(kind.percent?percentValues[j][r]||0:series[j].values[r]||0),0):0;return [r,prior,prior+val];}),renderItem:(_:any,api:any)=>{const index=api.value(0),start=api.coord(horizontal?[api.value(1),index]:[index,api.value(1)]),end=api.coord(horizontal?[api.value(2),index]:[index,api.value(2)]),band=(horizontal?api.size([0,1])[1]:api.size([1,0])[0])*.72/(kind.stacked?1:count),offset=kind.stacked?0:(i-(count-1)/2)*band;const x=horizontal?Math.min(start[0],end[0]):start[0]+offset-band/2,y=horizontal?start[1]+offset-band/2:Math.min(start[1],end[1]),w=horizontal?Math.max(1,Math.abs(start[0]-end[0])):band*.85,h=horizontal?band*.85:Math.max(1,Math.abs(start[1]-end[1])),d=Math.min(9,band*.3),color=colors[i%colors.length];const body=kind.shape==='cone'||kind.shape==='pyramid'?{type:'polygon',shape:{points:horizontal?[[x,y],[x+w,y+h/2],[x,y+h]]:[[x,y+h],[x+w/2,y],[x+w,y+h]]},style:{fill:color}}:{type:'rect',shape:{x,y,width:w,height:h,r:kind.shape==='cylinder'?[w/2,w/2,0,0]:0},style:{fill:color}};return {type:'group',children:[body,{type:'polygon',shape:{points:[[x+w,y],[x+w+d,y-d],[x+w+d,y+h-d],[x+w,y+h]]},style:{fill:color,opacity:.6}},{type:'polygon',shape:{points:[[x,y],[x+d,y-d],[x+w+d,y-d],[x+w,y]]},style:{fill:color,opacity:.8}}]};}}));
  }
  if(type.startsWith('combo')){base.series=series.map((s,i)=>({name:s.label,type:type==='combo-stacked'&&i>0?'line':i===series.length-1?'line':'bar',stack:type==='combo-stacked'&&i>0?'area':undefined,areaStyle:type==='combo-stacked'&&i>0?{opacity:.3}:undefined,data:s.values,yAxisIndex:type==='combo-secondary'&&i===series.length-1?1:0}));if(type==='combo-secondary'){base.yAxis=[base.yAxis,{...axis('y',false),name:series.at(-1)!.label,position:'right',nameGap:30}];base.grid.right=65;}}
  return base;
}
