import React, { useEffect, useMemo, useRef, useState } from 'react';
import MarkdownIt from 'markdown-it';
import DOMPurify from 'dompurify';
import { createPortal } from 'react-dom';
import { EditableChart } from './editable-chart';
import type { ChartSettings } from './chart-settings';
import { X, ExternalLink, Download, Plus, ArrowUp, ArrowDown, Combine, BarChart3, Undo2, MoreHorizontal, Pencil, Trash2, FileText, Code, Eye } from 'lucide-react';
import { chartData, mergeTables, blockMarkdown, documentMarkdown, type TableData, type MergeBlock } from './data';
export type Position = 'top' | 'bottom' | 'left' | 'right';
export function DockPane({ title, tools, position, onPosition, onClose, children }: { title: string; tools?:React.ReactNode; position: Position; onPosition(p: Position): void; onClose():void; children: React.ReactNode }) {
  const [popup, setPopup] = useState<Window | null>(null), [mount, setMount] = useState<HTMLElement | null>(null);
  const restore = () => { popup?.close(); setPopup(null); setMount(null); };
  function popOut() {
    const child = window.open('about:blank', '_blank', 'width=900,height=550'); if (!child) return;
    child.document.title = title + ' — CSV nyaan Viewer';
    document.querySelectorAll('link[rel=stylesheet],style').forEach(node => child.document.head.appendChild(node.cloneNode(true)));
    child.document.documentElement.dataset.theme = document.documentElement.dataset.theme;
    child.document.documentElement.style.cssText = document.documentElement.style.cssText;
    const root = child.document.createElement('div'); root.className='popout-root'; child.document.body.appendChild(root); setPopup(child); setMount(root);
    child.addEventListener('beforeunload', () => { setPopup(null); setMount(null); });
  }
  useEffect(() => { if (!popup) return; const observer = new MutationObserver(() => { popup.document.documentElement.dataset.theme=document.documentElement.dataset.theme; popup.document.documentElement.style.cssText=document.documentElement.style.cssText; }); observer.observe(document.documentElement,{attributes:true}); return () => observer.disconnect(); },[popup]);
  useEffect(() => () => { popup?.close(); }, [popup]);
  const content = <section className="dock-pane"><header className="pane-heading"><strong>{title}</strong>{tools}<select aria-label={`${title}の位置`} value={position} onChange={e => onPosition(e.target.value as Position)}>{[['bottom','下'],['top','上'],['left','左'],['right','右']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{popup ? <button className="icon-btn" title="メインウィンドウに戻す" aria-label="メインウィンドウに戻す" onClick={restore}><Undo2 size={14}/></button> : <button className="icon-btn" title="別ウィンドウにする" aria-label={`${title}を別ウィンドウにする`} onClick={popOut}><ExternalLink size={14}/></button>}<button className="icon-btn" title="ペインを閉じる" aria-label={`${title}を閉じる`} onClick={() => { restore();onClose(); }}><X size={15}/></button></header>{children}</section>;
  return mount ? <><div className="popout-placeholder"><ExternalLink size={17}/><span>{title}は別ウィンドウに表示中</span><button onClick={restore}>戻す</button></div>{createPortal(content,mount)}</> : content;
}
export function Dashboard({ type,setType,settings,onSettingsChange,table,theme,onSaveRef,onCaptureRef,onExport,onError }: { type:string;setType(value:string):void;settings:ChartSettings;onSettingsChange(settings:ChartSettings):void;table:TableData|null;theme:string;onSaveRef:React.MutableRefObject<(()=>void)|null>;onCaptureRef:React.MutableRefObject<(()=>string|null)|null>;onExport():void;onError(message:string):void }) {
  const [context,setContext]=useState<{x:number;y:number}|null>(null);
  const chartHandle=useRef<{png():string|null}|null>(null);
  const model=useMemo(()=>table?chartData(table):{labels:[],series:[],precisionWarning:false},[table]);
  async function save(){try{const image=chartHandle.current?.png();if(image)await window.csv.saveChart(image,'png');}catch(e){onError(String(e));}}
  onSaveRef.current=save;onCaptureRef.current=()=>chartHandle.current?.png()||null;
  return <><div className="pane-toolbar"><BarChart3 size={15}/><select aria-label="グラフ種類" value={type} onChange={e=>setType(e.target.value)}>{[['bar','棒グラフ'],['line','折れ線'],['area','面グラフ'],['pie','円グラフ'],['doughnut','ドーナツ'],['scatter','散布図（横軸：行番号）']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><span>{table?.rows.length||0}行</span><button onClick={save} disabled={!model.series.length}><Download size={14}/>PNG保存</button><button onClick={onExport} disabled={!table}><FileMd/>選択を.md出力</button></div><div className="chart-area" onContextMenu={e=>{e.preventDefault();setContext({x:e.clientX,y:e.clientY});}}>{model.series.length&&table?<EditableChart table={table} type={type} settings={settings} onSettingsChange={onSettingsChange} theme={theme} handleRef={chartHandle}/>:<div className="pane-empty"><BarChart3 size={28}/><p>数値を含む範囲を選択すると<br/>グラフがここに表示されます。</p></div>}</div>{table?.inferred?.length?<div className="pane-note" title={table.inferred.join('\n')}>見出しを推定：{table.inferred.join(' / ')}</div>:null}{(table?.truncated||model.precisionWarning||['pie','doughnut'].includes(type))&&<div className="pane-note">{table?.truncated?'選択範囲の先頭部分をプレビューしています。 ':''}{model.precisionWarning?'グラフ上の値は浮動小数点で近似されます。元の文字列は保持されます。 ':''}{['pie','doughnut'].includes(type)?'円グラフは先頭の数値列を表示します。負数は棒グラフなどで確認してください。':''}</div>}{context&&<div className="chart-context" style={{left:context.x,top:context.y}} onMouseLeave={()=>setContext(null)}><button onClick={()=>{save();setContext(null);}}><Download size={14}/>画像として保存（PNG）</button></div>}</>;
}
function FileMd(){return <span className="md-icon">M↓</span>;}
const docMarkdown=new MarkdownIt({html:false,linkify:false});
docMarkdown.renderer.rules.image=(tokens,i)=>{const src=tokens[i].attrGet('src')||'';return /^data:image\/png;base64,/.test(src)?'<img alt="'+docMarkdown.utils.escapeHtml(tokens[i].content)+'" src="'+src+'">':'<span>[画像: '+docMarkdown.utils.escapeHtml(tokens[i].content)+']</span>';};
docMarkdown.renderer.rules.link_open=()=>'<span class="md-link">';docMarkdown.renderer.rules.link_close=()=>'</span>';
export function MergePanel({theme,view,direction,setDirection,align,setAlign,format,setFormat,blocks,setBlocks,onAdd,onAddFile,onAddText,onAddChart,onExport,onExportDocument,onShareDocument,onShare}:{theme:string;view:'preview'|'source';direction:'rows'|'columns';setDirection(v:'rows'|'columns'):void;align:boolean;setAlign(v:boolean):void;format:string;setFormat(v:string):void;blocks:MergeBlock[];setBlocks:React.Dispatch<React.SetStateAction<MergeBlock[]>>;onAdd():void;onAddFile():void;onAddText():void;onAddChart():void;onExport(table:TableData,format:string):void;onExportDocument():void;onShareDocument():void;onShare(table:TableData):void}){
  const [editing,setEditing]=useState(''),[draft,setDraft]=useState(''),[menu,setMenu]=useState('');
  const tableBlocks=blocks.filter(b=>!b.kind||b.kind==='table');const merged=useMemo(()=>mergeTables(tableBlocks,direction,align),[blocks,direction,align]);
  function move(i:number,delta:number){setBlocks(all=>{const next=[...all],j=i+delta;if(j<0||j>=next.length)return all;[next[i],next[j]]=[next[j],next[i]];return next;});}
  function edit(block:MergeBlock){setEditing(block.id);setDraft(block.kind==='chart'?block.name:blockMarkdown(block));setMenu('');}
  function saveEdit(block:MergeBlock){const doc=new DOMParser().parseFromString(DOMPurify.sanitize(docMarkdown.render(draft)),'text/html');const htmlTable=doc.querySelector('table');const parsed=htmlTable?{headers:Array.from(htmlTable.rows[0]?.cells||[]).map(c=>c.textContent||''),rows:Array.from(htmlTable.rows).slice(1).map(r=>Array.from(r.cells).map(c=>c.textContent||''))}:null;setBlocks(all=>all.map(b=>b.id===block.id?block.kind==='chart'?{...b,name:draft}:block.kind==='table'||!block.kind?{...b,content:draft,kind:parsed?'table':'text',table:parsed||{headers:[],rows:[]}}:{...b,content:draft}:b));setEditing('');}
  return <><div className="pane-toolbar document-tools"><button onClick={onAdd}><Plus size={14}/>選択</button><button onClick={onAddFile}><Plus size={14}/>ファイル</button><button aria-label="テキストブロックを追加" onClick={onAddText}><FileText size={14}/>テキスト</button><button aria-label="グラフブロックを追加" onClick={onAddChart}><BarChart3 size={14}/>グラフ</button></div>
  <div className="merge-scroll document-scroll">{view==='source'?<textarea className="document-source" aria-label="結合文書のMarkdown原文" readOnly value={documentMarkdown(blocks)}/>:blocks.length?blocks.map((b,i)=><section className="merge-block document-block" key={b.id} data-block-id={b.id}>
    <div className="block-actions-wrap"><button className="block-more icon-btn" aria-label={`${b.name}のブロックオプション`} title="ブロックの編集・削除" onClick={()=>setMenu(menu===b.id?'':b.id)}><MoreHorizontal size={17}/></button><div className={'block-actions '+(menu===b.id?'visible':'')}><button className="icon-btn" title="編集" aria-label={`${b.name}を編集`} onClick={()=>edit(b)}><Pencil size={14}/></button><button className="icon-btn danger" title="削除" aria-label={`${b.name}を削除`} onClick={()=>setBlocks(all=>all.filter(v=>v.id!==b.id))}><Trash2 size={14}/></button></div></div>
    <div className="block-label"><span>{b.kind==='chart'?'グラフ':b.kind==='text'?'テキスト':'表'}</span><small title={b.name}>{b.name}</small></div>
    {editing===b.id?<div className="block-edit"><textarea aria-label="ブロックの編集内容" value={draft} onChange={e=>setDraft(e.target.value)} autoFocus/><div><button onClick={()=>setEditing('')}>キャンセル</button><button className="primary" onClick={()=>saveEdit(b)}>保存</button></div></div>:b.kind==='chart'?<figure className="document-chart">{b.chart?<EditableChart compact table={b.chart.table} type={b.chart.type} settings={b.chart.settings} theme={theme} onSettingsChange={settings=>setBlocks(all=>all.map(block=>block.id===b.id&&block.chart?{...block,chart:{...block.chart,settings}}:block))} onImage={image=>setBlocks(all=>{const block=all.find(block=>block.id===b.id);return block?.image===image?all:all.map(block=>block.id===b.id?{...block,image}:block);})}/>:<img src={b.image} alt={b.name} className="direct-edit-target" tabIndex={0} title="クリックしてグラフの説明を編集" onClick={()=>edit(b)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();edit(b);}}}/>}<figcaption className="direct-edit-target" tabIndex={0} title="クリックして説明を編集" onClick={()=>edit(b)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();edit(b);}}}>{b.name}</figcaption></figure>:<div className="block-markdown direct-edit-target" tabIndex={0} role="button" aria-label={`${b.name}を直接編集`} title="クリックしてブロックを編集" onClick={()=>edit(b)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();edit(b);}}} dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(docMarkdown.render(blockMarkdown(b)))}}/>}
    <footer className="block-footer"><span>{b.kind==='chart'?'PNG':b.kind==='text'?'Markdown':b.table.rows.length.toLocaleString()+'行 × '+b.table.headers.length+'列'}</span><button title="上に移動" disabled={!i} onClick={()=>move(i,-1)}><ArrowUp size={12}/></button><button title="下に移動" disabled={i===blocks.length-1} onClick={()=>move(i,1)}><ArrowDown size={12}/></button></footer>
  </section>):<div className="pane-empty"><Combine size={28}/><p>テキスト・表・グラフを追加して<br/>Markdown文書としてまとめます。</p></div>}</div>
  <div className="document-export"><span>{blocks.length}ブロック</span><button className="primary" disabled={!blocks.length} onClick={onExportDocument}><Download size={14}/>.mdを保存</button><button disabled={!blocks.length} onClick={onShareDocument}>共有</button></div>
  {tableBlocks.length>0&&<details className="table-merge-details"><summary>表をまとめて結合・出力</summary><div className="merge-options"><select aria-label="結合方向" value={direction} onChange={e=>setDirection(e.target.value as 'rows'|'columns')}><option value="rows">縦に結合（行を追加）</option><option value="columns">横に結合（列を追加）</option></select>{direction==='rows'&&<label><input type="checkbox" checked={align} onChange={e=>setAlign(e.target.checked)}/>同じ見出しで列を合わせる</label>}</div><div className="merge-summary">結合結果：{merged.rows.length.toLocaleString()}行 × {merged.headers.length}列</div><div className="merge-export"><select aria-label="結合の出力形式" value={format} onChange={e=>setFormat(e.target.value)}>{['csv','tsv','md','txt'].map(f=><option key={f} value={f}>{f.toUpperCase()}</option>)}</select><button className="primary" disabled={!blocks.length} onClick={()=>onExport(merged,format)}><Download size={14}/>出力</button><button disabled={!blocks.length} onClick={()=>onShare(merged)}>共有</button></div></details>}
  </>;
}
