import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Download,Play,Pause} from 'lucide-react';
import {AnalysisChart} from './analysis-chart';
import {categoryName,choiceName,initialAxes,objText,pcaPlot,plotFilename,plotPNG,rotate,seriesCorrelations,type AxisChoices,type Orientation,type PlotModel} from './analysis-plot';
import {rotatingGIF} from './analysis-gif';
import {formatNumber as fmt,type PrincipalComponents} from './analysis-types';
export interface PcaViewState {model:PlotModel;orientation:Orientation;angle:number;paragraphs:string[]}
function DirectionWheel({value,angle,onChange}:{value:Orientation;angle:number;onChange(v:Orientation):void}){
  const drag=useRef<{x:number;y:number;value:Orientation}|null>(null),vectors=[{x:1,y:0,z:0},{x:0,y:1,z:0},{x:0,y:0,z:1}].map(p=>rotate(p,value,angle));
  const presets=[['前',0,0],['後',180,0],['左',90,0],['右',-90,0],['上',0,-89],['下',0,89]] as const;
  return <div className="orientation-control"><svg className="direction-wheel" viewBox="0 0 120 120" role="slider" tabIndex={0} aria-label="3D方向ホイール" aria-valuemin={-180} aria-valuemax={180} aria-valuenow={Math.round(((value.yaw%360)+540)%360-180)} aria-valuetext={`水平${Math.round(value.yaw+angle)}度、垂直${Math.round(value.pitch)}度、傾き${Math.round(value.roll)}度`} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,value};}} onPointerMove={e=>{if(!drag.current)return;const start=drag.current;onChange({...start.value,...(e.shiftKey?{roll:start.value.roll+(e.clientX-start.x)*.8}:{yaw:start.value.yaw+(e.clientX-start.x)*.8,pitch:Math.max(-89,Math.min(89,start.value.pitch+(e.clientY-start.y)*.8))})});}} onPointerUp={e=>{drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={e=>{const step=e.shiftKey?15:5;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();onChange({...value,yaw:value.yaw+(e.key==='ArrowRight'?step:-step)});}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();onChange({...value,pitch:Math.max(-89,Math.min(89,value.pitch+(e.key==='ArrowDown'?step:-step)))});}if(e.key==='Home'){e.preventDefault();onChange({yaw:0,pitch:-20,roll:0});}}}><circle cx="60" cy="60" r="52" fill="var(--surface2)" stroke="var(--muted)"/><ellipse cx="60" cy="60" rx="52" ry="18" fill="none" stroke="var(--line)"/><ellipse cx="60" cy="60" rx="18" ry="52" fill="none" stroke="var(--line)"/>{vectors.map((v,i)=><g key={i}><line x1="60" y1="60" x2={60+v.x*38} y2={60-v.y*38} stroke={'var(--plot-'+(i+1)+')'} strokeWidth="3"/><circle cx={60+v.x*38} cy={60-v.y*38} r="10" fill="var(--bg)" stroke={'var(--plot-'+(i+1)+')'}/><text x={60+v.x*38} y={64-v.y*38} textAnchor="middle" fill="var(--text)" fontSize="11">{'XYZ'[i]}</text></g>)}</svg><div><small>ドラッグで向きを指定<br/>Shiftで傾きを調整</small><div className="view-presets">{presets.map(([label,yaw,pitch])=><button key={label} aria-label={'3Dを'+label+'から見る'} onClick={()=>onChange({yaw:yaw-angle,pitch,roll:0})}>{label}</button>)}</div></div></div>;
}
export function PcaView({pca,onState}:{pca:PrincipalComponents;onState(state:PcaViewState):void}){
  const [dimension,setDimension]=useState<2|3>(2),[axes,setAxes]=useState<AxisChoices>(()=>initialAxes(pca)),[orientation,setOrientation]=useState<Orientation>({yaw:0,pitch:-20,roll:0}),[angle,setAngle]=useState(30),[rotating,setRotating]=useState(false),[lines,setLines]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const model=useMemo(()=>pcaPlot(pca,axes,dimension,lines),[pca,axes,dimension,lines]);
  const correlations=seriesCorrelations(model),categories=axes.slice(0,dimension).flatMap((a,i)=>a.map(key=>'XYZ'[i]+' '+categoryName(pca,key))),paragraphs=[...categories,'表示：'+dimension+'D · 線で結ぶ：'+(lines?'有効':'無効'),...(dimension===3?[`方向：水平 ${orientation.yaw.toFixed(1)}° / 垂直 ${orientation.pitch.toFixed(1)}° / 傾き ${orientation.roll.toFixed(1)}° / 追加回転 ${angle.toFixed(1)}°`]:[]),...correlations.map(c=>`2系列の対応相関 ${c.axis}：r = ${fmt(c.r)}`)];
  useEffect(()=>{onState({model,orientation,angle,paragraphs});});
  useEffect(()=>{if(!rotating||dimension!==3)return;const timer=setInterval(()=>setAngle(a=>(a+1.5)%360),50);return()=>clearInterval(timer);},[rotating,dimension]);
  const choices=[...pca.loadings.map((_,i)=>'pc:'+i),...pca.dimensions.map((_,i)=>'column:'+i),'zero'];
  function choose(axis:number,item:number,key:string){setAxes(current=>{const next=current.map(a=>[...a]) as AxisChoices;if(!key)next[axis]=[next[axis][0]];else if(item===0){next[axis][0]=key;if(next[axis][1]===key)next[axis].pop();}else if(next[axis][0]!==key){next[axis][1]=key;setLines(true);}return next;});}
  async function save(format:'png'|'gif'|'obj'){
    setError('');setBusy(format);setRotating(false);
    try{const data=format==='png'?plotPNG(model,orientation,angle):format==='obj'?objText(model):await rotatingGIF(model,orientation,angle,p=>setBusy('GIF '+p+'%'));await window.csv.savePlot(data,format,plotFilename(model));}catch(e){setError(String(e));}finally{setBusy('');}
  }
  return <section className="analysis-pca"><div className="analysis-dim"><strong>主成分の分布</strong><select aria-label="分析の次元" value={dimension} onChange={e=>{setDimension(Number(e.target.value) as 2|3);setRotating(false);}}><option value="2">2D</option><option value="3">3D</option></select></div><AnalysisChart model={model} orientation={orientation} angle={angle}/><div className="pca-categories">{categories.map((c,i)=><p key={i}>{c}</p>)}</div><details className="axis-choices"><summary>軸の項目を選択（各軸2項目まで）</summary>{axes.slice(0,dimension).map((axis,i)=><div key={i}><strong>{'XYZ'[i]}軸</strong>{[0,1].map(item=><select key={item} aria-label={'XYZ'[i]+'軸 項目'+(item+1)} value={axis[item]||''} onChange={e=>choose(i,item,e.target.value)}>{item===1&&<option value="">比較なし</option>}{choices.map(key=><option key={key} value={key}>{choiceName(pca,key)}</option>)}</select>)}</div>)}<label><input type="checkbox" checked={lines} onChange={e=>setLines(e.target.checked)}/>点を線で結ぶ</label><small>元データの列は平均0・標準偏差1に標準化して表示します。</small></details>{correlations.length>0&&<div className="series-correlations">{correlations.map(c=><p key={c.axis}>2系列の対応相関 {c.axis}：r = {fmt(c.r)}</p>)}</div>}{dimension===3&&<><DirectionWheel value={orientation} angle={angle} onChange={setOrientation}/><label className="rotation-control">回転<button className="icon-btn" aria-label={rotating?'自動回転を停止':'自動回転を開始'} aria-pressed={rotating} disabled={!!busy} onClick={()=>setRotating(v=>!v)}>{rotating?<Pause size={14}/>:<Play size={14}/>}</button><input aria-label="3D分析の回転" type="range" min="0" max="360" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label></>}<div className="analysis-downloads">{(dimension===2?['png']:['gif','obj']).map(format=><button key={format} disabled={!!busy} onClick={()=>save(format as 'png'|'gif'|'obj')}><Download size={13}/>{format==='png'?'PNG保存':'.'+format}</button>)}</div>{busy&&<p role="status">{busy}</p>}{error&&<p role="alert">{error}</p>}<p>寄与率：{pca.explained.map((v,i)=>'PC'+(i+1)+' '+(v*100).toFixed(1)+'%').join(' / ')}</p><p>完全な数値行 {pca.completeRows} · {pca.dimensions.length}変量</p>{pca.clusters.length>0&&<p>推定した群：{pca.clusters.map((n,i)=>'群'+(i+1)+' '+n+'件').join(' / ')}</p>}<details><summary>主成分の負荷量</summary>{pca.dimensions.map((name,i)=><p key={i}>{name}：{pca.loadings.map((v,c)=>'PC'+(c+1)+' '+fmt(v[i])).join(' / ')}</p>)}</details></section>;
}
