import React,{useEffect,useState} from 'react';
import {Github,Gamepad2,Hash,ExternalLink,Globe,LogOut,X,Share2} from 'lucide-react';
import type {TableData,MergeBlock} from './data';
import type {ConnectionStatus} from './sharing';
import './s-sharing.css';
export interface SService {id:string;name:string;provider:string;url:string;native?:boolean}
export interface SAccount {provider:string;label:string;connected:boolean;service?:string;confirmedAt?:string;avatar?:string}
export interface SOpenOptions {service:string;title?:string;recipient?:string;message?:string;table?:TableData;document?:MergeBlock[];fileId?:string;format?:string;native?:boolean}
export interface SOpenResult {browserId?:number;fileName?:string;note:string}
const PROVIDERS:Record<string,string>={google:'Google',microsoft:'Microsoft',github:'GitHub',slack:'Slack',discord:'Discord'};
function ProviderIcon({provider}:{provider:string}){
  if(provider==='google')return <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.5-.2-2.2H12v4.2h5.4a4.6 4.6 0 0 1-2 3v2.7h3.3c2-1.8 2.9-4.5 2.9-7.7"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.7c-.9.6-2 .9-3.4.9-2.6 0-4.9-1.8-5.7-4.1H2.9v2.8A10 10 0 0 0 12 22"/><path fill="#FBBC05" d="M6.3 13.7a6 6 0 0 1 0-3.4V7.5H2.9a10 10 0 0 0 0 9l3.4-2.8"/><path fill="#EA4335" d="M12 6.2c1.5 0 2.8.5 3.8 1.5l2.9-2.9A9.6 9.6 0 0 0 12 2a10 10 0 0 0-9.1 5.5l3.4 2.8C7.1 8 9.4 6.2 12 6.2"/></svg>;
  if(provider==='microsoft')return <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true">{[[2,2,'#f25022'],[13,2,'#7fba00'],[2,13,'#00a4ef'],[13,13,'#ffb900']].map(([x,y,fill])=><rect key={String(fill)} x={x} y={y} width="9" height="9" fill={String(fill)}/>)}</svg>;
  return provider==='github'?<Github size={18}/>:provider==='slack'?<Hash size={18}/>:<Gamepad2 size={18}/>;
}
function errorText(error:unknown){return String(error).replace(/^Error: Error invoking remote method '[^']+': Error: /,'');}
function AccountImage({provider,avatar,label}:{provider:string;avatar?:string;label:string}){
  const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[avatar]);
  return avatar&&!failed?<img className="account-avatar" src={avatar} alt={label+'のプロフィール画像'} onError={()=>setFailed(true)}/>:<ProviderIcon provider={provider}/>;
}
export function AccountIcons(){
  const [sAccounts,setSAccounts]=useState<SAccount[]>([]),[api,setApi]=useState<ConnectionStatus|null>(null),[selected,setSelected]=useState<string|null>(null),[clearS,setClearS]=useState(true),[clearAPI,setClearAPI]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let alive=true;window.csv.sAccounts().then(value=>{if(alive)setSAccounts(value);}).catch(()=>{});window.csv.connections().then(value=>{if(alive)setApi(value);}).catch(()=>{});const s=window.csv.onSAccounts(setSAccounts),a=window.csv.onConnectionsChanged(setApi);return()=>{alive=false;s();a();};},[]);
  const connected=Object.keys(PROVIDERS).filter(p=>sAccounts.some(a=>a.provider===p&&a.connected)||api?.providers[p]?.connected),sActive=sAccounts.find(a=>a.provider===selected&&a.connected),apiActive=!!selected&&!!api?.providers[selected]?.connected;
  async function logout(){if(!selected)return;setBusy(true);setError('');try{if(sActive&&clearS)setSAccounts(await window.csv.sLogout(selected));if(apiActive&&clearAPI)setApi(await window.csv.logout(selected));setSelected(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <><div className="account-icons" aria-label="接続済みアカウント">{connected.map(p=>{const account=sAccounts.find(a=>a.provider===p&&a.connected),profile=api?.providers[p],avatar=account?account.avatar:profile?.avatar,label=account?.label||profile?.profileName||PROVIDERS[p];return <button key={p} className="account-icon icon-btn" title={PROVIDERS[p]+' · '+label+' — ログアウト確認'} aria-label={PROVIDERS[p]+'のアカウントを確認'} onClick={()=>{setSelected(p);setClearS(true);setClearAPI(true);setError('');}}><AccountImage provider={p} avatar={avatar} label={label}/><small>{account?'S':'API'}</small></button>;})}</div>{selected&&<div className="modal-overlay account-logout-overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="アカウントのログアウト確認"><div className="modal-heading"><h2>{PROVIDERS[selected]}からログアウト</h2><button className="icon-btn" aria-label="アカウント確認を閉じる" disabled={busy} onClick={()=>setSelected(null)}><X size={18}/></button></div><p className="modal-description">{sActive?.label||PROVIDERS[selected]}の接続を解除しますか？</p>{sActive&&<label className="check-field"><input type="checkbox" checked={clearS} onChange={e=>setClearS(e.target.checked)}/>S内部ブラウザのログインを解除</label>}{apiActive&&<label className="check-field"><input type="checkbox" checked={clearAPI} onChange={e=>setClearAPI(e.target.checked)}/>既存の「接続」の認証を解除</label>}<p className="export-note">他のブラウザと、Teamsなどの外部アプリのログインは保持されます。OAuthアプリの登録設定は残ります。</p>{error&&<p className="share-error" role="alert">{error}</p>}<div className="modal-actions"><button disabled={busy} onClick={()=>setSelected(null)}>キャンセル</button><button className="primary" disabled={busy||!(sActive&&clearS||apiActive&&clearAPI)} onClick={logout}><LogOut size={15}/>{busy?'ログアウト中':'ログアウト'}</button></div></section></div>}</>;
}
export function SConnections({onClose}:{onClose():void}){
  const [services,setServices]=useState<SService[]>([]),[accounts,setAccounts]=useState<SAccount[]>([]),[selected,setSelected]=useState('drive'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[confirm,setConfirm]=useState<string|null>(null);
  useEffect(()=>{window.csv.sServices().then(setServices).catch(e=>setError(errorText(e)));window.csv.sAccounts().then(setAccounts).catch(e=>setError(errorText(e)));return window.csv.onSAccounts(setAccounts);},[]);
  async function open(native=false){setBusy(true);setError('');try{setNote((await window.csv.sOpen({service:selected,native})).note);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function logout(){if(!confirm)return;setBusy(true);try{setAccounts(await window.csv.sLogout(confirm));setConfirm(null);setNote('S接続のログイン情報を消去しました。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <><div className="modal-heading"><h2>Sアカウント接続</h2><button className="icon-btn" aria-label="Sアカウント接続を閉じる" onClick={onClose}><X size={18}/></button></div><p className="modal-description">内部ブラウザでサービスにログインし、画面上部の「このログインを使用」で登録します。既存の「接続」とは別にログインを管理します。</p><label className="form-field">接続先<select aria-label="Sアカウント接続先" value={selected} onChange={e=>setSelected(e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{s.name}{s.id==='teams'?'（ウェブ / アプリ）':''}</option>)}</select></label><div className="s-connect-actions"><button className="primary" disabled={busy||!services.length} onClick={()=>open()}><Globe size={15}/>内部ブラウザでログイン</button>{services.find(s=>s.id===selected)?.native&&<button disabled={busy} onClick={()=>open(true)}><ExternalLink size={15}/>{selected==='teams'?'Teams':'サービス'}アプリを開く</button>}</div><p className="export-note">Googleなどが内部ブラウザでの認証を制限する場合は、既存の「接続」を利用してください。外部アプリのログイン・ログアウトは、そのアプリ側で行います。</p><div className="s-account-list">{accounts.map(account=><div key={account.provider}><AccountImage provider={account.provider} avatar={account.avatar} label={account.label}/><span><strong>{PROVIDERS[account.provider]}</strong><small>{account.connected?account.label+' · ユーザー確認済み':'未登録'}</small></span><button disabled={busy} aria-label={PROVIDERS[account.provider]+'のS接続をログアウト'} onClick={()=>{setConfirm(account.provider);setError('');}}>{account.connected?'ログアウト':'ログイン情報を消去'}</button></div>)}</div>{confirm&&<div className="s-confirm"><p>{PROVIDERS[confirm]}のS内部ブラウザのログインを解除しますか？既存の「接続」は保持されます。</p><button disabled={busy} onClick={()=>setConfirm(null)}>キャンセル</button><button className="primary" disabled={busy} onClick={logout}>ログアウト</button></div>}{error&&<p className="share-error" role="alert">{error}</p>}{note&&<p className="share-result" role="status">{note}</p>}</>;
}
export function SSharing({table,document,fileId,fileName,hasDocument,onDocument,onClose}:{table:TableData|null;document?:MergeBlock[];fileId?:string;fileName?:string;hasDocument:boolean;onDocument():void;onClose():void}){
  const [services,setServices]=useState<SService[]>([]),[service,setService]=useState('drive'),[title,setTitle]=useState(fileName?.replace(/\.[^.]+$/,'')||'CSV nyaan Viewer export'),[recipient,setRecipient]=useState(''),[message,setMessage]=useState(''),[format,setFormat]=useState('csv'),[source,setSource]=useState(document?.length?'document':'selection'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
  useEffect(()=>{window.csv.sServices().then(setServices).catch(e=>setError(errorText(e)));},[]);
  useEffect(()=>{if(document?.length)setSource('document');},[document]);
  async function share(){setBusy(true);setError('');try{const data=source==='file'?{fileId}:source==='document'?{document}:{table:table||undefined};setNote((await window.csv.sOpen({service,title,recipient,message,format,...data})).note);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <><div className="modal-heading"><h2>S共有</h2><button className="icon-btn" aria-label="S共有を閉じる" onClick={onClose}><X size={18}/></button></div><p className="modal-description">共有ファイルを用意し、ログイン済みの内部ブラウザでサービスを開きます。添付・アップロード・送信はサービスの画面で確認してください。</p><label className="form-field">共有先<select aria-label="S共有先" value={service} onChange={e=>{setService(e.target.value);if(['sheets','excel'].includes(e.target.value))setFormat('xlsx');setNote('');}}>{services.map(s=><option key={s.id} value={s.id}>{s.name}{s.id==='teams'?'（ウェブ / アプリ）':''}</option>)}</select></label><label className="form-field">共有する内容<select aria-label="S共有の内容" value={source} onChange={e=>{setSource(e.target.value);if(e.target.value==='document')onDocument();}}>{table&&<option value="selection">選択範囲のデータ</option>}{fileId&&<option value="file">開いているファイル全体（{fileName}）</option>}{hasDocument&&<option value="document">ファイル結合の文書（グラフ込みZIP）</option>}</select></label>{source==='selection'&&<label className="form-field">出力形式<select aria-label="S共有の出力形式" value={format} onChange={e=>setFormat(e.target.value)}><option value="csv">CSV</option><option value="xlsx">XLSX（セル文字列を保持）</option><option value="md">Markdown</option><option value="txt">TXT（タブ区切り）</option></select></label>}<label className="form-field">件名 / ファイル名<input aria-label="S共有の件名" value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/></label><label className="form-field">宛先 / チャンネル<input aria-label="S共有の宛先" value={recipient} maxLength={300} onChange={e=>setRecipient(e.target.value)} placeholder="メールアドレス等。チャットのチャンネルはサービス画面で選択"/></label><label className="form-field">メッセージ<textarea aria-label="S共有のメッセージ" value={message} maxLength={8000} rows={3} onChange={e=>setMessage(e.target.value)}/></label><p className="export-note">{service==='github'?'Gistでは内部ブラウザ上部の「本文をコピー」で貼り付けられます。公開範囲はGitHubで確認してください。':service==='sheets'||service==='excel'?'内部ブラウザのサービス画面でファイルをインポート／アップロードしてください。':'サービス画面の添付ボタンを押すと、用意した共有ファイルを選択できます。'}{services.find(s=>s.id===service)?.native&&' 内部ブラウザから外部アプリも開けます。アプリ側では保存した共有ファイルを添付します。'}</p>{error&&<p className="share-error" role="alert">{error}</p>}{note&&<p className="share-result" role="status">{note}</p>}<div className="modal-actions"><button onClick={onClose}>閉じる</button><button className="primary" disabled={busy||!services.length||!(source==='file'?fileId:source==='document'?document?.length:table)} onClick={share}><Share2 size={15}/>{busy?'共有ファイルを準備中':'内部ブラウザで共有'}</button></div></>;
}
