import React, { useEffect, useState } from 'react';
import { Check, LogIn, Send, Settings, ExternalLink, X, Share2 } from 'lucide-react';
import type { TableData, MergeBlock } from './data';
export interface ConnectionStatus { secureStorage:boolean; providers:Record<string,{clientId?:string;tenant?:string;connected:boolean;hasSecret:boolean}> }
export interface ShareResult { url?:string;id?:string;note?:string }
const SERVICES=[['gmail','Gmail','google'],['chat','Google Chat','google'],['sheets','Google スプレッドシート','google'],['drive','Google Drive','google'],['onedrive','OneDrive','microsoft'],['excel','Excel オンライン','microsoft'],['outlook','Outlook メール','microsoft'],['discord','Discord','discord'],['slack','Slack','slack'],['github','GitHub Gist','github'],['teams','Microsoft Teams（追加）','microsoft']];
const PROVIDERS=[['google','Google'],['microsoft','Microsoft'],['github','GitHub'],['slack','Slack'],['discord','Discord']];
export function Sharing({table,document,onClose}:{table:TableData|null;document?:MergeBlock[];onClose():void}){
  const [status,setStatus]=useState<ConnectionStatus|null>(null),[service,setService]=useState('drive'),[mode,setMode]=useState('direct'),[recipient,setRecipient]=useState(''),[title,setTitle]=useState('CSV nyaan Viewer export'),[message,setMessage]=useState(''),[isPublic,setIsPublic]=useState(false);
  const [provider,setProvider]=useState('google'),[configure,setConfigure]=useState(!table),[clientId,setClientId]=useState(''),[clientSecret,setClientSecret]=useState(''),[tenant,setTenant]=useState('common'),[accessToken,setAccessToken]=useState(''),[webhook,setWebhook]=useState('');
  const [busy,setBusy]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<ShareResult|null>(null),[deviceCode,setDeviceCode]=useState('');
  const selectedProvider=SERVICES.find(s=>s[0]===service)![2],connected=status?.providers[selectedProvider]?.connected;
  useEffect(()=>{window.csv.connections().then(setStatus);return window.csv.onAuth(info=>setDeviceCode(info.code));},[]);
  useEffect(()=>{setClientId(status?.providers[provider]?.clientId||'');setTenant(status?.providers[provider]?.tenant||'common');setClientSecret('');setAccessToken('');setWebhook('');},[provider,status]);
  async function run(label:string,fn:()=>Promise<void>){setBusy(label);setError('');setResult(null);try{await fn();}catch(e){setError(String(e).replace(/^Error: Error invoking remote method '[^']+': Error: /,''));}finally{setBusy('');setDeviceCode('');}}
  const save=()=>run('設定を保存中',async()=>{setStatus(await window.csv.configureConnection(provider,{clientId,clientSecret,tenant,access_token:accessToken,webhook}));setResult({note:'接続設定を保存しました。'});});
  const login=()=>run('ブラウザでログインしてください',async()=>{setStatus(await window.csv.login(provider));setResult({note:'ログインしました。'});});
  const share=()=>run(mode==='direct'?'共有を実行中':'共有先を開いています',async()=>{if(!table)return;const options={service,table,document,recipient,title,message,name:title.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,100)+'.csv',public:isPublic,native:mode==='native'};setResult(await(mode==='direct'?window.csv.share(options):window.csv.shareBrowser(options)));});
  return <><div className="modal-heading"><h2>{configure?'接続設定':'共有'}</h2><button className="icon-btn" aria-label="共有画面を閉じる" onClick={()=>{window.csv.cancelLogin();onClose();}}><X size={18}/></button></div><div className="share-tabs"><button className={!configure?'selected':''} disabled={!table} onClick={()=>setConfigure(false)}><Share2 size={15}/>データを共有</button><button className={configure?'selected':''} onClick={()=>setConfigure(true)}><Settings size={15}/>接続設定</button></div>
  {configure?<><p className="modal-description">OAuthアプリの登録情報を入力してください。Slack・DiscordはBotまたはWebhookで接続します。アカウントのパスワードは入力しません。</p><label className="form-field">接続先<select value={provider} onChange={e=>setProvider(e.target.value)}>{PROVIDERS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{['google','microsoft','github'].includes(provider)&&<><label className="form-field">OAuthクライアントID<input aria-label="OAuthクライアントID" value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="未登録の場合は各サービスでアプリを登録"/></label>{provider==='google'&&<label className="form-field">デスクトップアプリ用クライアントシークレット<input type="password" value={clientSecret} onChange={e=>setClientSecret(e.target.value)} placeholder={status?.providers[provider]?.hasSecret?'保存済み（変更時のみ入力）':'Googleのデスクトップアプリ登録値'}/></label>}{provider==='microsoft'&&<label className="form-field">テナント<input value={tenant} onChange={e=>setTenant(e.target.value)} placeholder="common / organizations / tenant ID"/></label>}<div className="export-note">{provider==='github'?'GitHub OAuth AppでDevice Flowを有効にします。ログイン時は表示されたコードをGitHubで入力してください。共有はGistとして作成します。':'ループバックURI: http://localhost:53682/oauth/callback。Googleはデスクトップアプリ、Microsoftはパブリッククライアントとして登録してください。権限と登録手順は同梱の接続ガイドを参照してください。'}</div></>}
  <label className="form-field">{provider==='discord'?'Botトークン（任意）':provider==='slack'?'Bot OAuthトークン（任意）':'既存のアクセストークン（任意）'}<input type="password" value={accessToken} onChange={e=>setAccessToken(e.target.value)} placeholder="設定する場合のみ入力"/></label>{['slack','discord'].includes(provider)&&<label className="form-field">Webhook URL（任意）<input type="password" value={webhook} onChange={e=>setWebhook(e.target.value)} placeholder={provider==='slack'?'https://hooks.slack.com/services/…':'https://discord.com/api/webhooks/…'}/></label>}
  <div className="connection-state">{status?.providers[provider]?.connected?<><Check size={15}/>接続情報あり</>:<>未接続</>}{!status?.secureStorage&&<p>OSの安全な保存領域が利用できないため、トークンは今回の起動中だけ保持します。</p>}</div><div className="modal-actions"><button disabled={!!busy} onClick={save}>設定を保存</button>{['google','microsoft','github'].includes(provider)&&<button className="primary" disabled={!!busy||!status?.providers[provider]?.clientId} onClick={login}><LogIn size={15}/>ログイン</button>}<button disabled={!!busy||!status?.providers[provider]?.connected} onClick={()=>run('ログアウト中',async()=>{setStatus(await window.csv.logout(provider));})}>ログアウト</button></div></>:<><p className="modal-description">{document?.length?document.length+'ブロックのMarkdown文書':table?.rows.length.toLocaleString()+'行 × '+table?.headers.length+'列'}を共有します。メールは添付付き下書きを作成し、チャットは指定先に投稿します。</p><label className="form-field">共有先<select aria-label="共有先" value={service} onChange={e=>{setService(e.target.value);setResult(null);setRecipient('');}}>{SERVICES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="form-field">共有方法<select value={mode} onChange={e=>setMode(e.target.value)}><option value="direct">ログイン情報で直接共有</option><option value="browser">ブラウザで開く</option>{['outlook','discord','slack','github'].includes(service)&&<option value="native">アプリで開く（インストール済みの場合）</option>}</select></label><label className="form-field">宛先 / チャンネル<input aria-label="共有の宛先" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder={service==='chat'?'spaces/xxxx':service==='slack'?'SlackチャンネルID（Webhookでは設定先固定）':service==='discord'?'DiscordチャンネルID（Webhookでは設定先固定）':service==='github'&&mode==='native'?'owner/repository':'メールアドレスなど（保存先共有では不要）'}/></label><label className="form-field">件名 / ファイル名<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="form-field">メッセージ<textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)}/></label>{service==='github'&&mode==='direct'&&<label className="check-field"><input type="checkbox" checked={isPublic} onChange={e=>setIsPublic(e.target.checked)}/>公開Gistとして作成（未選択でもURLを知る人は閲覧可）</label>}
  <div className="export-note">{document?.length&&<p>{['sheets','excel'].includes(service)?'文書内の表だけをセルに変換します。テキスト・グラフは含みません。':service==='github'?'Gistには.md本文だけを共有します。グラフ画像は含みません。':service==='slack'?'Bot接続は.mdと画像をまとめたZIPを投稿します。Webhookでは本文プレビューだけです。':'直接共有では.md本文とグラフ画像をまとめたZIPを送ります。'}</p>}{mode==='direct'?(service==='gmail'||service==='outlook'?'ファイル添付の下書きを作成します。送信はメール画面で行ってください。':service==='chat'?'DriveにCSVを作成し、指定スペースへリンクを投稿します。ファイル権限の設定は別途必要です。':service==='slack'?'Bot接続はCSVをアップロードします。Webhook接続は先頭1,400文字のプレビューのみです。':service==='discord'?'BotまたはWebhookでCSVファイルを投稿します。Webhookの場合はその設定先へ送信します。':service==='teams'?'OneDriveにCSVを保存してTeamsの共有画面を開きます。送信はTeamsで確定してください。':service==='excel'?'全セルを文字列としてXLSXを作成し、OneDriveにアップロードします。':service==='sheets'?'Google SheetsのRAW指定で文字列を保持します。':'接続先に新しいファイルを作成します。OneDriveには識別子付きのファイル名で保存します。'):'共有先の画面を開きます。ファイルの自動添付・アップロードは行いません。メールの本文には先頭4,000文字までを挿入します。'}</div>{mode==='direct'&&!connected&&<button className="quiet-button" onClick={()=>{setProvider(selectedProvider);setConfigure(true);}}>未接続です。接続設定を開く</button>}<div className="modal-actions"><button onClick={onClose}>閉じる</button><button className="primary" disabled={!!busy||(mode==='direct'&&!connected)} onClick={share}>{mode==='direct'?<Send size={15}/>:<ExternalLink size={15}/>} {mode==='direct'?(service==='gmail'||service==='outlook'?'下書きを作成':'共有を実行'):'共有先を開く'}</button></div></>}
  {busy&&<div className="share-progress">{busy}{deviceCode&&<strong>認証コード: {deviceCode}</strong>}{busy.includes('ログイン')&&<button onClick={()=>window.csv.cancelLogin()}>キャンセル</button>}</div>}{error&&<div className="share-error" role="alert">{error}</div>}{result&&<div className="share-result"><Check size={16}/><span>{result.note||'共有が完了しました。'}</span>{result.url&&<button onClick={()=>window.csv.openExternal(result.url!)}><ExternalLink size={14}/>開く</button>}</div>}
  </>;
}
