import React,{useState} from 'react';
import {Plus,Trash2,Table2} from 'lucide-react';
import type {SavedTable} from './analysis-types';
import type {Tab} from './types';
export function TablePreview({tables,tabs,onRename,onDelete,onAdd,onSelection}:{tables:SavedTable[];tabs:Tab[];onRename(id:string,name:string):void;onDelete(id:string):void;onAdd(id:string,sheet:string|undefined,address:string):Promise<void>;onSelection():void}){
  const [file,setFile]=useState(''),[sheet,setSheet]=useState(''),[address,setAddress]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const files=tabs.filter(t=>['csv','excel'].includes(t.meta.kind)),current=files.find(t=>t.meta.id===file)||files[0],activeSheet=current?.meta.sheets?.includes(sheet)?sheet:current?.meta.sheet;
  async function add(){if(!current)return;setBusy(true);setError('');try{await onAdd(current.meta.id,activeSheet,address);setAddress('');}catch(e){setError(String(e));}finally{setBusy(false);}}
  return <div className="table-preview"><div className="table-create-bar"><button disabled={!current||busy} onClick={onSelection}><Table2 size={14}/>選択範囲から作成<kbd>Ctrl+T</kbd></button><select aria-label="テーブル追加元ファイル" disabled={busy} value={current?.meta.id||''} onChange={e=>{setFile(e.target.value);setSheet('');}}>{files.map(t=><option key={t.meta.id} value={t.meta.id}>{t.meta.name||t.meta.path.split(/[\\/]/).pop()}</option>)}</select>{current?.meta.sheets&&<select aria-label="テーブル追加元シート" disabled={busy} value={activeSheet||''} onChange={e=>setSheet(e.target.value)}>{current.meta.sheets.map(s=><option key={s}>{s}</option>)}</select>}<input aria-label="テーブルのセル番地" placeholder="A2:D20" value={address} onChange={e=>setAddress(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add();}}/><button disabled={!current||!address.trim()||busy} onClick={add}><Plus size={14}/>番地から追加</button></div>{error&&<p role="alert">{error}</p>}<div className="saved-tables">{!tables.length&&<p className="pane-empty">範囲を選択してCtrl＋Tでテーブルを作成します。テーブルはアプリを開いている間、一時保存されます。</p>}{tables.map(t=><section className="saved-table" key={t.id} style={{'--table-color':t.color} as React.CSSProperties}><header><span className="table-swatch"/><input aria-label={'テーブル名 '+t.id} title="空欄にすると既定名に戻ります" value={t.name} onChange={e=>onRename(t.id,e.target.value)} onBlur={e=>{if(!e.target.value.trim())onRename(t.id,[t.fileName,t.sheet||'CSV',t.address].join('|'));}}/><button className="icon-btn" aria-label={t.name+'を削除'} onClick={()=>onDelete(t.id)}><Trash2 size={14}/></button></header><small>{t.fileName} | {t.sheet||'CSV'} | {t.address} · {t.rows.length}行 × {t.headers.length}列</small><div className="saved-table-scroll"><table><thead><tr>{t.headers.slice(0,30).map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{t.rows.slice(0,50).map((r,i)=><tr key={i}>{r.slice(0,30).map((v,c)=><td key={c}>{v}</td>)}</tr>)}</tbody></table></div>{(t.rows.length>50||t.headers.length>30)&&<small>プレビューは先頭50行・30列。分析は保存したテーブル全体から標本化します。</small>}</section>)}</div></div>;
}
